cve/Dockerfile
cve/docker-compose.yml
cve/entrypoint.sh
cve/src/config.yml.sample
cve/src/cve.py
cve/src/cvetostix2.py
cve/src/requirements.txt

As I saw there was a [need ](https://github.com/OpenCTI-Platform/opencti/issues/49)for a connector that imports from the CVE platform, I created one. 
I simply copied the structure from the mitre connector and adapted the code from there.
It imports the data from files issued by [nvd.nist.gov](https://nvd.nist.gov/vuln/data-feeds). It calls another python scripts that creates the stix2 bundle from that file.

Created the CVE connector

---

misp/src/misp.py

Fixed config file checks  so that if it doesn't exist, program doesnt crash.

FIX: if config file doesn't exist, program crashes

---

amitt/Dockerfile
amitt/docker-compose.yml
amitt/entrypoint.sh
amitt/src/amitt.py
amitt/src/config.yml.sample
amitt/src/requirements.txt

AMITT (Adversarial Misinformation and Influence Tactics and Techniques) framework for describing disinformation incidents. 
https://github.com/misinfosecproject/amitt_framework
This connector loads experimental AMITT STIX2 data.  The content of the stix2 repo is expected to change as the misinfosec working group matures the AMITT framework.

new: [amitt] add new AM!TT connector

---

cve/docker-compose.yml
cve/src/config.yml.sample
cve/src/cve.py

[CVE] Fixed the hard link to a variable #50

---

cryptolaemus/Dockerfile
cryptolaemus/docker-compose.yml
cryptolaemus/entrypoint.sh
cryptolaemus/src/config.yml.sample
cryptolaemus/src/cryptolaemus.py
cryptolaemus/src/requirements.txt

Add a connector for the Cryptolaemus Team Emotet update

---

.circleci/config.yml
.gitignore
export-file-csv/src/export-file-csv.py
import-file-pdf-observables/src/import-file-pdf-observables.py
import-file-pdf-observables/src/iocp.py
malpedia/src/malpedia.py
virustotal/src/virustotal.py

This PR adds (conservative) linting and formatting checks to circl-ci.
* Add black to check formatting
* Use flake8 to output stuff we really want to fix
* add `.vscode`to .gitignore
* Fix all-the-linting-errors :)

Enhance circl-ci with formatting & linting

---

LastInfoSec/Dockerfile
LastInfoSec/README.md
LastInfoSec/docker-compose.yml
LastInfoSec/entrypoint.sh
LastInfoSec/src/config.yml.sample
LastInfoSec/src/lastinfosec.py
LastInfoSec/src/requirements.txt

[LastInfoSec] Create the connector (#111)

---

virustotal/docker-compose.yml

Update docker-compose.yml for VT

---

ipinfo/docker-compose.yml

Update docker-compose.yml for IPInfo

---

malpedia/src/malpedia/models.py

Fix malpedia flake8 check

---

malpedia/Readme.md
malpedia/docker-compose.yml
malpedia/src/config.yml.sample

Reformat Readme and improve default config to be usable by new users.

Improve Malpedia documentation and default config

---

.gitignore
malpedia/Readme.md
malpedia/docker-compose.yml
malpedia/src/malpedia/client.py
malpedia/src/malpedia/core.py
malpedia/src/malpedia/knowledge.py
malpedia/src/malpedia/models.py
malpedia/src/malpedia/utils.py
malpedia/src/requirements.txt

This PR fixes multiple bugs with the Malpedia connector.

Fix Malpedia connector

---

lastinfosec/src/lastinfosec.py

Hello ,
I fixed the insert for the lastinfosec connector.
Linked to this issue : https://github.com/OpenCTI-Platform/connectors/issues/111
Best regards, 
François

[LastInfoSec] fix import

---

.flake8
malpedia/src/malpedia/core.py
malpedia/src/malpedia/knowledge.py
malpedia/src/malpedia/utils.py

This PR fixes the Malpedia state handling and adds a .flake8 config that is compatible with the slightly extended line length of the black format.

[Malpedia] Fix state handling

---

valhalla/src/valhalla/core.py
valhalla/src/valhalla/knowledge.py

Timestamps need to be converted to `int`.

[Valhalla] Fix state timestamps

---

virustotal/src/virustotal.py

* rename `final_observabke` -> `final_observable`
* log and return `"File not found on VirusTotal."` instead of `ValueError`
* add size attribute

Add size attribute, fix typo, fix file not found

---

hygiene/README.md
hygiene/docker-compose.yml
hygiene/src/config.yml.sample

Also check Artifact values for known false-positives

Update Hygiene default config

---

misp/README.md

Nothing import : Just a simple typo in the connector / misp README

Correcting typo

---

threatbus/.dockerignore
threatbus/.gitignore
threatbus/Dockerfile
threatbus/README.md
threatbus/docker-compose.yml
threatbus/entrypoint.sh
threatbus/src/config.yml.sample
threatbus/src/connector.py
threatbus/src/requirements.txt

This PR adds an OpenCTI connector for [Threat Bus](https://github.com/tenzir/threatbus).

Add Threat Bus connector

---

misp/docker-compose.yml

I forgot to update the docker compose for my new env variable which controls if MISP objects gets imported
Related #366

[MISP] Update docker-compose.yml

---

import-report/README.md

Thanks for the other changes/fixes btw!

[import-report] Renaming of the create_indicator variable in README.md

---

import-report/src/requirements.txt

ioc_finder 6.0.1 fixed a too many false positive issue for ASN parsing
Details: https://github.com/fhightower/ioc-finder/issues/136

[ImportReport] Update requirements.txt

---

import-report/src/reportimporter/config/entity_config.ini
import-report/src/reportimporter/config/observable_config.ini
import-report/src/reportimporter/core.py
import-report/src/reportimporter/report_parser.py
import-report/src/reportimporter/util.py

Changed the way for observable ingestion from `bundle_import` to `self.helper.api.stix_cyber_observable.create` due to this bug:
https://github.com/OpenCTI-Platform/client-python/issues/186
ASN feature ingestion works now.
Also changed the approach for detecting the MITRE ATT&CK techniques due to performance improvements.
- old approach: Checking for every single MITRE ATT&CK id if present in text
- new approach: Extracting the MITRE ATT&CK id using a regex and later verifying the few positive hits with the OpenCTI DB

[import-report] Import report asn improvement

---

import-report/src/reportimporter/report_parser.py

[import-report] Fix defang issue

---

import-report/src/reportimporter/core.py

[import-report] Fix creating indicator issue

---

.circleci/config.yml

Added shodan connector for automatic deployment

[circleci] Added shodan connector

---

virustotal/src/virustotal.py

Only a StixFile has the attribute `name`. An Artifact doesn't have that attribute. 
Fixing error #413

[virustotal] Fix #413

---

elastic/pyproject.toml

Also adjusted module path to `console.py` to align with rename and set the version to 1.0.0.

Updated the scripts entry to match `entrypoint.sh`

---

internal-import-file/import-report/src/reportimporter/report_parser.py

* Fixed issue, when the external library manipulates the extracted value
* #462

[import-report] Fixed #462 Trouble parsing domains / URLs with capital letters

---

internal-enrichment/greynoise/src/greynoise.py
internal-enrichment/greynoise/src/requirements.txt

This replaces PR #460 
---
This PR includes a handful of suggested updates for the GreyNoise connector to provide additional intelligence when the connector is used.
Improvements include:
- Malware Object creation for GN tags that are Worms or Malicious Activity
- Label creation and relationship for all other GN tags
- City/Country Object creation and relationships
- Modified sighting logic to mark sighting as FP if IP is benign (known good actor)
- Actor Objection creation for non-benign actors
- Update GreyNoise Visualizer link in External Reference creation
- Tool Object creation and relationship for VPNs
- Label creation and relationship for TORs and BOTs
- Labels for GN IP classification
- Vulnerability creation and relationships for attached CVEs
- Additional requirement on …

Suggested updates to GreyNoise connector v2

---

internal-enrichment/hygiene/README.md
internal-enrichment/hygiene/docker-compose.yml
internal-enrichment/hygiene/src/config.yml.sample
internal-enrichment/hygiene/src/hygiene.py

* Add configuration parameter for toggling warning lists slow search mode. 
* #471

[hygiene] Add configuration parameter for toggling warning lists slow search mode (#471)

---

template/src/main.py

* Class renaming and link update
* None

[template] Renaming and link update

---

internal-import-file/import-report/src/config.yml.sample
internal-import-file/import-report/src/reportimporter/models.py

* Improved logging for regex compile fails
* Improved config.yml sample
* #483

[import-report] Import report regex error catch

---

.circleci/config.yml
external-import/cape/Dockerfile
external-import/cape/README.md
external-import/cape/docker-compose.yml
external-import/cape/entrypoint.sh
external-import/cape/src/cape/__init__.py
external-import/cape/src/cape/cape.py
external-import/cape/src/cape/telemetry.py
external-import/cape/src/config.yml.sample
external-import/cape/src/main.py
external-import/cape/src/requirements.txt

* Adds a [CAPE Sandbox](https://github.com/kevoreilly/CAPEv2) external-import connector
* N/A
------------------------------
IP addresses  							(IMPLMENTED)
DNS          							(IMPLMENTED)
Malware   		      					(IMPLMENTED)
Process (Command Lines) 				(IMPLMENTED w/ PID and Full Child Process STIX Implementation)
Network Traffic (UDP/TCP/ICMP)			(IMPLMENTED) (Is this useful?)
URL called (HTTP requests) ** Cant do STIX 6.12.2 THUS COVERD BY DNS Names
File (Payloads (Only Suspious dropped))	(IMPLMENTED)
File (Main Binary)						(IMPLMENTED)
- ~~Score Based on MalScore~~ (No way to do this via STIX bundle)
- ~~Addational names via VT~~ (No way to do this via STIX bundle)
Registry Keys							(IMPLMENTED)
-------------------------------
Report for each CAPE Analysis		    			(IMPLMENTED /w …

[external-import] Adds CAPE Sandbox Connector

---

external-import/riskiq/src/riskiq/article_importer.py
external-import/riskiq/src/riskiq/riskiq.py

* Add `RiskIQ` as author of the objects created by the connector. 
N/A

[riskiq] add author for all objects

---

internal-enrichment/hatching-triage-sandbox/docker-compose.yml
internal-enrichment/hatching-triage-sandbox/src/config.yml.sample
internal-enrichment/hatching-triage-sandbox/src/hatching-triage-sandbox.py

* Re-factoring and bug fixes for non-existent keys in overview report
* Add existing analysis capability to use existing analysis to speed up processing times
These changes were made to re-factor some code that is re-used, to fix some bugs where certain keys didn't exist in the triage overview report, and to create a config option for enabling the use of an existing analysis's report rather than submitting a new analysis every time.

[hatching-triage-sandbox] add existing analysis config option and refactoring

---

internal-enrichment/unpac-me/src/config.yml.sample

* Minor changes to the config for the unpac-me internal enrichment connector.

[unpac-me] Update config.yml

---

internal-enrichment/cape-sandbox/docker-compose.yml
internal-enrichment/cape-sandbox/src/cape-sandbox.py
internal-enrichment/cape-sandbox/src/config.yml.sample

* Minor updates to default configuration as CAPEv2 has some bugs that are yet to be worked out

[cape-sandbox] Update config defaults

---

external-import/mitre/src/mitre.py
external-import/mitre/src/requirements.txt

Refactoring of the connector: 
* Add a method `retrieve_data` to handle the http requests.
* Add a method `send_bundle` to send the bundles.  
* Update pycti version. 
N/A

[mitre] add functions to handle http requests and bundles

---

external-import/misp/src/misp.py

* In line 368, the code first check for "Tags" with a 's' in "Event" dictionary, but this didn't return the values because "Tags" with 's' does not exist, but only "Tag", also by using `.get` make the core more clean.
* In line 298 and 309, the code only consider if there isn't any data, and forget to consider a empty string, so to fix this just check if it's not empty.

Fixing problems to get tags and empty values in config file

---

external-import/mitre/src/mitre.py

* Use confidence level config when importing Mitre data
* https://github.com/OpenCTI-Platform/connectors/issues/553

[Mitre] Add confidence level to bundle objects

---

external-import/misp/src/misp.py

* Extend the connector state with an additional timestamp "latest_event_timestamp".
* Use the "latest_event_timestamp" to fetch the events from MISP when the connector has already a saved state.
* https://github.com/OpenCTI-Platform/connectors/issues/563

[MISP] Add latest_event_timestamp in connector state

---

internal-import-file/import-document/README.md
internal-import-file/import-document/docker-compose.yml
internal-import-file/import-document/src/config.yml.sample
internal-import-file/import-document/src/reportimporter/constants.py
internal-import-file/import-document/src/reportimporter/report_parser.py

* Added simple CSV support, parsing it like text files
* #98 
- [ x I tested the code for its functionality using different use cases

[import-document] Add CSV file support

---

.circleci/config.yml
internal-export-file/export-report-pdf/Dockerfile

* Fix docker build for export-report-pdf
* #600

[export-report-pdf] Fix docker build #600

---

internal-enrichment/abuseipdb/src/abuseipdb.py

[abuse-ip] Fix key error

---

external-import/taxii2/src/taxii2.py
internal-import-file/import-document/src/reportimporter/util.py

* Prevent crash with empty bundles
* #411

Taxii handle empty bundle

---

internal-export-file/export-report-pdf/src/resources/report.css.template
internal-export-file/export-report-pdf/src/resources/report.html

* These changes were made to fix report formatting issues such as:
* Tables being cut off due to weasyprint bug
* Company name/address appears on second page
* Description/Confidence exist in one column and don't fill page width

[ExportReportPdf] Report Formatting Fixes 

---

external-import/valhalla/docker-compose.yml
external-import/valhalla/src/config.yml.sample
external-import/valhalla/src/requirements.txt
external-import/valhalla/src/valhalla/core.py
external-import/valhalla/src/valhalla/knowledge.py
external-import/valhalla/src/valhalla/models.py

This PR updates the Vahalla connector for the new worker API and removes any direct OpenCTI API calls in favor of uploading STIX 2.1 bundles.
Tested with the current stable OpenCTI version 5.2.3

[Valhalla] Refactor the whole connector for the new worker API

---

internal-import-file/import-document/src/reportimporter/config/entity_config.ini
internal-import-file/import-document/src/reportimporter/core.py
internal-import-file/import-document/src/reportimporter/models.py

* Adding custom attributes to graphql queries
* Fetching only needed fields from graphql
* Currently the graphql query will fetch all data, this can cause ES timeout on smaller resources.

[import-document] Performance improvement on graphql queries

---

internal-export-file/export-report-pdf/Dockerfile
internal-export-file/export-report-pdf/README.md
internal-export-file/export-report-pdf/src/export-report-pdf.py
internal-export-file/export-report-pdf/src/requirements.txt
internal-export-file/export-report-pdf/src/resources/intrusion-set.css.template
internal-export-file/export-report-pdf/src/resources/intrusion-set.html

* [export-report-pdf] Handle IntrusionSet Entitities
Changes have been made to the ExportReportPdf connector to allow for the export of IntrusionSet entity types to PDF.

[export-report-pdf] Handle IntrusionSet Entitities

---

external-import/socprime/src/socprime/core.py
external-import/socprime/src/socprime/mitre_attack.py

* add SOC Prime author to sigma indicators created by connector
* add MITRE ATT&CK techniques to sigma indicators created by connector
* add MITRE ATT&CK tools and software to sigma indicators created by connector
* add MITRE ATT&CK threat actors to sigma indicators created by connector

SOC Prime external-import connector update

---

internal-enrichment/virustotal/src/virustotal/builder.py
internal-enrichment/virustotal/src/virustotal/virustotal.py
internal-enrichment/virustotal/tests/test_builder.py

* Add external reference to virustotal website for the main observable being enriched (and not only the indicator).
* N/A

[virustotal] add external reference to virustotal website

---

external-import/maltiverse/.dockerignore
external-import/maltiverse/Dockerfile
external-import/maltiverse/README.md
external-import/maltiverse/docker-compose.yml
external-import/maltiverse/entrypoint.sh
external-import/maltiverse/src/config.yml.sample
external-import/maltiverse/src/main.py
external-import/maltiverse/src/requirements.txt

* Add [Maltiverse](https://maltiverse.com) external connector

Add maltiverse connector

---

.circleci/config.yml

* Add missing CI configuration for connector-maltiverse
* https://github.com/OpenCTI-Platform/connectors/issues/739

Add CI to connector-maltiverse

---

internal-enrichment/import-external-reference/README.md

Corrects configuration params to work.
* Updates and corrects mistakes in the import-external-reference connector documentation
* #752

Fixes #752 - Update and correct import-external-reference readme

---

external-import/mandiant/src/mandiant.py

Reports way of tracking , from epoch to "Next" functionality in APIv4.
Added PDF to reports.
Collecting data as Stix2.1 instead of Json.
#722
#740
- [x ] I consider the submitted work as finished

Updating Mandiant connector to collect reports

---

external-import/malpedia/src/malpedia/client.py
external-import/malpedia/src/malpedia/core.py
external-import/maltiverse/src/main.py
external-import/riskiq/src/riskiq/client.py
external-import/riskiq/src/riskiq/riskiq.py

* Use the logging methods of the `OpenCTIConnectorHelper` in the clients class instead of instanciating another logger. 
* n/a

[riskiq/malpedia] use logger of OpenCTIConnectorHelper for clients

---

.circleci/config.yml
external-import/urlscan/.dockerignore
external-import/urlscan/Dockerfile
external-import/urlscan/README.md
external-import/urlscan/docker-compose.yml
external-import/urlscan/poetry.lock
external-import/urlscan/pyproject.toml
external-import/urlscan/src/config.yml.sample
external-import/urlscan/src/urlscan/__init__.py
external-import/urlscan/src/urlscan/__main__.py
external-import/urlscan/src/urlscan/client.py
external-import/urlscan/src/urlscan/connector.py
external-import/urlscan/src/urlscan/hygiene.py
external-import/urlscan/src/urlscan/loop.py
external-import/urlscan/src/urlscan/patterns.py

* Implement a urlscan.io connector
* #432
- 👍

[urlscan] Implement connector

---

.circleci/config.yml

* Add MWDB connector to CircleCI
* None
Just added MWDB external connector to CircleCI

[MWDB-external_import] Added MWDB to CircleCI

---

.circleci/config.yml
internal-enrichment/shodan-internetdb/Dockerfile
internal-enrichment/shodan-internetdb/README.md
internal-enrichment/shodan-internetdb/docker-compose.yml
internal-enrichment/shodan-internetdb/poetry.lock
internal-enrichment/shodan-internetdb/pyproject.toml
internal-enrichment/shodan-internetdb/src/config.yml.sample
internal-enrichment/shodan-internetdb/src/shodan_internetdb/__init__.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/__main__.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/client.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/config.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py

* Shodan InternetDB connector!
* n/a
Replacement for the regular Shodan connector, less information but free (a recently released service). Allows for updating IPv4 observables.

[shodan-idb] Shodan InternetDB connector

---

external-import/urlhaus-recent-payloads/docker-compose.yml
external-import/urlhaus-recent-payloads/src/config.yml.sample

* Update comments for URLHaus Recent Payloads config

[URLHaus Recent Payloads] Update Comments for Config

---

external-import/cisa-known-exploited-vulnerabilities/src/main.py

Properly creating STIX objects
Removed references to OpenCTI UUID Tool
*
*

Removed references to OpenCTI UUID tool

---

external-import/mandiant/docker-compose.yml
external-import/mandiant/src/mandiant.py

Filter to ignore reports - Currently, Vulnerability reports contain a lot of software data creating latency processing. 
Fix News-Analysis report.
Update Threat-Actor to Intrusion-Set based on the parameter
Removed "Mandiant" name as Self Marking definition, just left the one define on the parameter.
#652 
#836
#837

Mandiant Connector, adding Report features with the latest update.

---

.circleci/config.yml
external-import/abuse-ssl/.dockerignore
external-import/abuse-ssl/Dockerfile
external-import/abuse-ssl/README.md
external-import/abuse-ssl/docker-compose.yml
external-import/abuse-ssl/entrypoint.sh
external-import/abuse-ssl/src/abuse-ssl.py
external-import/abuse-ssl/src/config.yml.sample
external-import/abuse-ssl/src/requirements.txt

* added abuse-ssl connector (see readme for more info)
This is my first PR, I have a few more that require some tuning, so be gentle please :)
This specific pull request contains the abuse-ssl connector. It pulls data from a CSV, generates indicators based on it. Nothing heavy.

Abuse-ssl IP blacklist import connector

---

external-import/abuse-ssl/docker-compose.yml

* changed the service name, so it's consistent with all the other connectors
* updated the version to latest
* changed the connector name, so it's consistent with connector-urlhaus
* changed the connector scope to lowercase, so it's consistent with all the other connectors
* N/A

[ABUSESSL] updated docker-compose.yml

---

external-import/abuseipdb-ipblacklist/docker-compose.yml

* added "connector-" prefix to the service name, so it's consistent with all the other connectors
* N/A

[ABUSEIPDB_IPBLACKLIST] updated the service name in docker-compose.yml

---

.circleci/config.yml
external-import/ironnet/Dockerfile
external-import/ironnet/README.md
external-import/ironnet/docker-compose.yml
external-import/ironnet/poetry.lock
external-import/ironnet/pyproject.toml
external-import/ironnet/src/config.yml.sample
external-import/ironnet/src/ironnet/__init__.py
external-import/ironnet/src/ironnet/__main__.py
external-import/ironnet/src/ironnet/client.py
external-import/ironnet/src/ironnet/config.py
external-import/ironnet/src/ironnet/connector.py
external-import/ironnet/src/ironnet/loop.py

* We started selling a threat feed, so I made a connector.
* Add an IronRadar/IronNet threat feed connector.
* n/a
Been running this in production for several weeks awaiting launch, seems solid.

[IronNet] New connector

---

internal-enrichment/vmray-analyzer/Dockerfile
internal-enrichment/vmray-analyzer/README.md
internal-enrichment/vmray-analyzer/docker-compose.yml
internal-enrichment/vmray-analyzer/entrypoint.sh
internal-enrichment/vmray-analyzer/src/config.yml.sample
internal-enrichment/vmray-analyzer/src/requirements.txt
internal-enrichment/vmray-analyzer/src/vmray-analyzer.py

* [VMRay Analyzer] New Connector

[VMRay Analyzer] New Connector

---

template/src/main.py

* Updates a link to documentation on connector development

Fix link to Connector Development docs in template

---

internal-enrichment/crowdsec/Dockerfile
internal-enrichment/crowdsec/README.md
internal-enrichment/crowdsec/docker-compose.yml
internal-enrichment/crowdsec/entrypoint.sh
internal-enrichment/crowdsec/src/config.yml.sample
internal-enrichment/crowdsec/src/crowdsec.py
internal-enrichment/crowdsec/src/requirements.txt

Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>
* Add CrowdSec CTI connector

Add crowdsec connector

---

external-import/mandiant/src/mandiant.py

* Fixing a typo on a label related to News Analysis.

[Mandiant] fixing a label with a type

---

stream/virustotal-livehunt-rules/README.md

[VirusTotal LiveHunts Stream] Fixing the README file
#917

[VirusTotal LiveHunts Stream] Fixing the README file

---

external-import/cybersixgill/.dockerignore
external-import/cybersixgill/Dockerfile
external-import/cybersixgill/README.md
external-import/cybersixgill/docker-compose.yml
external-import/cybersixgill/entrypoint.sh
external-import/cybersixgill/src/config.yml.sample
external-import/cybersixgill/src/cybersixgill/__init__.py
external-import/cybersixgill/src/cybersixgill/builder.py
external-import/cybersixgill/src/cybersixgill/client.py
external-import/cybersixgill/src/cybersixgill/core.py
external-import/cybersixgill/src/cybersixgill/importer.py
external-import/cybersixgill/src/cybersixgill/utils/__init__.py
external-import/cybersixgill/src/cybersixgill/utils/constants.py
external-import/cybersixgill/src/cybersixgill/utils/indicators.py
external-import/cybersixgill/src/cybersixgill/utils/observables.py
external-import/cybersixgill/src/main.py
external-import/cybersixgill/src/requirements.txt

cybersixgill darkfeed connector

---

stream/splunk/src/splunk.py

Allow the Splunk Stream connector to move on whenever it fails due to a bad message, in this case, it has a bad character.
*#949

Splunk stream to be able to recover from errors

---

external-import/mwdb/README.md
external-import/mwdb/docker-compose.yml
external-import/mwdb/src/config.yml.sample
external-import/mwdb/src/mwdb.py

* Added support for MWDB instances with selfsigned cerfificate   
* Fixed some bugs related to MWDB tag importer routines
*  https://github.com/OpenCTI-Platform/connectors/issues/935
- [ x] I consider the submitted work as finished
- [ x] I tested the code for its functionality using different use cases
- [ x] I added/update the relevant documentation (either on github or on notion)
- [ x] Where necessary I refactored code to improve the overall quality

[MWDB] Selfsigned certificate support + various bug fixes

---

internal-enrichment/virustotal/docker-compose.yml
internal-enrichment/virustotal/src/config.yml.sample
internal-enrichment/virustotal/src/virustotal/virustotal.py

* Make ASN and location resolution for IPs optional
* Make IP resolution for domains optional

[VirusTotal] Made IP and Domain relationships optional

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-txt/src/export-file-txt.py

https://github.com/OpenCTI-Platform/opencti/pull/2813

List exports bug fixes for contained data (#2804)

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-stix/src/export-file-stix.py

Add the possibility to export selected StixSightingRelationships only
https://github.com/OpenCTI-Platform/opencti/issues/2735
https://github.com/OpenCTI-Platform/opencti/pull/2819

[connectors] selected StixSightingRelationships export (#2735)

---

stream/elastic/elastic/import_manager.py
stream/elastic/elastic/stix2ecs.py

* Added URL STIX2.1 pattern parsing capabilities to connector-elastic
* added a warning if more than one pattern is encountered in indicators. 
* not implemented patterns now log as error, not only warning
*

Connector-Elastic -- implemented URL-stix2-parsing and checks

---

internal-enrichment/crowdsec/src/crowdsec.py

Set user agent of crowdsec connector to `crowdsec-opencti/v1.0.0` while making calls to CrowdSec API

Set user agent for crowdsec connector to crowdsec-opencti/v1.0.0

---

external-import/socprime/src/socprime/core.py

* fix Socprime connector crashing when it tries to send empty stix2 bundle

Socprime connector fix

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-txt/src/export-file-txt.py

…cident to fit new Format (#issue/1075) (#1076)
* Remove Case in export files
* Add Feedback and Case Incident in export files
* https://github.com/OpenCTI-Platform/opencti/issues/2977

[connectors] remove Case in export files and Add feedback and Case Incident

---

external-import/taxii2/src/taxii2.py

So what I've done is added pagination to the poll function.
I also added a line in there to add pattern_type for stix 2.0 feeds.
I'm using the manifest to determine the date_after when getting objects.
Finally, I'm reconstructing the bundle so I didn't have to modify any other code.
https://github.com/OpenCTI-Platform/connectors/issues/1024
If doing an initial download, because it is going to be a big bundle, I'm not sure if that is going to cause issues. It was working fine for me with 4.5K indicators.

[taxii2] Added pagination to taxii connector

---

external-import/mandiant/src/mandiant.py

I know there is a lot of work going on with the Mandiant connector at the moment. But I was hoping a smaller PR with just the mscore might make it though quicker while we wait for other PR that involves a rewrite of the whole connector. Having the ability to use the mscore to only pull malicious indicators is a feature that has been missing from the Mandiant Connector for a long time.
https://github.com/OpenCTI-Platform/connectors/issues/736

[mandiant] Added mscore to mandiant connector

---

internal-enrichment/ivre/src/ivre_connector.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
internal-enrichment/shodan/src/shodanImport.py

* [Issue 1086](https://github.com/OpenCTI-Platform/connectors/issues/1086)
✅ Test OK with OpenCTI branch
⚠️ Waiting merge of [PR 3063](https://github.com/OpenCTI-Platform/opencti/pull/3063)

[ivre/shodan] Migrate Stix Cyber Observable Relationship to Stix Ref Relationship

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-txt/src/export-file-txt.py

* Add CaseRFI and CaseRFT to export files
* https://github.com/OpenCTI-Platform/opencti/issues/2977

[connectors] Add CaseRfi and CaseRft to export files (#issue/1079)

---

internal-enrichment/virustotal-downloader/docker-compose.yml

[Virustotal Downloader] Increase Default Confidence Level to 100, resolves #1095

---

internal-enrichment/yara/.dockerignore
internal-enrichment/yara/Dockerfile
internal-enrichment/yara/README.md
internal-enrichment/yara/docker-compose.yml
internal-enrichment/yara/src/config.yml.sample
internal-enrichment/yara/src/main.py
internal-enrichment/yara/src/requirements.txt

* Add a new internal enrichment connector that scans Artifact Observables with YARA Indicators
* Uses `yara-python`
* https://github.com/OpenCTI-Platform/connectors/issues/756
N/A

Introduce the YARA connector

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-txt/src/export-file-txt.py

*
*
* https://github.com/OpenCTI-Platform/opencti/issues/3328
*

export Data-source & Data-component (#issue/3328)

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-txt/src/export-file-txt.py

* Implementing Tasks in Exports 
* https://github.com/OpenCTI-Platform/opencti/issues/2846

Implementing Tasks (#issue/1107)

---

external-import/lastinfosec/docker-compose.yml

Our docker-compose had an error so we were not able to pull the image

fix docker-compose

---

stream/qradar/.dockerignore
stream/qradar/.gitignore
stream/qradar/Dockerfile
stream/qradar/README.md
stream/qradar/docker-compose.yml
stream/qradar/entrypoint.sh
stream/qradar/src/qradar.py
stream/qradar/src/requirements.txt

The connector was tested on a test environment and is now in production, feeds were pushed to multiple reference sets based on the Indicator type for performance reasons.

Qradar Stream Connector

---

internal-enrichment/sophoslabs-intelix/README.md
internal-enrichment/sophoslabs-intelix/docker-compose.yml
internal-enrichment/sophoslabs-intelix/src/config.yml.sample
internal-enrichment/sophoslabs-intelix/src/intelix.py
internal-enrichment/sophoslabs-intelix/src/main.py
internal-enrichment/sophoslabs-intelix/src/requirements.txt

Added error handling if authentication is not successful or if there's a bad response from the Intelix service. Added additional support for StixFile
N/A
- [X ] I consider the submitted work as finished
- [X ] I tested the code for its functionality using different use cases
- [ X] I added/update the relevant documentation (either on github or on notion)
- [ X] Where necessary I refactored code to improve the overall quality
N/A

Updated Intelix connector for additional connector types, added error handling

---

internal-enrichment/hybrid-analysis-sandbox/src/hybrid-analysis-sandbox.py

Change the connector to generate a Malware Analysis and attach the observables generated from the analysis the Malware Analysis.
Brainstorm: https://www.notion.so/filigran/Hybrid-Analysis-Connector-f401ce4c9c164fdc8d20ac7df704d554?pvs=4
*
*
*
*
Tested on :

[hybrid-analysis-sandbox] add Malware Analysis (#3478)

---

internal-enrichment/hybrid-analysis-sandbox/src/config.yml.sample
internal-export-file/export-file-txt/src/export-file-txt.py

* Fix the txt export for Malware Analyses
* Taking Artifact out of the scope of the connector Hybrid Analysis
* https://github.com/OpenCTI-Platform/connectors/issues/1212
*
Sorry for the issue number that doesn't match the branch name

[connectors] fix export malware analyses as a txt (#1212)

---

external-import/urlhaus-recent-payloads/docker-compose.yml

* typo in `CONNECTOR_NAME`, correct name is `URLhaus`, ref. https://urlhaus.abuse.ch/
* make `CONNECTOR_ID` align better with other connectors: `ChangeMe`
* #1221
*

Update docker-compose.yml for urlhaus-recent-payloads

---

external-import/ironnet/README.md
external-import/ironnet/docker-compose.yml
external-import/ironnet/src/ironnet/connector.py

* Refactor stix object creation, mainly to dedupe object creation for faster runs. 
* Add malware objects and relationships to observables and (if enabled) indicators
* Added a blurb in the README about how the URL can be configured for additional filtering.
* Renamed the connector name in the compose file (I originally copied it from Mandiant)
* n/a

[ironnet] Update connector

---

external-import/ironnet/src/ironnet/connector.py

* Added descriptions to the observable/indicator and malware relationships to include the ports used by each threat when it was discovered. 
Example:
Indicator associated with:
- `Cobalt Strike` on port(s) `9999`
- `Viper` on port(s) `60000,60001`
* n/a
*

[ironnet] Add ports used to observable descriptions

---

internal-enrichment/virustotal/src/virustotal/client.py

* Updated the `Retry()` method call to use `allowed_methods` over the now deprecated `method_whitelist`.
* #1271 
- [ x ] I consider the submitted work as finished
- [ x ] I tested the code for its functionality using different use cases
- [ N/A ] I added/update the relevant documentation (either on github or on notion)
- [ N/A ] Where necessary I refactored code to improve the overall quality
* Likely related to [this](https://github.com/phac-nml/irida-uploader/pull/153) Urllib3 change.

VirusTotal: Fixed unexpected keyword argument 'method_whitelist' error

---

external-import/feedly/.dockerignore
external-import/feedly/Dockerfile
external-import/feedly/README.md
external-import/feedly/docker-compose.yml
external-import/feedly/entrypoint.sh
external-import/feedly/src/config.yml.sample
external-import/feedly/src/feedly/opencti_connector/connector.py
external-import/feedly/src/feedly/opencti_connector/runner.py
external-import/feedly/src/main.py
external-import/feedly/src/requirements.txt

* Add a Feedly connector to OpenCTI eco-system

[feedly-connector] Add a Feedly connector

---

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py

* Send bundles incrementally instead of all at the end.
* Seach existing incident by id instead of name.
* Check for field last_analysis_stats.
* N/A

[vt-livehunt] send bundles incrementally

---

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py

* Only create the work id if they are bundles to send to avoid seeing empty work process in the connector page.
* N/A

[vt-livehunt] initiate work only if bundles to send

---

internal-export-file/export-file-stix/src/export-file-stix.py

* https://github.com/OpenCTI-Platform/connectors/issues/1337

[export-file-stix] Fix export selected entities

---

stream/logrhythm/.dockerignore
stream/logrhythm/.gitignore
stream/logrhythm/Dockerfile
stream/logrhythm/README.md
stream/logrhythm/docker-compose.yml
stream/logrhythm/entrypoint.sh
stream/logrhythm/src/config.yml.sample
stream/logrhythm/src/logrhythm.py
stream/logrhythm/src/requirements.txt

[Logrhythm] stream connector for LR SIEM

---

internal-export-file/export-file-stix/src/export-file-stix.py

**Related PR in client-python :** https://github.com/OpenCTI-Platform/client-python/pull/448
* Fix export list (https://github.com/OpenCTI-Platform/connectors/issues/1387)
* Fix export relationships (https://github.com/OpenCTI-Platform/opencti/issues/4253)
* https://github.com/OpenCTI-Platform/connectors/issues/1387

[export-file-stix] fix export list (#1387)

---

external-import/taxii2/README.md
external-import/taxii2/docker-compose.yml
external-import/taxii2/src/config.yml.sample
external-import/taxii2/src/taxii2.py
internal-export-file/export-report-pdf/src/export-report-pdf.py
internal-export-file/export-report-pdf/src/resources/report.html

* Adding Content section to PDF report for opencti reports
* Handling "stix object does not exists on server" error; continuing processing the objects
* Adding the possibility for token authentication to taxii server
*
*

Content Section for PDF Export Connector & Authorization Token for Taxii connector

---

external-import/riskiq/docker-compose.yml
external-import/riskiq/src/config.yml.sample
external-import/riskiq/src/riskiq/article_importer.py
external-import/riskiq/src/riskiq/client.py
external-import/riskiq/src/riskiq/riskiq.py

* Add metrics for the riskiq connector
* N/A

[riskiq] add metrics

---

external-import/misp/docker-compose.yml
external-import/misp/src/config.yml.sample
external-import/misp/src/misp.py

* Add metrics for the misp connector
* N/A

[misp] add metrics

---

external-import/malpedia/docker-compose.yml
external-import/malpedia/src/config.yml.sample
external-import/malpedia/src/malpedia/client.py
external-import/malpedia/src/malpedia/core.py
external-import/malpedia/src/malpedia/knowledge.py
external-import/malpedia/src/malpedia/models.py

* Add metrics for the malpedia connector
* N/A

[malpedia] add metrics

---

external-import/cve/src/cve.py
external-import/cve/src/cvetostix2.py

* Add metrics for cve connector
* N/A

[cve] add metrics

---

external-import/kaspersky/docker-compose.yml
external-import/kaspersky/src/config.yml.sample
external-import/kaspersky/src/kaspersky/client.py
external-import/kaspersky/src/kaspersky/connector.py
external-import/kaspersky/src/kaspersky/importer.py
external-import/kaspersky/src/kaspersky/master_ioc/builder.py
external-import/kaspersky/src/kaspersky/master_ioc/importer.py
external-import/kaspersky/src/kaspersky/master_yara/builder.py
external-import/kaspersky/src/kaspersky/master_yara/importer.py
external-import/kaspersky/src/kaspersky/publication/builder.py
external-import/kaspersky/src/kaspersky/publication/importer.py
external-import/kaspersky/src/kaspersky/utils/common.py
external-import/kaspersky/src/kaspersky/utils/indicators.py
external-import/kaspersky/src/kaspersky/utils/observables.py
external-import/kaspersky/src/kaspersky/utils/openioc.py
external-import/kaspersky/src/kaspersky/utils/stix2.py
external-import/kaspersky/src/kaspersky/utils/yara.py

* Add metrics for the kaspersky connector
* N/A

[kaspersky] add metrics

---

internal-enrichment/domaintools/src/connector/builder.py
internal-enrichment/domaintools/src/connector/core.py

* Add metrics for the domaintools enrichment connector
* N/A

[domaintools] add metrics

---

external-import/orange-cyberdefense/Dockerfile
external-import/orange-cyberdefense/docker-compose.yml
external-import/orange-cyberdefense/src/config.yml.sample
external-import/orange-cyberdefense/src/orange-cyberdefense.py

Code Enhancements & Refactor Summary
General Adjustments:
Configuration Loading:
I've added a bit of logging when loading the configuration. This should help us track any changes or issues with configurations more easily.
Split the configuration loading into its own function. This way, it's more organized.
Update Timing:
Changed the update interval from 60 seconds to 600 seconds for smoother operations.
Date Handling:
Added a parseDate function to make date parsing a consistent process across the code.
Run Method Tweaks:
Simplified Logic:
Broke down some of the complex parts into smaller functions. This should make it easier for us to understand and troubleshoot, if need be.
Unified State Updates:
Started using the _check_and_update_state method to manage updates from various data …

refacto: OCD connector refactor

---

.circleci/config.yml

[rf-feeds] Fix CI/CD

---

external-import/thehive/src/thehive.py

* Fix error where the alert and case state are updated to the last processed object. The last object is not always the latest case or alert. Added a function to check and return the latest value to track the state appropriately. This will prevent all cases from being imported every time the connector is run.

[thehive] - Fix Connector state for alerts, and cases.

---

external-import/threatfox/README.md
external-import/threatfox/docker-compose.yml
external-import/threatfox/src/config.yml.sample
external-import/threatfox/src/main.py

- Threatfox filtering improvement
- Bug correction
- Fix of the issue [#1456](https://github.com/OpenCTI-Platform/connectors/issues/1456)
- Add external reference import
- Addition/Completion of the "x_opencti_main_observable_type" fields

Threatfox improvement

---

external-import/threatfox/README.md
external-import/tweetfeed/src/tweetfeed.py

Correct the type of the "days_back_in_time" variable so that it is an integer (instead of a string)

Tweetfeed fix

---

templates/external-import/README.md
templates/internal-enrichment/README.md

* Fix README.md in templates directory.

Fix README.md in templates directory.

---

external-import/thehive/src/thehive.py

* Handle error for AttributeErrors with Case / Alerts
```
{"timestamp": "2023-11-06T20:18:00.216428Z", "level": "ERROR", "name": "pycti.connector", "message": "Error occurred: 'WindowsRegistryValueType' object has no attribute 'id'"}	
Traceback (most recent call last):	
File "/opt/opencti-connector-thehive/thehive.py", line 537, in run	
self.process_logic("case", "last_case_date", self.generate_case_bundle)	
File "/opt/opencti-connector-thehive/thehive.py", line 374, in process_logic	
updated_last_date = self.process_items(	
^^^^^^^^^^^^^^^^^^^	
File "/opt/opencti-connector-thehive/thehive.py", line 342, in process_items	
stix_bundle = process_func(item)	
^^^^^^^^^^^^^^^^^^	
File "/opt/opencti-connector-thehive/thehive.py", line 248, in generate_case_bundle	
processed_observables, …
```

[thehive] - Include error handling for case/alert AttributeErrors.

---

external-import/misp/src/misp.py

Fix keep as is comparison for custom labels.

[misp] Fix keep as-is configuration option for labels

---

stream/qradar/src/qradar.py

Fix update & delete event (self.qradar_reference_name is already in collection_url)

[QRADAR] Fix uri for delete & update

---

internal-enrichment/domaintools/README.md
internal-enrichment/domaintools/docker-compose.yml
internal-enrichment/domaintools/src/config.yml.sample
internal-enrichment/domaintools/src/connector/core.py

* Add a `MAX_TLP` option to avoid enrichment of sensitive information
* N/A

[domaintools] add MAX_TLP option for enrichment

---

external-import/recordedfuture-notes/README.md
external-import/recordedfuture-notes/docker-compose.yml
external-import/recordedfuture-notes/src/config.yml.sample
external-import/recordedfuture-notes/src/rf_notes.py
external-import/recordedfuture-notes/src/rflib/rf_client.py
external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py

* Handle multiple topics
* Add a parameter "risk_as_score" to use risk score (RF) as score for indicators (Hash, IP, domain)
* Add a parameter "risk_threshold" under which related indicators are not taken into account
* Mapping more related entities 
* Product -> Software, 
* Mitre Attack Pattern -> Attack pattern, 
* City, Country, ProvinceOrState -> City, Country, Administrative-Area
* Industry -> Sector
* Operation -> Campaign
* Mapping Sigma rules
* Add relationships between entities contained in a report
* https://github.com/OpenCTI-Platform/connectors/issues/1418

Improving Recorded Future Connector (#issue/1418)

---

external-import/threatfox/src/main.py

* Improvement of the code to unzip the file
* Improvement of indicator type names

[connector] fix compressed file fetching - Threatfox

---

external-import/cve/src/cve.py
external-import/valhalla/src/valhalla/core.py
external-import/valhalla/src/valhalla/knowledge.py
external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py
internal-enrichment/domaintools/src/connector/core.py

* Refinement of metrics for the following connectors:
- cve
- domaintools
- valhalla
- virustotal-livehunt-notifications
* N/A

[metrics] refinement of some connectors metrics

---

internal-enrichment/hostio/README.md

[hostio] - Fix readme hostio

---

external-import/thehive/src/thehive.py
internal-enrichment/hostio/docker-compose.yml
internal-enrichment/hostio/src/hostio/hostio_utils.py
internal-enrichment/hostio/src/hostio/tests/test_ipinfo.py
internal-enrichment/hostio/src/hostio/transform_to_stix.py
internal-enrichment/hostio/src/main.py

* Added enhancement to get ASN from free license.
* Labels were incorrectly applied, updated to use `pycti` correctly.

[hostio] - Fix labels, add AS for free license.

---

external-import/recordedfuture-notes/src/rf_notes.py

* Specify that the variable risk_threshold is a number

[Recorded Future] Force parameter as number for risk threshold

---

stream/harfanglab/docker-compose.yml

* Fix environment variables name
*
* #1598
*

[HarfangLab] Fix environment variables for Docker Compose

---

external-import/mandiant/README.md
external-import/mandiant/src/connector/actors.py
external-import/mandiant/src/connector/base.py
external-import/mandiant/src/connector/campaigns.py
external-import/mandiant/src/connector/common.py
external-import/mandiant/src/connector/reports.py
external-import/mandiant/src/connector/utils.py

Multiple improvements on Mandiant connector.
Most important, `last_run` parameter is now present to control the number of times each collection (`actors`, `indicators`, `vulnerabilities`, etc.) is collected.

Mandiant connector improvement

---

external-import/crowdstrike/src/crowdstrike/report/importer.py

crowdstrike: Remove printing of bundle on stdout

---

external-import/mandiant/src/connector/api.py
external-import/mandiant/src/connector/campaigns.py

* Add report indicators endpoint
* Add proper campaign attack patterns

Mandiant improvements

---

stream/harfanglab/src/config.yml.sample
stream/harfanglab/src/sightings.py

* Add handle state
* Add filtering data by date
* Update default "confidence_lvl" in config
* Add log Create Yara / Sigma
* Fix error import Hash unique
* https://github.com/OpenCTI-Platform/connectors/issues/1454

[Connector] Fix Connector HarfangLab

---

external-import/socprime/docker-compose.yml
external-import/socprime/src/config.yml.sample
external-import/socprime/src/socprime/core.py
external-import/socprime/src/socprime/mitre_attack.py

* Threat Actor entity type is changed by Intrusion Set in SOC Prime connector
* Added Vulnerability entities in SOC Prime connector

socprime connector update

---

external-import/orange-cyberdefense/docker-compose.yml
external-import/orange-cyberdefense/src/config.yml.sample
external-import/orange-cyberdefense/src/orange-cyberdefense.py

feat: update vuln

---

external-import/mandiant/README.md
external-import/mandiant/src/connector/actors.py
external-import/mandiant/src/connector/api.py
external-import/mandiant/src/connector/base.py
external-import/mandiant/src/connector/campaigns.py
external-import/mandiant/src/connector/common.py
external-import/mandiant/src/connector/utils.py

[mandiant] Improve pagination and prevent failure loop (#1644)

---

internal-enrichment/recordedfuture-enrichment/README.md
internal-enrichment/recordedfuture-enrichment/src/requirements.txt
internal-enrichment/recordedfuture-enrichment/src/rf_enrichment.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_client.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_utils.py

* Add more robust error handling when an IOC does not exist in RF.
* Link TTPs to existing opencti AttackPattern(s), requires Mitre IDs to be imported vs creating new TTPs
* Add support to iterate through multiple Arrays of Links
* Gracefully handle Max TLP 
* Add IPv6 Support
* Add Friendly Name for Enrichment Job
* RF API returns a 404 when an IOC does not exist, added logic to handle this gracefully. 
* RF Max TLP would raise an error, added logic to handle this gracefully
* Connector when set to auto enrich would fail open clogging MQ. We had 1.2 Million Items in our MQ due to the above failures.

[recordedfuture-enrichment] - Connector enhancements and bug resolution

---

external-import/cve/src/connector/cveConnector.py
external-import/cve/src/services/converter/vulnerabilityToStix2.py

[cve] Expose metrics activation prevent connector to start (#1646)

---

external-import/mandiant/src/connector/__main__.py
external-import/mandiant/src/connector/actors.py
external-import/mandiant/src/connector/api.py
external-import/mandiant/src/connector/base.py
external-import/mandiant/src/connector/campaigns.py
external-import/mandiant/src/connector/common.py
external-import/mandiant/src/connector/indicators.py
external-import/mandiant/src/connector/malwares.py
external-import/mandiant/src/connector/reports.py
external-import/mandiant/src/connector/utils.py
external-import/mandiant/src/connector/vulnerabilities.py

[mandiant] Global rework of the connector (#1644)

---

internal-enrichment/attribution-tools/src/dataexport.py

See https://github.com/OpenCTI-Platform/client-python/pull/518

[attribution-tool] Change logging function to comply to new API

---

external-import/cve/README.md
external-import/cve/docker-compose.yml
external-import/cve/src/config.yml.sample
external-import/cve/src/services/client/api.py
external-import/cve/src/services/client/vulnerability.py

* Sleep script between each request and not only for pagination
* Increase `backoff_factor` when retry fail
* Complete `docker-compose.yml` and `config.sample.yml` files with additionnal information
* https://github.com/OpenCTI-Platform/connectors/issues/1661

[CVE] Fix  connector makes unnecessary paginated request and failing to limit API Rate limit when exception thrown

---

external-import/recordedfuture-notes/README.md
external-import/recordedfuture-notes/docker-compose.yml
external-import/recordedfuture-notes/src/config.yml.sample
external-import/recordedfuture-notes/src/requirements.txt
external-import/recordedfuture-notes/src/rf_notes.py
external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py
external-import/recordedfuture-notes/src/rflib/risk_list.py

* Remove context's IPs from Risk Lists
* Add context on risk lists, create relationships with attack pattern
* Add check and handle for IPv4 and IPv6
* Add default marking for all objects imported
* Add improvement to indicator filtering
* https://github.com/OpenCTI-Platform/connectors/issues/1478

[Recorded Future] Part 1 : Improve import of risk lists

---

external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py
external-import/recordedfuture-notes/src/rflib/risk_list.py

* Add risk rules related to criticality score in indicator description
* https://github.com/OpenCTI-Platform/connectors/issues/1478

[Recorded Future] Complete risk lists with risk rules in description

---

internal-export-file/export-report-pdf/README.md
internal-export-file/export-report-pdf/src/resources/case.html

* Fix Export PDF of Cases containing tasks.
*  [#5467](https://github.com/OpenCTI-Platform/connectors/issues/1693)

[connectors] Fix export of a case with tasks to PDF (#5467)

---

external-import/thehive/src/thehive.py

* Fix condition when case or alert already fetched
* https://github.com/OpenCTI-Platform/connectors/issues/1696

[The Hive] Fix connector when case and alert already fetched

---

external-import/mandiant/src/connector/base.py

…formation
* The job (work) has been moved in the process to avoid having jobs with zero import (open for discussion)
* Fixed collection call interval 
* Update logs with more informations (remaining time, no data)
* #1685
*
Current behavior :
New :
Logs :

[connector] Fixed collection call interval and updated log 

---

stream/crowdstrike/.dockerignore
stream/crowdstrike/Dockerfile
stream/crowdstrike/README.md
stream/crowdstrike/docker-compose.yml
stream/crowdstrike/entrypoint.sh
stream/crowdstrike/src/config.yml.sample
stream/crowdstrike/src/crowdstrike.py
stream/crowdstrike/src/requirements.txt

* A Crowdstrike connector allowing users to push indicators from OpenCTI to Crowdstrike endpoint security solution

Add a Crowdstrike connector

---

internal-enrichment/shodan/src/shodanImport.py

* Modify enrichment connectors "Shodan" is “Playbook compatible”
*
* #1585
*
* Todo: Improvement of the structure

[connector] Update Shodan for “Playbook compatible”

---

external-import/recordedfuture-notes/docker-compose.yml
external-import/recordedfuture-notes/src/config.yml.sample
external-import/recordedfuture-notes/src/rf_notes.py
external-import/recordedfuture-notes/src/rflib/__init__.py
external-import/recordedfuture-notes/src/rflib/constants.py
external-import/recordedfuture-notes/src/rflib/rf_client.py
external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py
external-import/recordedfuture-notes/src/rflib/risk_list.py
external-import/recordedfuture-notes/src/rflib/threat_map.py

* Import Threat Actors from RF Threat map as Intrusion Set
* Create relationships:
Expected output for Intrusion Set relationships:
*  Import Malware from RF Threat map
* Create relationships:
Expected output for Malware relationships:
And some additionnal relationships:
* Improve logs to see details of importations
* Some screenshots
* https://github.com/OpenCTI-Platform/connectors/issues/1478
- Tests have been made with only one Worker: for about 76 threat actors to import with their links, it can take few hours to import all entities
- Code needs to be refactored but review can be done without this

[Recorded Future] Import Malware and Threat Actors from Threat API

---

external-import/mandiant/src/connector/base.py

* Resetting the visibility of “work” to zero
* Fix for missing offsets in the UI when creating “works” for the “malware”, “actors”, “campaigns” collections
* #1685

[connector] Update work, and fix offset missing in some collections

---

external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py

* Correct mapping for organization: 
* if Organization or Person is a TA => add it as Intrusion Set
* if Organization or Person is not a TA => add it as identity
* Add correct names for attack pattern
From this display:
To this display:
*  https://github.com/OpenCTI-Platform/connectors/issues/1478

[Recorded Future] Fix correct mapping for organization and person + add correct names for attack pattern

---

external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py

* Fix import url, hash, domain

[Recorded Future] Fix import url, hash, domain

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-stix/src/export-file-stix.py
internal-export-file/export-file-txt/src/export-file-txt.py

[export] CSV and TEXT export fail with null filters 
See #1764

[export] CSV and TEXT export fail with null filters (#1764)

---

external-import/recordedfuture-notes/README.md
external-import/recordedfuture-notes/src/config.yml.sample
external-import/recordedfuture-notes/src/rf_notes.py
external-import/recordedfuture-notes/src/rflib/rf_notes_to_stix2.py
external-import/recordedfuture-notes/src/rflib/risk_list.py

* Add option of selecting which related entities are imported in config
* Update related README.md documentation
* Update docker-compose.yml configurations

[Recorded Future] Add option of selecting which related entities are imported

---

external-import/recordedfuture-notes/docker-compose.yml

* Add config in docker-compose

[Recorded Future] Add config in docker-compose

---

external-import/feedly/src/feedly/opencti_connector/connector.py

* Add main observable type to indicators
N/A

[feedly connector] Add main observable type to indicators

---

internal-enrichment/malbeacon/docker-compose.yml
internal-enrichment/malbeacon/src/config.yml.sample
internal-enrichment/malbeacon/src/malbeacon.py
internal-enrichment/malbeacon/src/requirements.txt

* Convert API calls into STIX objects to be ingested 
* Add config variable for score
* Complete config variables for docker-compose.yml file
* Add types and comments
* https://github.com/OpenCTI-Platform/connectors/issues/1585

[Malbeacon] Modify Malbeacon connector to be playbook compatible

---

external-import/ransomwarelive/.env.sample
external-import/ransomwarelive/Dockerfile
external-import/ransomwarelive/README.md
external-import/ransomwarelive/docker-compose.yml
external-import/ransomwarelive/entrypoint.sh
external-import/ransomwarelive/requirements.txt
external-import/ransomwarelive/src/lib/ransomConn.py
external-import/ransomwarelive/src/main.py

* Ransomware Live connector
*Tracking Ransomware events live from ransomwarelive api
* https://www.ransomware.live/#/about
Thanks to Julien Mousqueton for making api public

RansomwareLive Connector

---

internal-enrichment/malbeacon/docker-compose.yml
internal-enrichment/malbeacon/entrypoint.sh
internal-enrichment/malbeacon/src/main.py
internal-enrichment/malbeacon/src/malbeacon.py
internal-enrichment/malbeacon/src/malbeacon_client.py
internal-enrichment/malbeacon/src/malbeacon_config_variables.py
internal-enrichment/malbeacon/src/malbeacon_converter.py
internal-enrichment/malbeacon/src/malbeacon_endpoints.py
internal-enrichment/malbeacon/src/malbeacon_utils.py
internal-enrichment/malbeacon/src/models/c2_model.py
internal-enrichment/malbeacon/src/models/email_model.py

* File restructurations
* Handle data with bundle from enrichment

[Malbeacon] Improvement structure and playbook handling

---

internal-enrichment/greynoise/README.md
internal-enrichment/greynoise/docker-compose.yml
internal-enrichment/greynoise/src/config.yml.sample
internal-enrichment/greynoise/src/greynoise.py

* Modify Greynoise connector to be playbook compatible
* Add types and comments
* #1585 
*

[Greynoise] Modify Greynoise connector to be playbook compatible

---

external-import/recordedfuture-notes/src/rf_notes.py
external-import/recordedfuture-notes/src/rflib/risk_list.py
external-import/recordedfuture-notes/src/rflib/threat_map.py

* Fix interval to receive only integer for risk list and threat maps

[Recorded Future] Fix interval to receive only integer for risk lists and threat maps

---

external-import/feedly/src/feedly/opencti_connector/connector.py

[feedly] fix adding main observable type

---

stream/sentinel/src/sentinel.py

* Fix Sentinel stream connector is not processing file hashes => get properly created date
* https://github.com/OpenCTI-Platform/connectors/issues/1081

[Sentinel] Fix Sentinel stream connector is not processing file hashes

---

stream/splunk/README.md

README:
replaced splunk_login and splunk_password parameters by splunk_token.
added stream id parameter

update splunk connector README

---

internal-import-file/import-document/src/reportimporter/core.py

* Fix relationship creation (entity_id instead of entity)
* Remove duplicated code
* https://github.com/OpenCTI-Platform/opencti/issues/6121

[import-document] fix import document on Incident & Threat actor (opencti/6121)

---

internal-enrichment/import-external-reference/README.md
internal-enrichment/import-external-reference/src/config.yml.sample
internal-enrichment/import-external-reference/src/import-external-reference.py

* Update variable wkhtmltopdf_path in config.yml (Optional)
*
* #1812
* #1864

[Connector] Optional variable wkhtmltopdf_path

---

external-import/greynoisefeed/Dockerfile
external-import/greynoisefeed/README.md
external-import/greynoisefeed/docker-compose.yml
external-import/greynoisefeed/entrypoint.sh
external-import/greynoisefeed/src/config.yml.sample
external-import/greynoisefeed/src/main.py
external-import/greynoisefeed/src/requirements.txt

* Adds a new external-import connect to pull indicators from GreyNoise
* N/A

[greynoisefeed] Initial setup for new GreyNoise Feed connector

---

external-import/recorded-future/src/rflib/constants.py
external-import/recorded-future/src/rflib/rf_to_stix2.py
external-import/recorded-future/src/rflib/risk_list.py

* Fix Malware and Threat Actor relationship types with and Indicator when importing risk lists
* Update triggered risk rules display, add severity name and corresponding risk score
From a list display: 
To a table display:

[Recorded Future] Fix Malware and Threat Actor relationship types + update triggered risk rules display

---

external-import/sekoia/README.md
external-import/sekoia/docker-compose.yml

* Add relationship into connector scope configuration as it is required for having relationship
* Add and complete README documentation
* Remove confidence level from config.yml file as it is deprecated since 6.0

[Sekoia] Add relationship into connector scope + complete documentation

---

external-import/sekoia/src/config.yml.sample

* add campaign,infrastructure,relationship in Sekoia CONNECTOR_SCOPE
*
* https://github.com/OpenCTI-Platform/connectors/issues/1905
*

add campaign,infrastructure,relationship to config.yml.sample

---

internal-enrichment/shodan-internetdb/entrypoint.sh

* Fix module name 
* https://github.com/OpenCTI-Platform/connectors/issues/1932

[Shodan-InternetDB] Fix module name in entrypoint shodan-internetdb

---

internal-enrichment/dnstwist/Dockerfile
internal-enrichment/dnstwist/src/lib/DnsTwistConn.py

Bug Fixes and Changes to fields

Bug Fixes and Changes to Whois Record

---

internal-enrichment/anyrun-task/src/anyrun_task.py

* Correct endpoint URL
Related to the issue below:

[AnyRun Task] Fix endpoint anyrun-task enrichment connector

---

external-import/cpe/src/connector.py

* handle potential raised error on stadardize_tag
* https://github.com/OpenCTI-Platform/connectors/issues/1927

fix: handle potential error on standardize_tag. Fixes https://github.com/OpenCTI-Platform/connectors/issues/1927

---

internal-enrichment/anyrun-task/src/anyrun_task.py

* Fix default config AnyRun API endpoint

[AnyRun Task] Fix default config AnyRun API endpoint

---

internal-enrichment/crowdsec/Dockerfile
internal-enrichment/crowdsec/README.md
internal-enrichment/crowdsec/docker-compose.yml
internal-enrichment/crowdsec/src/crowdsec.py

…oc and default docker-compose.yml
* Fixed missing dependency in the install script of CrowdSec connector
* Better default values in example file and doc
* https://github.com/OpenCTI-Platform/connectors/issues/1946
More improvements will come on that connector. I'm just pushing the fix for the install for now

CrowdSec Enrichment Connector install dependencies fix

---

external-import/comlaude/src/comlaude/__init__.py
external-import/comlaude/src/main.py

* return timestamp as None when error
*
*
*

return timestamp as None when error

---

external-import/sekoia/src/sekoia.py

* Add print error on unknow exception (before that it was stopping with no error cause)
* Move work id in try block
* https://github.com/OpenCTI-Platform/connectors/issues/1958
* https://github.com/OpenCTI-Platform/client-python/pull/591

[Sekoia] Connector do not re-run and fail silently

---

external-import/ransomwarelive/Dockerfile
external-import/ransomwarelive/README.md
external-import/ransomwarelive/docker-compose.yml

- Remove env CONNECTOR_TYPE
- Add image in docker-compose.yml

[RANSOMWARELIVE] Doc enhancement

---

internal-enrichment/joe-sandbox/docker-compose.yml
internal-enrichment/joe-sandbox/src/config.yml.sample
internal-enrichment/joe-sandbox/src/joe-sandbox.py

* Remove `live-interaction` parameter from joe-sandbox connector which prevents the connector from starting.
This was removed from the joesandbox API two months ago: https://github.com/joesecurity/jbxapi/commit/3f8ba8d4f52e1c9647eee7df4ddc0eab3ea221dc
* Mentioned on Slack

[joe-sandbox] remove live-interaction parameter

---

.circleci/config.yml

CI: add malcore

---

templates/external-import/src/lib/external_import.py
templates/external-import/src/main.py

* Fix typos in the templates of the external-import connector
* Fix some pylint warnings
* Add metrics in the template
* N/A

[templates] fix typos and add metrics for external-import

---

internal-enrichment/anyrun-task/README.md
internal-enrichment/anyrun-task/src/anyrun_task.py
internal-enrichment/anyrun-task/src/config.yml.sample

Fixing some bugs in anyrun-task connector
* Fix API URL 
* add privacy and locale params
*
*

Anyrun-task fixes

---

internal-enrichment/anyrun-task/docker-compose.yml

* Updated the docker-compose to add the new parameters
*
*
*

update docker-compose anyrun_task

---

external-import/thehive/docker-compose.yml
external-import/thehive/src/hive_observable_transform.py
external-import/thehive/src/requirements.txt
external-import/thehive/src/thehive.py

* Apply modifications made by a customer
*
*
*

Update the Hive connector

---

external-import/malcore/src/malcore/core.py

* Fixes a header issue in the Malcore connector
* Privately discussed

fixes a header issue

---

external-import/cpe/src/config.yml.sample

* Replace `connector_run_every` by `interval` in the configuration example to match current implementation of the connector

[cpe] fix configuration file example with cpe.interval attribute

---

external-import/mandiant/src/connector/actors.py

* Fix open vocabularies for intrusion set
* Update secondary_motivations
* https://github.com/OpenCTI-Platform/opencti/issues/6660
*

[Connector] Fix open vocabularies for intrusion set

---

stream/qradar/docker-compose.yml

* Fix variable name in docker-compose
*
* #2033 
*

[Qradar] Fix docker-compose variable

---

external-import/thehive/README.md
external-import/thehive/docker-compose.yml
external-import/thehive/src/config.yml.sample
external-import/thehive/src/thehive.py

* Remove confidence level in connector as it is deprecated since >= 6.0
*
* #2035
*

[theHive] Fix remove all confidence levels

---

stream/qradar/docker-compose.yml

* Fix docker-compose structure
*
* #2033 
*

[Qradar] Fix docker-compose structure

---

internal-enrichment/greynoise/docker-compose.yml
internal-enrichment/greynoise/entrypoint.sh
internal-enrichment/greynoise/src/config.yml.sample
internal-enrichment/greynoise/src/main.py
internal-enrichment/greynoise/src/requirements.txt

* Updates enricher to use the GreyNoise python SDK
* Adds API key validation to prevent the connector from running if the API key isn't supported
* Users with invalid API keys were running the connector unsuccessfully
Replaces standard python request calls with the GreyNoise python SDK.

Update GreyNoise internal-enrichment - API key validation and SDK

---

internal-import-file/import-document/src/reportimporter/core.py
internal-import-file/import-document/src/reportimporter/report_parser.py

* fix download failure for working directory pemission.
* #2032 is question for prepareing testdata.
- I tested text data import, but another file-type is only static analysis (test data is not ready)

[import-document] Use tempfile for parsing document

---

external-import/comlaude/README.md
external-import/comlaude/docker-compose.yml
external-import/comlaude/src/config.yml.sample
external-import/comlaude/src/main.py

* Add relationship between DomainName and Indicators.
* Add support for Score
* Add description
* Update documentation

Add relationship for DomainName and Indicator, Add support for Score.

---

internal-export-file/export-report-pdf/src/resources/case.css.template
internal-export-file/export-report-pdf/src/resources/case.html

* Fix overflow of case response indicator pattern when exporting to PDF
* #2026
*

[export-pdf] Fix indicator for case

---

internal-enrichment/ivre/src/ivre_connector.py

Kept ivre connector compatible with linked-to ref removal
Linked to opencti [PR](https://github.com/OpenCTI-Platform/opencti/pull/6513)

[connector] Changed linked-to ref to related-to relation

---

internal-enrichment/abuseipdb/src/abuseipdb.py

* Fix of a specific case regarding the creation of a "Location" in STIX2
*
* #2079 
*

[abuseipdb] Fix error

---

internal-enrichment/intezer-sandbox/src/intezer_sandbox.py

https://github.com/OpenCTI-Platform/connectors/issues/2090

---

external-import/recorded-future/src/main.py
external-import/recorded-future/src/rflib/rf_client.py

fix: https://github.com/OpenCTI-Platform/connectors/issues/2076

[Recorded Future] connector stop while doing initial import/lookback

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-stix/src/export-file-stix.py
internal-export-file/export-file-txt/src/export-file-txt.py
internal-export-file/export-report-pdf/src/export-report-pdf.py

*
*
* https://github.com/OpenCTI-Platform/opencti/issues/5797
*
* https://github.com/OpenCTI-Platform/opencti/pull/6815
* https://github.com/OpenCTI-Platform/client-python/pull/627

[connectors] Marking definition filters to export files (#5797)

---

internal-export-file/export-file-stix/src/export-file-stix.py

[external-file-stix] Fix stix export (#opencti/issue/5797)

---

external-import/malpedia/src/main.py

* Fix Malpedia connector correct import name

[Malpedia] Fix Malpedia connector import

---

internal-enrichment/hygiene/src/hygiene.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py
internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-stix/src/export-file-stix.py
internal-export-file/export-report-pdf/src/export-report-pdf.py
internal-export-file/export-ttps-file-navigator/src/export-ttps-file-navigator.py
internal-import-file/import-document/src/reportimporter/core.py
internal-import-file/import-file-stix/src/import-file-stix.py
stream/tanium/src/tanium_api_handler.py
templates/internal-export/src/main.py

Error when importing text files or PDFs (#6942)

Error when importing text files or PDFs (#6942)

---

internal-import-file/import-document/src/reportimporter/core.py
internal-import-file/import-document/src/reportimporter/report_parser.py

Reverts OpenCTI-Platform/connectors#2059

Revert "[import-document] Use tempfile for parsing document"

---

stream/qradar/src/config.yml.sample
stream/qradar/src/qradar.py

* Add file config.yml.sample
* Getting the right type when the stream detects an observable
* Added management of information logs and error logs during creation
* #1437
*

[Qradar] Fix error related to type

---

internal-enrichment/virustotal/src/virustotal/builder.py
internal-export-file/export-file-csv/src/export-file-csv.py

[platform] Fix virus total + adapt from client change (#2146)

---

internal-export-file/export-file-csv/src/export-file-csv.py
internal-export-file/export-file-stix/src/export-file-stix.py

*
*
* https://github.com/OpenCTI-Platform/connectors/issues/2121
* https://github.com/OpenCTI-Platform/opencti/issues/6824

[connectors] Error when trying to export without order by (#2121)

---

stream/qradar/src/qradar.py

* Fix deprecated API request regarding reference_set 
* #2124

[Qradar] Fix deprecated API request regarding reference_data

---

external-import/recorded-future/src/rflib/rf_to_stix2.py

* Complete types of Notes from RF
* https://github.com/OpenCTI-Platform/connectors/issues/2142

[Recorded Future] Fix sources for RF report type

---

stream/sentinel/README.md

Update typo in README.md

---

stream/crowdstrike-endpoint-security/src/main.py

[Crowdstrike Endpoint Security] Fix import CES import

---

stream/qradar/README.md
stream/qradar/docker-compose.yml
stream/qradar/src/config.yml.sample
stream/qradar/src/qradar.py

* Adding an new environment variable "QRADAR_URL_REFERENCE"
* Update Readme, docker-compose, config.yml.sample
* #2188

[Qradar] Adding an new environment variable

---

internal-import-file/import-document/src/reportimporter/core.py

[import-document] added error log to track bug

---

internal-enrichment/malbeacon/src/main.py
internal-enrichment/malbeacon/src/malbeacon_converter.py

* Fix import environment variables in converter

[Malbeacon] Fix import environment variable in converter

---

external-import/zerofox/src/collectors/mappers/botnetToInfrastructure.py
external-import/zerofox/src/collectors/mappers/c2DomainsToInfrastructure.py
external-import/zerofox/src/collectors/mappers/exploitToTool.py
external-import/zerofox/src/collectors/mappers/malwareToMalware.py
external-import/zerofox/src/collectors/mappers/phishingToInfrastructure.py
external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py
external-import/zerofox/src/zerofox/domain/malware.py
external-import/zerofox/src/zerofox/domain/ransomware.py

* This includes several refactorings to improve the ZeroFox connector
* N/A

[zerofox] Update ZeroFox Connector

---

internal-import-file/import-document/src/reportimporter/config/entity_config.ini

Closes https://github.com/OpenCTI-Platform/opencti/issues/7012

[import-document] Fix alias mapping for Country

---

external-import/zerofox/src/main.py

* This improves the logic that checks when a given collector should run and fixes #2221 
* https://github.com/OpenCTI-Platform/connectors/issues/2221

[zerofox] Simplify connector start logic

---

.circleci/config.yml

Build rolling connector images with pycti@master

---

external-import/red-flag-domains/Dockerfile
external-import/red-flag-domains/README.md
external-import/red-flag-domains/docker-compose.yml
external-import/red-flag-domains/entrypoint.sh
external-import/red-flag-domains/src/config.yml.sample
external-import/red-flag-domains/src/redflag-domains.py
external-import/red-flag-domains/src/requirements.txt

* addition of a new connector, for the red flag domains source, widely used in France

[NEW] Add 'red flag domains' connector

---

internal-enrichment/reversinglabs-malware-presence/.dockerignore
internal-enrichment/reversinglabs-malware-presence/.gitignore
internal-enrichment/reversinglabs-malware-presence/Dockerfile
internal-enrichment/reversinglabs-malware-presence/README.md
internal-enrichment/reversinglabs-malware-presence/docker-compose.yml
internal-enrichment/reversinglabs-malware-presence/entrypoint.sh
internal-enrichment/reversinglabs-malware-presence/requirements.txt
internal-enrichment/reversinglabs-malware-presence/src/lib/internal_enrichment.py
internal-enrichment/reversinglabs-malware-presence/src/main.py

* Adding a new connector to the repository
* Connector enables malware presence capabilities both on files and network locations
*
*

[REVERSINGLABS] New connector

---

stream/harfanglab/README.md
stream/harfanglab/src/harfanglab.py

* Implementing a condition that excludes observables that have the same value as the indicator
* Improvement "Logger" ( Use "connector_logger")
* Improvement "Readme" (More details)
* #1975

[HarfangLab] Improvement logger and readme

---

external-import/red-flag-domains/src/config.yml.sample

* Add type of connector in config sample file

[RedFlag] Add type of connector in config sample file

---

stream/chronicle/src/chronicle.py

* Fix lint Chronicle connector
*
*

[Chronicle] Fix lint chronicle connector

---

external-import/mwdb/src/mwdb.py
external-import/mwdb/src/requirements.txt

Hi!
I'm from CERT.pl team and I'm one of the authors of [mwdb-core](https://github.com/CERT-Polska/mwdb-core) project behind mwdb.cert.pl service.
This PR fixes very annoying issue reported here: https://github.com/OpenCTI-Platform/connectors/issues/1555 that is observed from time to time when users try to use connector to ingest data from our MWDB service into OpenCTI platform. In case of any persistent error (HTTP 401/403/429), it goes into infinite loop flooding our service with lots of requests.
To improve the overall code quality, I modified connector to use official [mwdblib](https://github.com/CERT-Polska/mwdblib) library instead of raw HTTP client as mwdblib correctly handles various exceptions that may happen during interaction with our API.
* closes #1555

[MWDB] API connection based on mwdblib, fix issues

---

external-import/mandiant/src/connector/campaigns.py

* Add campaign first_seen date

[Mandiant] Add campaign first_seen date

---

external-import/mandiant/src/connector/__main__.py
external-import/mandiant/src/connector/reports.py

* Add the story link in external reference
On Mandiant
Expected output on OpenCTI
* Add a description
On Mandiant
Expected output on OpenCTI
* Add Analyst comment as Note 
On Mandiant
Expected output on OpenCTI
* https://github.com/OpenCTI-Platform/connectors/issues/2303

[Mandiant] Correctly import Mandiant report news analysis

---

external-import/infoblox/Dockerfile
external-import/infoblox/README.md
external-import/infoblox/docker-compose.yml
external-import/infoblox/entrypoint.sh
external-import/infoblox/src/config.yml.sample
external-import/infoblox/src/infoblox.py
external-import/infoblox/src/requirements.txt
external-import/threatfox/src/main.py

* https://github.com/OpenCTI-Platform/connectors/issues/2309

Adding the Infoblox connector

---

.circleci/config.yml

[infoblox] Add to CI/CD

---

external-import/mandiant/src/connector/reports.py

* Sometimes, relationships in a report is not created. The fix check if there are related entities in the list, add it into `definitions` and create stix relationship

[connector] Fix mandiant relationships

---

external-import/infoblox/src/infoblox.py

* https://github.com/OpenCTI-Platform/connectors/issues/2337

Fix KeyError on dict

---

external-import/flashpoint/docker-compose.yml
external-import/flashpoint/src/config.yml.sample
external-import/flashpoint/src/flashpoint.py
external-import/flashpoint/src/mispfeed.py
external-import/mandiant/src/connector/reports.py

[flashpoint] Create groupings instead of reports by default

---

external-import/flashpoint/src/mispfeed.py

[Flashpoint] Fix lint Flashpoint

---

internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py

* Add score in the correct field
Output
* https://github.com/OpenCTI-Platform/connectors/issues/2349

[Recorded Future Enrichment] Add score in the correct field

---

stream/splunk/src/splunk.py

* Add traceback to have more accurate logs
* https://github.com/OpenCTI-Platform/connectors/issues/2374

[Splunk] Add traceback to have more accurate logs

---

external-import/ironnet/src/ironnet/__main__.py

* Add traceback to show more accurate logs
* Fix import
* https://github.com/OpenCTI-Platform/connectors/issues/2383

[Ironnet] Fix error on running connector

---

.circleci/config.yml

* Fix CircleCI configuration file for more consistency
*

[Webhook] Fix circle ci configuration file for more consistency

---

stream/webhook/Dockerfile
stream/webhook/docker-compose.yml
stream/webhook/src/requirements.txt

* Update version to fix CI build

[Webhook] Update version to fix CI build

---

internal-enrichment/cape-sandbox/src/cape-sandbox.py

update the signature of the "stix_cyber_observable.update_field" method to be compatible with latest version of pycti.
https://github.com/OpenCTI-Platform/connectors/issues/2357

[cape-sandbox]: Fix, error updating some "File" observable properties

---

external-import/red-flag-domains/docker-compose.yml

* Update red-flag-domains docker-compose file, change image name to correct one.
*
* 
*

[red-flag-domains] Update red-flag-domains docker-compose.yml

---

templates/external-import/src/lib/external_import.py

* Updated the validation and error handling of the retrieval of the`CONNECTOR_RUN_EVERY` environment variable.
* Updated the validation and error handling of the retrieval of the`CONNECTOR_UPDATE_EXISTING_DATA` environment variable.
* Fixed the bug in `elif isinstance(update_existing_data, bool) and update_existing_data.lower in`
* None.

Updated exception handling & code quality in external-import template

---

external-import/misp/src/misp.py

!--
Thank you very much for your pull request to the OpenCTI project! We as a community driven project depend on support and contributions like this!
Thus already a BIG THANK YOU upfront to you for choosing to help with your PR.
-->
* Fix indentation
* Add traceback for logs outside connector main process
* https://github.com/OpenCTI-Platform/connectors/issues/2389

[Misp] Fix indent + add traceback for logs outside connector main process

---

external-import/comlaude/README.md
external-import/comlaude/src/comlaude/__init__.py
external-import/comlaude/src/config.yml.sample
external-import/comlaude/src/main.py
external-import/comlaude/src/requirements.txt

Pull request by customer
* Tests conducted and normally the loop no longer exists.
* Regarding the relationships between indicators and observables, the indicators are now correctly linked to the observables.
* Put "Comlaude" as author.
* Added TLP Amber as "marking".
* Deleted useless label.
* The connector no longer re-imports the observables and indicators after it has finished importing the observables and indicators.
*
*

fixes Comlaude

---

internal-enrichment/google-dns/src/main.py

* Make the connector 'playbook compatible'
*
* #2397 
*

[Google DNS] Make the connector 'playbook compatible'

---

external-import/misp-feed/src/misp-feed.py
external-import/misp/src/misp.py

[MISP] search for threats in aliases when guess_threats_from_tags is ON

---

internal-enrichment/shodan-internetdb/README.md
internal-enrichment/shodan-internetdb/docker-compose.yml
internal-enrichment/shodan-internetdb/src/config.yml.sample
internal-enrichment/shodan-internetdb/src/requirements.txt
internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py

Updates to be playbook compatible
https://github.com/OpenCTI-Platform/connectors/issues/2419

[Shodan InternetDB] Playbook compatibility 

---

external-import/mandiant/src/connector/campaigns.py
external-import/mandiant/src/connector/common.py

* Add Mandiant TTP names in `Labels` of an Attack Pattern to the corresponding MITRE TTP
Mandiant name and Mitre name
Label in OpenCTI
* Add relationship when an Instrusion Set -> uses -> Attack Pattern when available on Mandiant
* Add `start_time` and `stop_time` for an Attack Pattern (when it is used the first time and when it is used the last time)
* Add `start_time` and `stop_time` for an Intrusion Set  (when we have seen this Intrusion Set the fisrt time during a Campaign and when we have seen it the last time during the Campaign)
* Add description with Mandiant Analyst comments if it exists
* https://github.com/OpenCTI-Platform/connectors/issues/2420

[Mandiant] Improvement of campaign imports

---

external-import/mandiant/src/connector/campaigns.py

* Fix argument method extract mandiant name

[Mandiant] Fix argument method extract mandiant name

---

external-import/comlaude/src/main.py

change Identity import and use of utcnow()

[Comlaude] change Identity import and utcnow

---

internal-enrichment/hygiene/src/hygiene.py

* Add the missing list: https://github.com/MISP/misp-warninglists/blob/ccdebabf6bc6f0f06767b17ae3bd5d5244e60e66/lists/findip-host/list.json
* Added protection/verification in prevention for other similar problems
* https://github.com/OpenCTI-Platform/connectors/issues/2435

[Hygiene] Hygiene enrichment connector error

---

external-import/sekoia/src/config.yml.sample
external-import/sekoia/src/sekoia.py

* Adding "Related Threats" with the indicator
* 
* #2392 
*

[Sekoia] Adding related threat

---

external-import/fortinet-ti/README.md

* Improve README Fortinet connector

Update README Fortinet

---

external-import/comlaude/src/main.py

[Comlaude] Tiny fix for labels

---

internal-enrichment/virustotal/src/virustotal/builder.py

Checks the presence of concerned fields
* https://github.com/OpenCTI-Platform/connectors/issues/2433

[VirusTotal] - Exception during IP address enrichment when VT does not return the expected information

---

external-import/ransomwarelive/docker-compose.yml
external-import/ransomwarelive/src/lib/ransomConn.py

* Changes to Report
* Author was added to reports
* Sector was added but accuracy is not 100%
* Domains and IPs are added
*
*

Updated Ransomware

---

external-import/ransomwarelive/requirements.txt

Updated requirements.txt for ransomwarelive
* Requirements were updated
*
* Requirements were  not updated in previous pull request
*

Update requirements.txt for ransomwarelive

---

external-import/zerofox/src/collectors/mappers/botnetToInfrastructure.py
external-import/zerofox/src/collectors/mappers/c2DomainsToInfrastructure.py
external-import/zerofox/src/collectors/mappers/exploitToTool.py
external-import/zerofox/src/collectors/mappers/malwareToMalware.py
external-import/zerofox/src/collectors/mappers/phishingToInfrastructure.py
external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py
external-import/zerofox/src/collectors/mappers/vulnerabilityToVulnerability.py

* Add pydocs to intelligence collectors
* Create Observable to C2 domains collector based on sample software
* remove family labels in ransomware collector to avoid redundancy

[ZeroFox] Document collectors and add software observable to C2Domains collector

---

external-import/mandiant/src/connector/base.py
external-import/mandiant/src/connector/reports.py
internal-enrichment/virustotal/docker-compose.yml
internal-enrichment/virustotal/src/config.yml.sample
internal-enrichment/virustotal/src/virustotal/builder.py
internal-enrichment/virustotal/src/virustotal/virustotal.py

[virustotal] Enhance all notes

---

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py

* Fix issue on debug logger calling json_dump
* https://github.com/OpenCTI-Platform/connectors/issues/1832

[VirusTotal Livehunt Notification] Fix issue on json dump

---

.circleci/config.yml

* Add connector to Circle CI
* #2515

[Safebrowsing] Add connector to Circle CI

---

internal-export-file/export-file-csv/src/export-file-csv.py

* float added on export list function
* https://github.com/OpenCTI-Platform/opencti/issues/7951

[connector] Float values are not exported on csv (#7951)

---

external-import/riskiq/src/riskiq/article_importer.py

* Fix attack-pattern ID generation
* Adapt parsing of attack-pattern tag
* https://github.com/OpenCTI-Platform/connectors/issues/2543
* https://github.com/OpenCTI-Platform/connectors/issues/2544

[RiskIQ] Fix handling of attack-pattern tag

---

external-import/malpedia/README.md
external-import/malpedia/src/malpedia_connector/malpedia.py
external-import/malpedia/src/malpedia_services/client.py
external-import/malpedia/src/malpedia_services/constants.py
external-import/malpedia/src/malpedia_tests/test_malpedia.py

* Better manage rate limits (Fix rate limit error)
* Add rate limit information to doc
* Fix KeyError ("refs") for Intrusion Set 
* More explicit logger added
* Update test_malpedia (status code 429)
* #2532

[Malpedia] Better manage rate limit

---

external-import/mandiant/src/connector/base.py

The current process of ingesting vulnerability reports is quite painful because it takes a long time.
What's actually happening is that when the connector starts the import, it waits for ALL the reports to be retrieved before bundling them. However, the period time set isn't always enough to retrieve everything, and before the bundle is queued, the connector restarts. The result is:
- No reports are queued for the dates currently being retrieved
- No ingestion occurs, leaving the work queue empty
- A new work item is created when the process restarts
* Send each report's bundle directly to the queue as soon as it's collected, just for the report collection process. This will allow the report to be ingested immediately without waiting for the entire retrieval process to finish.
* …

[Mandiant] Send bundle for each report and its context

---

external-import/mwdb/src/mwdb.py

Line 510 in mwdb.py
Handling keys from the extra tag process. Added exception handling with logging
Errors would occur if no extra tags were present.
*
Minor change

Fixed error when tags not present, added except

---

external-import/threatmatch/README.md
external-import/threatmatch/docker-compose.yml
external-import/threatmatch/src/config.yml.sample
external-import/threatmatch/src/threatmatch.py

* Added ability to upload IOCs from Threatmatch to OpenCTI
* None

Added IOC upload

---

.pre-commit-config.yaml

* Update isort from 5.10.1 to 5.12.0
* #2638

[connector] update isort version

---

external-import/alienvault/requirements.txt
external-import/crowdstrike/src/requirements.txt
external-import/ironnet/src/requirements.txt
external-import/kaspersky/src/requirements.txt
external-import/malpedia/src/requirements.txt
external-import/urlscan/src/requirements.txt
external-import/valhalla/src/requirements.txt
external-import/zerofox/src/requirements.txt
internal-enrichment/malbeacon/src/requirements.txt
internal-enrichment/shodan-internetdb/src/requirements.txt
internal-import-file/import-document/src/requirements.txt
stream/webhook/src/requirements.txt

This reverts commit 09035b26863d61334f45c4cc4579c341ad1f33c7.

[Fix Pydantic version] Revert "Update dependency pydantic to v2.9.2 (#2670)"

---

internal-enrichment/shodan/docker-compose.yml
internal-enrichment/shodan/src/config.yml.sample
internal-enrichment/shodan/src/shodanImport.py

Created config to give the ability to save the results as a note rather than the observable description. I set the default to false so it doesn't mess with existing processes.

[Shodan] Save results to note

---

stream/logrhythm/README.md

Fixing the configuration naming issue
*
*
*
*

Fix configuration issues

---

stream/logrhythm/src/logrhythm.py

hardcoded client name removed
*
*
*
*

Remove MSSP name

---

internal-enrichment/greynoise-vuln/.dockerignore
internal-enrichment/greynoise-vuln/.gitignore
internal-enrichment/greynoise-vuln/Dockerfile
internal-enrichment/greynoise-vuln/README.md
internal-enrichment/greynoise-vuln/docker-compose.yml
internal-enrichment/greynoise-vuln/entrypoint.sh
internal-enrichment/greynoise-vuln/src/config.yml.sample
internal-enrichment/greynoise-vuln/src/main.py
internal-enrichment/greynoise-vuln/src/requirements.txt

* Add new connector to support enrichment of Vulnerabilities via GreyNoise
* #2708

[greynoise-vuln] Add new GreyNoise Vulnerability internal enrichment connector (v2)

---

external-import/group-ib/README.md
external-import/group-ib/README_dev.md
external-import/group-ib/docker-compose.yml
external-import/group-ib/docs/configs/endpoints_config.yaml
external-import/group-ib/docs/configs/mapping.json
external-import/group-ib/docs/configs/qmapping.py
external-import/group-ib/src/adapter.py
external-import/group-ib/src/data_to_stix2.py
external-import/group-ib/src/lib/external_import.py
external-import/group-ib/src/main.py

[Group-IB Connector] bug fixes, code updates, ttl + [Improvements 2623](https://github.com/OpenCTI-Platform/connectors/issues/2623)
* TTL added via valid_from, valid_until parameters
* Intrusion Set support added and now optional
* References names update
* Bug fixes
* https://github.com/OpenCTI-Platform/connectors/issues/2623

[Group-IB Connector] bug fixes, code updates, ttl + Improvements 2623

---

external-import/threatfox/README.md

* Fixed docs for config value: `ioc_to_import`

fixed threatfox doc

---

.circleci/config.yml
internal-enrichment/greynoise-vuln/docker-compose.yml

* Add greynoise-vuln enrichment connector in CI

[Greynoise Vuln] Add greynoise-vuln enrichment connector in CI/CD

---

external-import/zerofox/src/collectors/collector.py
external-import/zerofox/src/open_cti/observables.py

* Fix ordering in ZeroFox intelligence collector
*

[ZeroFox] fix ordering in intelligence collector

---

external-import/ransomwarelive/src/lib/ransomConn.py

[ransomwarelive] Create predictive ids to prevent stix ids location explosion (#2768)

---

external-import/zerofox/src/collectors/collector.py
external-import/zerofox/src/collectors/mappers/botnetToInfrastructure.py
external-import/zerofox/src/collectors/mappers/c2DomainsToInfrastructure.py
external-import/zerofox/src/collectors/mappers/exploitToTool.py
external-import/zerofox/src/collectors/mappers/malwareToMalware.py
external-import/zerofox/src/collectors/mappers/phishingToInfrastructure.py
external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py
external-import/zerofox/src/collectors/mappers/vulnerabilityToVulnerability.py
external-import/zerofox/src/main.py
external-import/zerofox/src/open_cti/__init__.py
external-import/zerofox/src/open_cti/domain_objects.py
external-import/zerofox/src/open_cti/observables.py

* Changed domain_object calls to type specific constructors
* Adapted Connector constructor for better testing
* Changed stix object mapping from ZeroFox object for better handling by analysts
* [2780](https://github.com/OpenCTI-Platform/connectors/issues/2780)

[ZeroFox] Format intelligence objects

---

.circleci/config.yml

Add config for both sentinel-intel and sentinel-incidents connectors

[Sentinel connectors] add config to .circleci

---

external-import/misp/src/misp.py

* PR adds intrusion set from custom ESET galaxy

MISP connector add ESET galaxy

---

external-import/misp/src/misp.py

* PR sets tool name for PyMISP client, which helps enhancing telemetry for threat intelligence providers

MISP connector: set tool name for PyMISP

---

external-import/riskiq/src/riskiq/article_importer.py

* Set Main Observable type for indicators
*
* https://github.com/OpenCTI-Platform/connectors/issues/2804
*

[RiskIQ] set Main Observable type for indicators

---

internal-export-file/export-file-stix/src/export-file-stix.py

* entity type for "do_read" function updated for selections
* https://github.com/OpenCTI-Platform/opencti/issues/7796

[connectors] Error at relationships export in json (#7796)

---

internal-enrichment/import-external-reference/Dockerfile

* Add lib to use with playwright

[import-external-reference] Add lib to use with playwright

---

internal-enrichment/yara/Dockerfile

* Remove from yara unecessary lib

[Yara] Remove from yara unecessary lib

---

internal-enrichment/yara/Dockerfile

* Remove apt-get from yara Dockerfile

[yara] Remove apt-get from yara Dockerfile

---

internal-enrichment/attribution-tools/Dockerfile
internal-enrichment/import-external-reference/Dockerfile

* Change supported lib for attribution-tools in Dockerfile

[attribution-tools] change supported lib for attribution-tools in Dockerfile

---

.circleci/config.yml

* Update CircleCI build distribution
* https://github.com/OpenCTI-Platform/connectors/issues/2861

[connectors] Update CircleCI build distribution

---

.flake8

* restore the flake8 config file
* https://github.com/OpenCTI-Platform/connectors/issues/2865

[Connector] Revert flake8 config  file deletion

---

.circleci/config.yml

* Distribute build time for CI
* https://github.com/OpenCTI-Platform/connectors/issues/2901

[connectors] Distribute build time for CI

---

external-import/sentinel-incidents/Dockerfile
external-import/sentinel-incidents/README.md
external-import/sentinel-incidents/docker-compose.yml
external-import/sentinel-incidents/src/config.yml.sample
external-import/sentinel-incidents/src/sentinel_incidents_connector/client_api.py
external-import/sentinel-incidents/src/sentinel_incidents_connector/config_variables.py
external-import/sentinel-incidents/src/sentinel_incidents_connector/connector.py
external-import/sentinel-incidents/src/sentinel_incidents_connector/converter_to_stix.py
external-import/sentinel-incidents/src/sentinel_incidents_connector/utils.py
stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
stream/sentinel-intel/src/sentinel_intel_connector/config_variables.py

Improvments :
* Setting up the use of `fileEvidence` (Add stix Directory if available in `parent_directory_ref` for stix File)
* Setting up the use of `fileHashEvidence`
* Setting up the use of `malwareEvidence` (Add stix File if available in `sample_ref` for stix Malware)
* Addition of stix Directory and its relation to the incident, as well as stix Malware and its relation to the incident
* Addition of `recommended actions` in incident descriptions (for each alert in Microsoft Sentinel)
* Addition of a pagination system that also includes management of a possible rate limit
* Improved management of `import_start_date`
Fix :
* Fix variable env (remove confidence lvl in config.sample, 
* Fix docker compose (remove quote in target_product) 
* Fix problem of state
* Fix TLP_marking
* Fix …

[Sentinel-Incidents] Improvment feature

---

external-import/sentinel-incidents/Dockerfile

* Fix the image path in dockerfile
* #2887

[Sentinel Incidents] Fix dockerfile path

---

internal-import-file/import-file-misp/src/import-file-misp.py
internal-import-file/import-file-stix/src/import-file-stix.py

* we now add all containers and entity contained in containers from bundle to the contextual container
* [opencti #8178](https://github.com/OpenCTI-Platform/opencti/issues/8178)

[internal-import] add bundle containers to context entity container (OCTI #8178)

---

external-import/zerofox/src/collectors/mappers/botnetToInfrastructure.py
external-import/zerofox/src/collectors/mappers/malwareToMalware.py
external-import/zerofox/src/collectors/mappers/phishingToInfrastructure.py
external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py
external-import/zerofox/src/zerofox/domain/botnet.py
external-import/zerofox/src/zerofox/domain/malware.py
external-import/zerofox/src/zerofox/domain/phishing.py
external-import/zerofox/src/zerofox/domain/ransomware.py

* Rename class for botnet, malware, phishing, ransomware models
* https://github.com/OpenCTI-Platform/connectors/issues/2878

[Zerofox] Rename class for botnet, malware, phishing, ransomware models

---

templates/external-import/src/external_import_connector/connector.py

* Changed condition for stix_objects length to not equal 0
* Added work_id to send_stix2_bundle so the progress can be seen in GUI.
I didn't directly test the template, but I did make these changes and tested them in this PR for the Taxii connector: https://github.com/OpenCTI-Platform/connectors/pull/2894

[Template] Fixed condition and work id

---

.circleci/config.yml
README.md
internal-enrichment/orion-malware/src/main.py
shared/pylint_plugins/check_stix_plugin/README.md

* Add linter check for no generation id stix, no value parameter and unused import in Circle CI
* https://github.com/OpenCTI-Platform/connectors/issues/2923

[Connectors] Add linter check for no generation id stix, no value parameter and unused import in Circle CI

---

.circleci/config.yml

* Revert docker_layer_caching as some builds fail and behavior is not clear
* https://github.com/OpenCTI-Platform/connectors/issues/2879#issuecomment-2464130225

[Connectors] Revert docker_layer_caching

---

external-import/flashpoint/src/flashpoint.py

* check if `item["site_source_uri"]` is truthy prior to instatiate an External Reference STIX object
* #2867

[Flashpoint] Fix KeyError "site_source_uri"

---

stream/crowdstrike-endpoint-security/src/crowdstrike_services/client.py

* Improve condition in Crowdstrike stream
* https://github.com/OpenCTI-Platform/connectors/issues/2980

[connector] Improve condition in Crowdstrike stream

---

internal-enrichment/ipinfo/src/ipinfo.py

* Added elif to extract asn data from org field if using free plan.
* https://github.com/OpenCTI-Platform/connectors/issues/2895
Screenshot from free plan
Use ASN name: true
Use ASN name: false

[IpInfo] Added extraction of asn data from org field

---

.circleci/config.yml

* Move Qradar in another build
*

[Connectors] Move Qradar in another build

---

external-import/recorded-future/src/rflib/pyrf.py

* Add more explicit errors and do not stop the process when alerting rule is not found
* Remove assertion when getting priorities rules
* https://github.com/OpenCTI-Platform/connectors/issues/2989

[Recorded Future] Fix error when getting priority alerts for when getting Alerts

---

stream/crowdstrike-endpoint-security/src/crowdstrike_services/client.py

* Improve condition in Crowdstrike stream to avoid connector to crash
* https://github.com/OpenCTI-Platform/connectors/issues/2980#issuecomment-2492859843 (issue re opened)

[Crowdstrike] Improve condition in Crowdstrike stream

---

external-import/recorded-future/src/rflib/pyrf.py

* Fix import incidents for RF alerts
* https://github.com/OpenCTI-Platform/connectors/issues/3025

[Recorded Future] Fix import incidents for RF alerts

---

external-import/feedly/src/feedly/opencti_connector/connector.py
external-import/feedly/src/feedly/opencti_connector/runner.py

* Use the source name as the author
* Fix an issue for the newerThan parameter for feeds that caused some articles to not be ingested

[Feedly connector] use source name as author

---

external-import/tenable-vuln-management/src/tenable_vuln_management/connector.py
external-import/tenable-vuln-management/src/tenable_vuln_management/models/common.py
external-import/tenable-vuln-management/src/tenable_vuln_management/models/tenable.py
external-import/tenable-vuln-management/tests/test_converter_to_stix.py
external-import/tenable-vuln-management/tests/test_models/resources/tenable_api_response.json
external-import/tenable-vuln-management/tests/test_models/test_opencti.py
external-import/tenable-vuln-management/tests/test_models/test_tenable.py

* Integrate changes from tenable vuln management rest API response model
* Add Validation Warning for new extra parameters
* Add corresponding unit tests
* https://github.com/OpenCTI-Platform/connectors/issues/2997
https://docs.tenable.com/release-notes/Content/vulnerability-management/2024.htm#November-19,-2024

[Tenable Vuln Management] - Integrate source api changes

---

external-import/thehive/src/hive_observable_transform.py
external-import/thehive/src/thehive.py

* Change a logging level that was set to error but it is info.
* https://github.com/OpenCTI-Platform/connectors/issues/2825
N/A

[The Hive] - Change confusing logger level

---

.circleci/config.yml

* Add a build_4 in CircleCI
* Add a build_rolling_4 in CircleCI
* Add slack/notify and ms-teams/report missing in build_3 
* #3127

[CircleCI] Add a build_4 and build_rolling_4 (Bug #3127)

---

.circleci/config.yml

* Adding **Intel471_v2** in CircleCI (`Build_4`)
* Adding **Intel471_v2** in CircleCI (`Build_rolling_4`)
* #3137

[Intel471_v2] Adding intel471v_v2 in CircleCI

---

.circleci/config.yml

* Fix path in CircleCI the working directory
* #3164

[Google-secops-siem] Fix path in CircleCI the working directory

---

external-import/recorded-future/src/rflib/make_markdown_table.py
external-import/recorded-future/src/rflib/rf_playbook_alerts.py

* Handle properly incident ID generation to avoid Incident duplication
* Add modified date
* Handle correct markdown format
* https://github.com/OpenCTI-Platform/connectors/issues/3169
* https://github.com/OpenCTI-Platform/connectors/issues/3168

[Recorded Future] Handle properly incident ID generation and created and updated dates + correct markdown format

---

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py

* Modifies the way to configure plyara logger
* https://github.com/OpenCTI-Platform/connectors/issues/3172

VirusTotal Livehunt Notifications plyara - no attribute logger

---

stream/harfanglab-intel/src/config.yml.sample

Update HarfangLab sample config
- https://github.com/OpenCTI-Platform/connectors/issues/3188

Update HarfangLab config.yml.sample

---

external-import/harfanglab-incidents/src/harfanglab_incidents_connector/client_api.py
external-import/harfanglab-incidents/src/harfanglab_incidents_connector/connector.py
external-import/harfanglab-incidents/src/harfanglab_incidents_connector/converter_to_stix.py
external-import/harfanglab-incidents/src/harfanglab_incidents_connector/models/opencti.py

* Check if attribute exist before trying to use it
* Fix  typing and default None arguments.
* https://github.com/OpenCTI-Platform/connectors/issues/3153
*
[Investigation Page](https://www.notion.so/filigran/HARFANGLAB-INCIDENTS-Unsafe-Alert-Process-attributes-access-when-creating-File-1668fce17f2a804eafc2f298827eaaf8?pvs=4)

[HARFANGLAB INCIDENTS] - Unsafe Alert Process attributes access when creating File

---

external-import/intel471/src/requirements.txt

* Downgrade Titan-Client lib version to 1.20.0.4
* https://github.com/OpenCTI-Platform/connectors/issues/3206

[Intel471] Downgrade Titan-Client lib version to 1.20.0.4

---

.circleci/config.yml

* Add Stream connector Zscaler in CircleCi
* #1419
* #3226

[Zscaler] Stream Connector add Circleci

---

.circleci/config.yml

* Update CircleCI and remove Ipsum from build rolling 2
*
* https://github.com/OpenCTI-Platform/connectors/issues/3271

[All Connectors] Update CircleCI

---

.circleci/config.yml

* Add RST IOC LookUp connector in CI
* https://github.com/OpenCTI-Platform/connectors/issues/3306

[CircleCI] Add RST IOC LookUp connector in CI

---

.circleci/config.yml

* Add IBM X-Force in CI
* https://github.com/OpenCTI-Platform/connectors/issues/3309

[CircleCI] Add IBM X-Force in CI

---

internal-enrichment/rst-ioc-lookup/src/requirements.txt

* Change dependency range for RST IOC Lookup requirements
* https://github.com/OpenCTI-Platform/connectors/issues/3320

[RST IOC Lookup] Change dependency range for RST IOC Lookup requirements

---

internal-enrichment/abuseipdb/src/abuseipdb.py

* Add more accurate logs when issue occurring outside the main process 
*
* https://github.com/OpenCTI-Platform/connectors/issues/3326

[AbuseIPDB] Add more accurate logs when issue occurring outside the main process 

---

external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py

* Correct imports are incorrectly sorted and/or formatted
* https://github.com/OpenCTI-Platform/connectors/issues/3338

[Crowdstrike] Correct imports are incorrectly sorted and/or formatted

---

external-import/group-ib/Dockerfile

* Remove copy .env in Dockerfile
* https://github.com/OpenCTI-Platform/connectors/issues/3380

[GroupIB] Remove copy .env in Dockerfile

---

internal-enrichment/reversinglabs-spectra-analyze/src/main.py

* update existing connector with new classification API
* integrate new API in enrichment workflow
*
*
- [] I added/update the relevant documentation (either on github or on notion)

[reversinglabs-spectra-analyze] Add classification API support in workflow

---

external-import/tenable-vuln-management/README.md
external-import/tenable-vuln-management/src/tenable_vuln_management/config_variables.py

* Update Documentation
* Side improvement : hard-code connector_type
* https://github.com/OpenCTI-Platform/connectors/issues/3461
Related Notion Page : https://www.notion.so/filigran/tenable-vuln-management-add-missing-documentation-1a18fce17f2a80d59a23cd3c2204744a?pvs=4

[tenable vuln management] fix: missing documentation for connector duration period

---

external-import/dragos/dragos/interfaces/__init__.py
external-import/dragos/dragos/interfaces/common.py
external-import/dragos/dragos/interfaces/config.py
external-import/dragos/dragos/interfaces/report.py
external-import/dragos/pyproject.toml
external-import/dragos/tests/conftest.py
external-import/dragos/tests/tests_dragos/tests_interfaces/test_config.py
external-import/dragos/tests/tests_dragos/tests_interfaces/test_report.py

* Define interfaces for Dragos connector
* https://github.com/OpenCTI-Platform/connectors/issues/2570
Related Notion page : https://www.notion.so/filigran/Integration-Dragos-Create-the-connector-1528fce17f2a80dda61ed990b8e78b75

[Dragos] define interfaces

---

external-import/bambenek/Dockerfile

* Fix Dockerfile for CI
* https://github.com/OpenCTI-Platform/connectors/issues/3511

[Bambenek] Fix Dockerfile for CI

---

external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/connector.py
external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/utils.py

* correction of malware evidence dates
* Add a check to skip "ParseError_LengthExceedsLimit" Entities
* https://github.com/OpenCTI-Platform/connectors/issues/3516

[microsoft-sentinel-incidents] Error during imports related to the datetime format on the created field.

---

external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py

* Add a check and log the Entity
* https://github.com/OpenCTI-Platform/connectors/issues/3539

[microsoft-sentinel-incidents]: "NoneType" exception when converting HostEntity

---

external-import/group-ib/README.md
external-import/group-ib/src/adapter.py
external-import/group-ib/src/lib/external_import.py
external-import/group-ib/src/main.py
external-import/group-ib/src/utils.py

* Add updated logger, remove old usage of loggers
* Use traceback for catching errors outside process
* Update documentation
- details on known behavior when activate specific collection
* https://github.com/OpenCTI-Platform/connectors/issues/3582

[GroupIB] Fix logger + update documentation

---

external-import/recorded-future/README.md
external-import/recorded-future/src/main.py
external-import/recorded-future/src/rflib/rf_alerts.py
external-import/recorded-future/src/rflib/rf_client.py
external-import/recorded-future/src/rflib/rf_playbook_alerts.py
external-import/recorded-future/src/rflib/rf_to_stix2.py
external-import/recorded-future/src/rflib/risk_list.py
external-import/recorded-future/src/rflib/threat_map.py

*  Fix state usages and best practices for 
* Analyst Notes
* Alerts
* PlaybookAlerts
* Threat Maps
* Risk lists
* Update usage of logger instead of using deprecated one
* Update related documentation
* https://github.com/OpenCTI-Platform/connectors/issues/3625

[Recorded Future] Fix states usages and best practices

---

external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/connector.py
external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/converter_to_stix.py

* change log level from error to warning when information is not present 
* added a check for the presence of the field before processing an IpEvidence
* https://github.com/OpenCTI-Platform/connectors/issues/3652

Microsoft Defender for Endpoint connector data validation errors

---

internal-enrichment/shodan-internetdb/entrypoint.sh
internal-enrichment/shodan-internetdb/src/main.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/__main__.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/client.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/config.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/converter_to_stix.py
internal-enrichment/shodan-internetdb/src/shodan_internetdb/exceptions.py
internal-enrichment/shodan-internetdb/tests/conftest.py
internal-enrichment/shodan-internetdb/tests/test-requirements.txt
internal-enrichment/shodan-internetdb/tests/test_shodan_internet_db_connector.py

- Refacto :
- move main and add exception catch
- Extract and unify config
- Implement converter
- Move stix objects creation to converter
- Implement extract_and_check_markings
- Verify:
- Add author
- Add tlp marking
- Add external references
- Fix entity in scope
- Remove logger and not necessary
- Add error handling
- Change dynamic ID to hard coded
- Add tests
- https://github.com/OpenCTI-Platform/connectors/issues/3497

fix(shodan-internetdb) Fix for verify & refactoring

---

external-import/dragos/dragos/interfaces/__init__.py
external-import/dragos/dragos/interfaces/common.py
external-import/dragos/dragos/interfaces/geocoding.py
external-import/dragos/dragos/interfaces/report.py
external-import/dragos/tests/tests_dragos/tests_interfaces/test_geocoding.py
external-import/dragos/tests/tests_dragos/tests_interfaces/test_report.py

* Add a geocoding interface. This will be used to process the Geolocation Tag retrieved from Dragos report.
* https://github.com/OpenCTI-Platform/connectors/issues/2570
Related to Product Team decision about geolocation tag processing see : https://www.notion.so/filigran/Integration-Dragos-Create-the-connector-1528fce17f2a80dda61ed990b8e78b75?pvs=4#1c18fce17f2a80aba1e0d782b68b92ac

[Dragos] feat: implement geocoding interface

---

external-import/wiz/README.md

* Status verified for WIZ connector
*

fix(wiz): Update README status verified

---

external-import/intel471_v2/README.md

* https://github.com/OpenCTI-Platform/connectors/issues/3721

[Intel471v2] README: fix INTEL471_PROXY incorrect documentation formating

---

external-import/sekoia/src/sekoia.py

* Remove unused global variable as it's never re-assigned
- Flake8 raises an error on this line in the CI

[Sekoia] Fix unused global variable

---

external-import/group-ib/README.md
external-import/group-ib/src/lib/external_import.py
external-import/group-ib/src/main.py

* Remove threat actor creation if "intrusion-set instead of threat-actor" is set to true
* Update readme to indicate known issue
* https://github.com/OpenCTI-Platform/connectors/issues/3717

[GroupIB]  fix:  creates both threat actor and intrusion set insteaf of one of them

---

external-import/dragos/dragos/domain/models/octi/__init__.py
external-import/dragos/dragos/domain/models/octi/common.py
external-import/dragos/dragos/domain/models/octi/domain.py

* add UploadedFile model
* update Report model
* update use case to handle report's pdf
* #2570

[Dragos] Send pdf content alongside report

---

external-import/dragos/README.md
external-import/dragos/client_api/v1/common.py
external-import/dragos/client_api/v1/product.py
external-import/dragos/dragos/adapters/config/env.py
external-import/dragos/dragos/adapters/report/dragos_v1.py
external-import/dragos/dragos/app.py
external-import/dragos/dragos/domain/models/octi/common.py
external-import/dragos/dragos/domain/models/octi/domain.py
external-import/dragos/dragos/domain/use_cases/ingest_report.py
external-import/dragos/dragos/interfaces/config.py
external-import/dragos/dragos/interfaces/report.py
external-import/dragos/main.py
external-import/dragos/tests/tests_client_api/tests_v1/test_v1_product.py
external-import/dragos/tests/tests_dragos/test_app.py

* Add application and main
* Aside small fixes
* N/A

[Dragos] feat: add  application

---

internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
internal-enrichment/shodan-internetdb/tests/test_shodan_internet_db_connector.py

* Fix the use of playbook with the connector : 
* Get the entity type from the right data (data -> observable)
* Validate ipv4 after check on scope
* https://github.com/OpenCTI-Platform/connectors/issues/3497

[ShodanInternetDB] Fix playbook

---

external-import/dragos/README.md
external-import/dragos/dragos/domain/models/octi/domain.py
external-import/dragos/dragos/domain/use_cases/ingest_report.py
external-import/dragos/tests/tests_dragos/test_domain/test_models/test_domain.py

* update OCTI Report model to include `labels` field
* update `ingest_report` use case 
* #3868

[Dragos] Add reports' labels

---

internal-enrichment/shodan-internetdb/README.md

* Status verified for Shodan InternetDB connector
* https://github.com/OpenCTI-Platform/connectors/issues/3497

[ShodanInternetDB] Update README status verified

---

internal-import-file/import-document-ai/src/reportimporter/core.py

* add file in the stix bundle
* https://github.com/OpenCTI-Platform/connectors/issues/3903
Tested locally on a "real" pdf file

[Import Document AI] Import Document AI attaches file to report

---

stream/microsoft-defender-intel/Dockerfile

[microsoft-defender-intel] Fix Dockerfile

---

external-import/malwarebazaar-recent-additions/src/config.yml.sample
external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py

* Malware Bazaar connector should leverage the OpenCTIConnectorHelper api client and not instantiate its own
* Remove useless config options
* Add default config parameter values
* Add marking on indicators
* https://github.com/OpenCTI-Platform/connectors/issues/3866
*

[MalwareBazaar-recent-additions] : fixes

---

internal-enrichment/shodan-internetdb/tests/test_shodan_internet_db_connector.py

* Fix Flaky test using the real API and not mocking
* https://github.com/OpenCTI-Platform/connectors/issues/3497

[ShodanInternetDB] Fix flaky test

---

internal-enrichment/hygiene/README.md
internal-enrichment/hygiene/src/config.yml.sample
internal-enrichment/hygiene/src/hygiene.py
internal-enrichment/hygiene/tests/conftest.py
internal-enrichment/hygiene/tests/mock_config.yaml
internal-enrichment/hygiene/tests/test-requirements.txt
internal-enrichment/hygiene/tests/test_hygiene_connector_init.py
internal-enrichment/hygiene/tests/test_hygiene_enrichment.py

* Add configuration option for label name and color.
* Add configuration option for parent label name and color.
* More verbose feedback, including warninglists that were matched and score.
* Defaults are backwards compatible with previous behavior.
* Re-iteration of cancelled PR #3383 but now with more code-signing.
* https://github.com/OpenCTI-Platform/connectors/issues/4056

[Hygiene] Add configurable labels

---

external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py

* Add multiple infos from incident to case incident description
* https://github.com/OpenCTI-Platform/connectors/issues/3739

[MicrosoftSentinelIntel] Add infos to case incident description

---

external-import/recorded-future/src/rflib/rf_playbook_alerts.py
external-import/recorded-future/src/rflib/rf_to_stix2.py

* set `x_opencti_created_by_ref` custom property on every observable
* #4070

[Recorded Future] Add observables' missing author

---

external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py

* Handle None value for Remediation alert field
* https://github.com/OpenCTI-Platform/connectors/issues/4081

[MicrosoftSentinelIncident] Add infos to case incident description

---

external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py
external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py

* Delete initial logger
* Add log warning
* Add try/except
* Update returns for indicators and reports (change log_level)
* #4140

[Crowdstrike] Fix error in report

---

external-import/riskiq/README.md
internal-enrichment/riskiq-passive-total/README.md

* RiskIQ connectors depreciation added to respective READMEs.
- External-Import - RiskIQ
- Internal-Enrichment - RiskIQ Passive-Total
* #3515

[RiskIQ] Add in readme, deprecated connectors

---

external-import/accenture-acti/src/accenture_connector/converter_to_stix.py

[Accenture-ACTI] Fix linter

---

external-import/malwarebazaar-recent-additions/docker-compose.yml
external-import/malwarebazaar-recent-additions/src/config.yml.sample
external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py

* Add required auth key to malwarebazaar-recent-additions
* [4311 - API key authentication now required](https://github.com/OpenCTI-Platform/connectors/issues/4311)
* [4258 - Add API key authentication to existing connector](https://github.com/OpenCTI-Platform/connectors/issues/4258) - Same problem, different connector

[MalwareBazaarRecentAddition] Add required auth key

---

external-import/s3/src/s3.py

* Enhance the connector with more mappings 
* https://github.com/OpenCTI-Platform/connectors/issues/4338

[s3] Enhance the connector with more mappings V2

---

external-import/s3/README.md

Under "Description", changed the "Full name of the connector" to be S3
*
*
*
*

[S3] Update README.md

---

internal-enrichment/recordedfuture-enrichment/README.md
internal-enrichment/recordedfuture-enrichment/docker-compose.yml
internal-enrichment/recordedfuture-enrichment/entrypoint.sh
internal-enrichment/recordedfuture-enrichment/src/config.yml.sample
internal-enrichment/recordedfuture-enrichment/src/main.py
internal-enrichment/recordedfuture-enrichment/src/rflib/__init__.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_client.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_connector.py
internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py

* add `EnrichedVulnerability` class
* add `get_vulnerability_enrichment` in RecordedFuture API client
* split use cases in _rf_connector.py_
* #4190 
This PR aims to implement the enrichment of OCTI Vulnerability's <ins>**properties only**</ins>.
In next PR, the enrichment of OCTI Vulnerability will include the creation of multiple STIX objects and relationships.
In this context, some fixes/code improvements will be included, such as:
- dependencies versions will be added in _requirements.txt_
- classes in _rf_to_stix2.py_ will be replaced by **pydantic** models in a dedicated file
- **pydantic-settings** and _config_loader.py_ will be added

[RecordedFuture-Enrichment] Enrich OCTI vulnerability (properties only)

---

external-import/threatmatch/src/threatmatch/connector.py
external-import/threatmatch/tests/threatmatch/conftest.py
external-import/threatmatch/tests/threatmatch/test_connector.py

* refactor: Move declaration
* refactor: Move business logic to own _collect_intelligence method
* refactor: Remove condition replaced by schedule_process
* refactor: Clean up log and definition of last_run
* refactor: Clean up unecessary variables
* refactor: Move import_from_date_definition to business logic
* refactor: clean up datetime methods
* tests: Add test_connector_process_data_last_run
* refactor: Save isoformat instead of timestamp in state
* refactor: Change logging
* refactor: Remove unused
* https://github.com/OpenCTI-Platform/connectors/issues/3500

[ThreatMatch] Cleanup, tests and restructuration

---

external-import/s3/src/s3.py

* Fix a bug when creating external references
* https://github.com/OpenCTI-Platform/connectors/issues/4436

[S3] Connector crashes trying to parse 'reference'

---

external-import/threatmatch/src/threatmatch/client.py
external-import/threatmatch/src/threatmatch/connector.py

* refactor: Implement Client with token
* refactor: Implement request + get_profile_ids
* refactor: Implement get_alert_ids
* refactor: Implement get_indicators
* refactor: Implement get_stix_bundle
* https://github.com/OpenCTI-Platform/connectors/issues/3500

[ThreatMatch] Implement client

---

internal-enrichment/shodan/src/shodanImport.py

* Before
* After
* https://github.com/OpenCTI-Platform/connectors/issues/4384

[Shodan] Fix playbook

---

external-import/s3/src/s3.py

* Support of "technology" and "technology-to" relationships
* Rewriting of STIX identifiers
* Closes #4509

[s3] Connector enhancements (#4509)

---

run_test.sh

* [CircleCI]: Fix test results storage
* https://github.com/OpenCTI-Platform/connectors/issues/4461

[CircleCI]: Fix test results storage

---

connectors-sdk/connectors_sdk/models/octi/__init__.py
connectors-sdk/connectors_sdk/models/octi/activities/analyses.py
connectors-sdk/connectors_sdk/models/octi/activities/observations.py
connectors-sdk/connectors_sdk/models/octi/enums.py
connectors-sdk/connectors_sdk/models/octi/knowledge/arsenal.py
connectors-sdk/connectors_sdk/models/octi/knowledge/entities.py
connectors-sdk/connectors_sdk/models/octi/knowledge/threats.py
connectors-sdk/tests/test_models/test_octi/test_activities/test_analyses.py
connectors-sdk/tests/test_models/test_octi/test_activities/test_observations.py
connectors-sdk/tests/test_models/test_octi/test_api.py
connectors-sdk/tests/test_models/test_octi/test_knowledge/test_arsenal.py
connectors-sdk/tests/test_models/test_octi/test_knowledge/test_entities.py
connectors-sdk/tests/test_models/test_octi/test_knowledge/test_threats.py
external-import/s3/src/s3.py

* add IPV6Adress + unit tests
* add DomainName + unit tests
* add URL + unit tests
* add File + unit tests
* add Malware + unit tests
* add Individual + unit tests
* add ThreatActorGroup + unit tests
* add new enums
* #4261 
This PR is required for RecordedFuture Enrichment connector.

[connectors-sdk] Add IPV6Address, DomainName, URL, File, Malware, Individual and ThreatActorGroup models

---

external-import/thehive/src/thehive.py

* Fix SSL verification
* Fix logger issue
* https://github.com/OpenCTI-Platform/connectors/issues/4382

[thehive] Fix SSL verify + fix logger issue

---

internal-enrichment/hygiene/docker-compose.yml
internal-enrichment/hygiene/src/config.yml.sample
internal-enrichment/hygiene/src/hygiene.py

* Fix Case is taken into account for Indicator
* https://github.com/OpenCTI-Platform/connectors/issues/4530

[Hygiene] Fix Case is taken into account for Indicator

---

external-import/flashpoint/__metadata__/connector_manifest.json

[flashpoint]: fix flashpoint manifest name and description

---

internal-enrichment/ipinfo/__metadata__/connector_manifest.json
internal-enrichment/ipinfo/src/__main__.py
internal-enrichment/ipinfo/src/models/configs/config_loader.py
internal-enrichment/ipinfo/src/models/configs/connector_configs.py

* Catch 403 errors
* https://github.com/OpenCTI-Platform/connectors/issues/4576

[IpInfo] Invalid message when a bad API Token is configured

---

external-import/cve/__metadata__/connector_manifest.json

* [composer] fix cve manifest name
*
*
*

[composer] fix cve manifest name

---

shared/tools/composer/generate_connectors_config_json_schemas.py.sample

Remove connector ID from manifest

[composer] Remove connector_id from schema generation

---

external-import/sekoia/src/connector/models/configs/config_loader.py
external-import/sekoia/src/connector/models/configs/connector_configs.py
external-import/sekoia/src/requirements.txt

* migrate Sekoia scope configuration from str to ListFromString
* https://github.com/OpenCTI-Platform/connectors/issues/4658

[composer] migrate Sekoia scope configuration from str to ListFromString

---

stream/tanium-intel/README.md
stream/tanium-intel/docker-compose.yml
stream/tanium-intel/src/config.yml.sample
stream/tanium-intel/src/tanium_intel_connector/api_handler.py
stream/tanium-intel/src/tanium_intel_connector/config_variables.py

* feat: Add TANIUM_INTEL_DEPLOY_INTEL configuration
* https://github.com/OpenCTI-Platform/connectors/issues/4720

[TaniumIntel] Add TANIUM_INTEL_DEPLOY_INTEL configuration

---

internal-enrichment/joe-sandbox/README.md

Correct URL for JOe

---

external-import/dogesec-ctibutler/src/connector.py

* Use updated endpoints in dogesec-ctibutler
* Add support for new knowledgebase type
* #4415

[ctibutler] fix renamed paths, add new knowledgebase

---

.github/workflows/auto-author-assign.yml

* Auto assign PR on creation
* https://github.com/OpenCTI-Platform/connectors/issues/4790

 [GithubAction] Auto assign PR on creation

---

external-import/google-ti-feeds/connector/src/custom/mappers/gti_vulnerabilities/gti_vulnerability_to_stix_note.py

[x] Remove cve-cve- label from Vulnerability Notes (don’t replace it).
This PR is part of the umbrella PR #4810 to solve the issues identified in #4801
Before:
After:
Umbrella PR: https://github.com/OpenCTI-Platform/connectors/pull/4810
Base Issue: https://github.com/OpenCTI-Platform/connectors/issues/4801

[Google TI] Fix CVE label #4810

---

external-import/google-ti-feeds/README.md

This PR is part of the umbrella PR #4810 to solve the issues identified in #4801
Umbrella PR: https://github.com/OpenCTI-Platform/connectors/pull/4810
Base Issue: https://github.com/OpenCTI-Platform/connectors/issues/4801

[Google TI] Add warning about the aliases being disable. #4810

---

internal-import-file/import-document-ai/src/reportimporter/core.py
internal-import-file/import-document/src/reportimporter/core.py

*
*
* [opencti #12210](https://github.com/OpenCTI-Platform/opencti/issues/12210)
* https://github.com/OpenCTI-Platform/connectors/issues/4866

[importdoc] fix check for file (if in a draft, file_id starts with draft/{draft_id}/import/global)

---

internal-export-file/export-ttps-file-navigator/src/export-ttps-file-navigator.py

* Now properly raise an error when an export other than single is asked
* https://github.com/OpenCTI-Platform/opencti/issues/11843

[ExportTTP] Now properly raise an error when an export other than single is asked
