OpenCTI-Platform/connectors

misp/config.json, misp/misp.py
This allows to disable the removal of OpenCTI import tags.
=> [misp] added config switch to disable tag removal.

misp/misp.py
The latest commit uses the hardcoded "OpenCTI: Import" tag for searching events in MISP instead of the tag given in the config.
=> Use tag given in the config instead of a hardcoded one for searching events

.circleci/config.yml
Actually add format and linting check jobs to a dedicated circl-ci workflow.
As this should be run for every push on every branch I did not add any filters.
=> Actually add liniting and formatting to workflow

alienvault/Dockerfile, amitt/Dockerfile, crowdstrike/Dockerfile, cryptolaemus/Dockerfile, cve/Dockerfile, cyber-threat-coalition/Dockerfile, export-file-csv/Dockerfile, export-file-stix/Dockerfile, import-file-pdf-observables/Dockerfile, import-file-stix/Dockerfile, ipinfo/Dockerfile, malpedia/Dockerfile, misp/Dockerfile, mitre/Dockerfile, opencti/Dockerfile, virustotal/Dockerfile
I propose we unify the base image for all current connectors.
The current base images are diverse and somewhat behind in fixes and might include security bugs.
By also removing the python and alpine minor versions we ensure the latest security and bug-fix releases will be used for OpenCTI docker releases.
This PR changes all base images to `python:3.7-alpine`.
=> Unify the base images for all connectors

.circleci/config.yml, .gitignore, README.md, hygiene/.dockerignore, hygiene/.gitignore, hygiene/Dockerfile, hygiene/Readme.md, hygiene/docker-compose.yml, hygiene/entrypoint.sh, hygiene/src/config.yml.sample, hygiene/src/hygiene.py, hygiene/src/requirements.txt
This pull request adds the hygiene connector to OpenCTI.
The connector adds the following information for observables:
* `Hygiene` tag to observables if they are on [misp-warninglists](https://github.com/MISP/misp-warninglists)
* external references for every matching warninglist
Due to descriptive tags this can be used to get rid of indicators that might lead to false positive when used for detection by searching for the `Hygiene` tag.
Possible future features:
* also decrease score for all indicators (needs work on `Indicator` class in pycti)
=> Add hygiene connector

alienvault/Dockerfile, amitt/Dockerfile, crowdstrike/Dockerfile, cryptolaemus/Dockerfile, cve/Dockerfile, cyber-threat-coalition/Dockerfile, export-file-csv/Dockerfile, export-file-stix/Dockerfile, hygiene/Dockerfile, import-file-pdf-observables/Dockerfile, import-file-stix/Dockerfile, ipinfo/Dockerfile, lastinfosec/Dockerfile, malpedia/Dockerfile, misp/Dockerfile, mitre/Dockerfile, opencti/Dockerfile, virustotal/Dockerfile
As suggested by @2xyo there is no reason to stick with python 3.7 and move to 3.8 instead.
=> Move all connectors to python 3.8

malpedia/Readme.md, malpedia/src/malpedia/client.py
This PR enables the Malpedia connector without using a token and thus needing a Malpedia account.
If API_KEY is left empty or undefined only TLP:WHITE entities are imported from the public API without authentication.
=> Make it possible to run Malpedia without token

hygiene/Readme.md, hygiene/src/hygiene.py
With this PR the Hygiene connector also tags all Indicators of a warning-list detection with an observable.
In addition it sets a weighted indicator score below 20 based on the number of warning-list entries for the parent observable (1:15, >=3:10, >=5:5, default:20).
=> [Hygiene] Add tag to indicators as well

cve/src/cve.py
History starts for newly created OpenCTI platforms, but not for existing ones.
Fixed operator `AND` preventing history launch for OpenCTI platforms already installed once.
=> Fixed operator

valhalla/src/valhalla/knowledge.py
In some cases the creation of indicator<> intrusion set creations failed.
The following change fixes this.
=> [valhalla] Fix relation creation

misp/README.md, misp/docker-compose.yml, misp/src/config.yml.sample, misp/src/misp.py, misp/src/requirements.txt
The `misp_import_from` date should be in YYYY-MM-DD format.
This PR ensures that the pymisp functions always use timestamps as is the MISP default.
In addition this PR adds support for `NOT` tags.
Reference: #102
=> [MISP] Bugfix: wrong date format

cve/src/cve.py, cve/src/requirements.txt, mitre/src/mitre.py, mitre/src/requirements.txt
The behavior of urllib changes in Python 3.6 as noted, here:
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
These changes address that issue.
=> Fixes to mitre connector to address urllib changes in Python >=3.6

cybercrime-tracker/src/cybercrime-tracker.py
Fixing this typo ensures `self.interval` gets populated:
https://github.com/OpenCTI-Platform/connectors/blob/d95edd27bd3f6ef826eaeb2d629f57885d4957ba/cybercrime-tracker/docker-compose.yml#L17
If `self.interval` is None then this line fails:
https://github.com/OpenCTI-Platform/connectors/blob/d95edd27bd3f6ef826eaeb2d629f57885d4957ba/cybercrime-tracker/src/cybercrime-tracker.py#L163
fixes #213
=> use correct naming scheme when retrieving interval value

lastinfosec/Dockerfile, lastinfosec/README.md, lastinfosec/docker-compose.yml, lastinfosec/src/config.yml.sample, lastinfosec/src/lastinfosec.py
Hello,
We have made some changes in our lastinfosec connector to use our stix2.1 api rather than stix 2.0
Best regards,
Rémy DEWAILLY
=> move lastinfosec cti feed to stix2.1 version

misp/src/requirements.txt
Pymisp changed to install last release and align it automatically to last Misp version
=> Change pymisp requirement

.pre-commit-config.yaml
No more [CircleCI linter/ensure_formatting failures](https://github.com/OpenCTI-Platform/connectors/pulls?q=is%3Apr+status%3Afailure) with  `pre-commit` :) 
```
$ pip install pre-commit
$ pre-commit install
$ git add .pre-commit-config.yaml 
$ git commit -m "pre-commit setup"
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
Check Yaml...............................................................Passed
[precommit 5be35e3] pre-commit setup
1 file changed, 14 insertions(+)
create mode 100644 .pre-commit-config.yaml
```
=> pre-commit setup

taxii2/src/taxii2.py
Quick PR, not tested :grimacing:  ! 
Should fix:
```
INFO:root:Run Complete. Sleeping until next run in None hours
Traceback (most recent call last):
File "taxii2.py", line 245, in <module>
raise (e)
File "taxii2.py", line 243, in <module>
CONNECTOR.run()
File "taxii2.py", line 134, in run
time.sleep(self.get_interval())
File "taxii2.py", line 93, in get_interval
return int(self.interval) * 3600
```
=> Fix typo and add a default interval of one hour

urlhaus/src/config.yml.sample, urlhaus/src/urlhaus.py
This PR resolves the issue #290 by adding the ability to control indicator creation (True/False) through config file in OpenCTI
=> Add control over URLhaus indicator creation [#290]

misp/src/misp.py
Fixes #291 
It would pass a broken json/dict object to ExpandedPyMISP
I would appreciate someone else reproducing the same findings before merging this pull request
=> [MISP] Fixed ERROR:root:search() keywords must be string

misp/README.md
The MISP_CREATE_OBSERVABLES and MISP_CREATE_INDICATORS options were
added to control the ingestion of MISP attributes. Without specifying
these, the attributes in MISP will not be imported.
Should fix #308
=> Add MISP_CREATE_OBSERVABLES and MISP_CREATE_INDICATORS to README.md

threatbus/README.md, threatbus/src/config.yml.sample, threatbus/src/connector.py
This PR adds a config option to the Threat Bus connector, so users can decide to either forward all Indicators from OpenCTI or only those that have the `detection` toggle set to `true`.
=> Add config option to respect detection toggle

import-file-stix/src/requirements.txt
Avoid import error: ModuleNotFoundError: No module named 'maec'
* https://maecproject.github.io/
* https://github.com/MAECProject/python-maec/
=> [import-file-stix] Add maec to requirments.txt

threatbus/README.md, threatbus/src/config.yml.sample, threatbus/src/connector.py, threatbus/src/threatbus_connector_helper.py
This PR adds the capability to request [snapshots](https://docs.tenzir.com/threatbus/features/snapshotting). Users can now configure the `snapshot: X` property in the connector's config file to request `X` days of historic indicators from Threat Bus. These indicators are then ingested into OpenCTI via API calls.
=> Request snapshots with the Threat Bus OpenCTI connector

misp/src/misp.py
If you created objects and relationships between them in MISP, they wouldn't be imported into OpenCTI.
I thought this was an important feature, so now it links the relevant indicators.
In MISP you can have "Reports". These can be auto generated or manually submitted.
I've also added support for this. It gets added as a Note with a reference to the report.
=> [MISP] Added object relationships + report support

misp/README.md, misp/src/config.yml.sample, misp/src/misp.py
- When a MISP EventReport gets imported, we change the @object and @attribute links to OpenCTI links.
MISP:
OCTI:
- When we imported a MISP object with attributes, we omitted the MISP object, now we create it as a OCTI Text Observable
MISP:
OCTI Before:
OCTI After:
- Relationships between MISP objects & MISP attributes are now also correctly reflected:
- When the connector can't find the correct observable (e.g. cookie) it will import it as a OpenCTI-Text observable. In the value it'll also give its real type
=> [MISP] process_note + text fallback + import MISP objects

threatbus/src/connector.py, threatbus/src/threatbus_connector_helper.py
Since OpenCTI 4.5.1 deleted indicators are fully available in the SSE stream. This PR picks up the change and correctly forwards removed indicators to Threat Bus.
Additionally, this PR adds a little check before creating/updating indicators with messages received from Threat Bus, so we effectively avoid updating stuff when there are no changes. This in turn avoids unnecessary events in the SSE stream.
=> Propagate indicator removal & avoid double updates

misp/src/misp.py
We didn't import the MISP date for Reports, now we do
=> [MISP] Use correct date from MISP

import-file-stix/src/import-file-stix.py, import-file-stix/src/requirements.txt
Implemented following feature request:
https://github.com/OpenCTI-Platform/opencti/issues/1402
The Stix knowledge gets only appended to the current report, if the Stix file doesn't contain a report and if the Stix upload is NOT contextual.
=> [ImportFileStix] Add Stix knowledge to existing Report

threatbus/src/connector.py, threatbus/src/threatbus_connector_helper.py
Clarify some log messages and use the proper log level for a warning.
=> Clarify log messages

misp/src/misp.py
Fixed an issue with wrong creation date for MISP event ingestion.
I kept the use of datetime.utcfromtimestamp, after a little research it seems that this method is not quite safe.
According to https://docs.python.org/3/library/datetime.html, this is the safe method: 
datetime.fromtimestamp(timestamp, timezone.utc) 
timezone should be also imported from datetime in order for this to work.
=> fixed MISP event creation date and modification date

threatbus/src/requirements.txt, threatbus/src/threatbus_connector_helper.py
The connector was still expecting the full endpoint as opposed to just the port. This also upgrades to latest threatbus in the process.
=> Fix bug where threatbus did not connect

abuseipdb/src/abuseipdb.py
Modified code to improve performance on handling the sightings from AbuseIPDB. Original code went through all the sighting calling the API for every individual entry. This occasionally caused several thousand OpenCTI interface calls for a single IP address.
New code is correlating and all sightings in the connector and calling the OpenCTI API using total results. This reduces the number of calls (in case of many sightings like example IP address 42.194.168.209) from a few thousand 1000 to approx. 50.
=> Performance improvements on IP sightings

external-import/riskiq/src/riskiq/article_importer.py
* Instead of setting the TLP_marking of the report as AMBER, look at the IoC's TLPs:
If all IoC's TLPs are WHITE, the report is WHITE, otherwise it is AMBER.
N/A
=> [riskiq] set report's tlp as AMBER if not all IoC's are WHITE

external-import/alienvault/.dockerignore, external-import/amitt/.dockerignore, external-import/crowdstrike/.dockerignore, external-import/cryptolaemus/.dockerignore, external-import/cuckoo/.dockerignore, external-import/cve/.dockerignore, external-import/cyber-threat-coalition/.dockerignore, external-import/cybercrime-tracker/.dockerignore, external-import/fireeye/.dockerignore, external-import/lastinfosec/.dockerignore, external-import/malpedia/.dockerignore, external-import/misp/.dockerignore, external-import/mitre/.dockerignore, external-import/opencti/.dockerignore, external-import/riskiq/.dockerignore, external-import/sekoia/.dockerignore, external-import/taxii2/.dockerignore, external-import/thehive/.dockerignore, external-import/threatmatch/.dockerignore, external-import/urlhaus/.dockerignore, external-import/valhalla/.dockerignore, external-import/vxvault/.dockerignore, internal-enrichment/lastinfosec/.dockerignore, internal-import-file/import-report/.dockerignore, template/.dockerignore
Only a few connectors have a `.dockerignore` file. There should be a `.dockerignore` file for every connector, especially to avoid having the cache folder and the `config.yml` file inside the docker image. 
Having the `config.yml` file inside the images can lead to some nasty bugs. For example having a variable set in the `config.yml` file and not set (overriden) in the docker-compose file can make us think that the variable is not set even if it is because of the `config.yml` file. 
* Add a `.dockerignore` file for every connector.
N/A
=> [connector] add missing dockerignore files

internal-enrichment/cape-sandbox/.dockerignore, internal-enrichment/cape-sandbox/.gitignore, internal-enrichment/cape-sandbox/Dockerfile, internal-enrichment/cape-sandbox/docker-compose.yml, internal-enrichment/cape-sandbox/entrypoint.sh, internal-enrichment/cape-sandbox/src/cape-sandbox.py, internal-enrichment/cape-sandbox/src/config.yml.sample, internal-enrichment/cape-sandbox/src/requirements.txt
* Add internal enrichment CAPEv2 Sandbox connector
This Connector was developed to aid analysts in the research of Artifacts. As an Internal Enrichment based Connector, an analyst can refresh the knowledge on a particular Artifact and all associated hosts, domains will be attached as relationships to the original artifact. For any identified malware configurations, they will be attached to the original artifact as a Note. The same goes for trID results. All TTPs and FLARE Capa TTPs will also be associated with the original artifact as Attack Patterns with associated TTP #. All CAPE payloads and process dumps will be uploaded As Artifacts associated to the original artifact and include: unpacked shellcode, injected shellcode, unpacked payloads, etc. All uploaded Artifacts are labeled …
=> [internal enrichment] Add CAPEv2 Sandbox Connector

internal-enrichment/intezer-sandbox/Dockerfile, internal-enrichment/intezer-sandbox/docker-compose.yml, internal-enrichment/intezer-sandbox/entrypoint.sh, internal-enrichment/intezer-sandbox/src/config.yml.sample, internal-enrichment/intezer-sandbox/src/intezer_api.py, internal-enrichment/intezer-sandbox/src/intezer_sandbox.py, internal-enrichment/intezer-sandbox/src/requirements.txt
* Add Intezer Sandbox Connector
This Connector has been written to improve the efforts of analysts while analyzing Artifacts. An analyst can send an Artifact for analysis by Intezer Sandbox and retrieve the results as an external reference to the Artifact, in addition to labels being applied to the Artifact such as: verdict (malicious, suspicious, trusted, unknown) and malware family (if any).
=> [internal enrichment] Add Intezer Sandbox Connector

internal-enrichment/cape-sandbox/docker-compose.yml, internal-enrichment/cape-sandbox/src/cape-sandbox.py, internal-enrichment/cape-sandbox/src/config.yml.sample
* Minor bug fixes
* Add static extraction
These changes were made to improve the processing time it takes to extract malware configurations from samples that are already unpacked. By enabling the config option "try_extract" first CAPE will attempt to extract the configuration without sending the file to a VM.
=> [cape-sandbox] add static extraction config option

internal-enrichment/cape-sandbox/src/cape-sandbox.py, internal-enrichment/cape-sandbox/src/requirements.txt
* Fix re-trying upon API failure
It occurred to me recently that there was a bug where the CAPEv2 API will throttle. These changes fix the re-trying capabilities.
=> [cape-sandbox] Fix re-trying upon API failure

internal-enrichment/ivre/src/ivre_connector.py
* TOR certificates are not self signed. This simple heuristic prevents some false positives.
* This heuristic is also used in ivre/ivre#1240
That's a tiny-yet-important change, as most false positives get catched by this simple heuristic.
=> IVRE: prevent false positives in TOR certificates detection

external-import/malwarebazaar-recent-additions/.dockerignore, external-import/malwarebazaar-recent-additions/Dockerfile, external-import/malwarebazaar-recent-additions/docker-compose.yml, external-import/malwarebazaar-recent-additions/entrypoint.sh, external-import/malwarebazaar-recent-additions/src/config.yml.sample, external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py, external-import/malwarebazaar-recent-additions/src/requirements.txt
* [external-import] Add MalwareBazaar Recent Additions Connector
This Connector was created to allow pro-active threat research of samples available in MalwareBazaar. Samples are uploaded to MalwareBazaar by IT-security researchers and include file types such as: doc, docm, docx, exe, dll, etc. This Connector will periodically poll the recent additions API of MalwareBazaar and download any not-yet uploaded samples and upload them into OpenCTI with associated tags as labels.
=> [external-import] Add MalwareBazaar Recent Additions Connector

external-import/urlhaus-recent-payloads/.dockerignore, external-import/urlhaus-recent-payloads/Dockerfile, external-import/urlhaus-recent-payloads/docker-compose.yml, external-import/urlhaus-recent-payloads/entrypoint.sh, external-import/urlhaus-recent-payloads/src/config.yml.sample, external-import/urlhaus-recent-payloads/src/requirements.txt, external-import/urlhaus-recent-payloads/src/urlhaus-recent-payloads.py
* [external import] Add URLHaus Recent Payloads Connector
This Connector was created to enable pro-active threat research of samples available in URLHaus. Samples are uploaded to URLHaus by IT-security researchers and include file types such as: doc, docm, docx, exe, dll, etc. This Connector will periodically poll the recent payloads API of URLHaus and download any not-yet uploaded samples and upload them into OpenCTI with associated signature and filetype as labels.
=> [external-import] Add URLHaus Recent Payloads Connector

internal-enrichment/hatching-triage-sandbox/src/hatching-triage-sandbox.py
* Resolve bug where AgentTesla samples aren't processed correctly, exception: 
```
* raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Relationship 'target_ref': reference to custom object type: x-opencti-simple-observable
```
=> [hatching triage sandbox] Resolve "stix2.exceptions.InvalidValueError: Invalid value for Relationship 'target_ref'"

external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py
* Fix cooldown_seconds being parsed as string
* Fix iterating issue when `MALWAREBAZAAR_RECENT_ADDITIONS_LABELS` not present in the config
* Fix iterating issue when a recent addition has no tags
* None because this was a quick fix and didn't open one
=> [MalwareBazaar Recent Additions] bugfixes

external-import/riskiq/src/riskiq/article_importer.py
The field `publishedDate` returned by RiskIQ API is null, making it impossible to use it for the published date of the report. If the `publishedDate` is null, use the `createdDate` instead.
Fixes #606
* Use the `createdDate` as published date if the `publishedDate` is null. 
* #606
=> [riskiq] fix importation when `publishedDate` is not provided

external-import/misp/src/misp.py
* Fixes MISP connector bug by setting `x_mitre_id` to `None` if it is not returned by misp
* #626
This sets `x_mitre_id` to `None` if it is not returned by misp, right now it crashes
=> [misp] fixes bug with no external_id in AttackPattern

external-import/thehive/src/thehive.py
Right now thehive come with hostname observable, because of that the thehive connector is crashing and cannot import cases with hostname type as observable.
connector-thehive_1                          | INFO:root:Connector last_case_date: 2022-03-15 07:30:59
connector-thehive_1                          | INFO:root:Get cases since last run (2022-03-15 07:30:59)
connector-thehive_1                          | INFO:root:Initiate work for f27f6437-d79e-444c-a20f-11af49e91902
connector-thehive_1                          | ERROR:root:'hostname'
connector-thehive_1                          | INFO:root:Connector successfully run, storing last_run as 1647329519
connector-thehive_1                          | INFO:root:Reporting work update_received opencti-work--5f5465af-f9aa-45a0-8fdc-e51eedbcfb9e …
=> [thehive_connector] Add hostname observable in thehive connector

internal-export-file/export-report-pdf/Dockerfile
* Adding cairo-dev apk in Dockerfile
* export report in pdf is broken
* connector logs shows root cause is absence of pango-1.0-0 library
Observed error:
docker-compose -f docker-compose.yml logs -f connector-export-report-pdf
Attaching to docker_connector-export-report-pdf_1
connector-export-report-pdf_1  | Traceback (most recent call last):
connector-export-report-pdf_1  |   File "/opt/opencti-connector-export-report-pdf/export-report-pdf.py", line 6, in <module>
connector-export-report-pdf_1  |     from weasyprint import HTML
connector-export-report-pdf_1  |   File "/usr/local/lib/python3.9/site-packages/weasyprint/__init__.py", line 322, in <module>
connector-export-report-pdf_1  |     from .css import preprocess_stylesheet  # noqa isort:skip
connector-export-report-pdf_1  |   File …
=> [export-report-pdf] Fix_missing_Error_loading_shared_library_pango-1.0-0

external-import/kaspersky/src/kaspersky/client.py, external-import/kaspersky/src/kaspersky/importer.py, external-import/kaspersky/src/kaspersky/utils/yara.py
The Kaspersky connector has a lot of logs as `info`, making it really verbose. 
* Switch some of the `info` logs as `debug` to avoid generating that much logs in production. 
N/A
- [] I added/update the relevant documentation (either on github or on notion)
- [] Where necessary I refactored code to improve the overall quality
=> [kaspersky] switch some logs to debug to reduce verbosity

external-import/mandiant/src/mandiant.py
* replace name for value when importing indicators using the /v4/indicators endpoint for the Mandiant connector
* #694
=> replaces name for value and resolves 694

internal-enrichment/virustotal/src/virustotal/virustotal.py
* Confidence level should be treated as a number
* #709
=> [virustotal] set confidence level as a number

external-import/misp/src/misp.py
Since version 5.3.5, the creation of the relationship id uses a value that can be `None`. 
Example of error (row number might not match): 
```
Traceback (most recent call last):
{{ File "/opt/opencti-connector-misp/misp.py", line 2038, in <module>}}
{{ mispConnector.run()}}
{{ File "/opt/opencti-connector-misp/misp.py", line 380, in run}}
{{ event_timestamp = self.process_events(work_id, events)}}
{{ File "/opt/opencti-connector-misp/misp.py", line 632, in process_events}}
{{ indicator = self.process_attribute(}}
{{ File "/opt/opencti-connector-misp/misp.py", line 1235, in process_attribute}}
{{ "related-to", object_observable.id, observable.id}}
AttributeError: 'NoneType' object has no attribute 'id'
Killed 
```
* Fix the creation of the id to avoid crashing the connector
* ~~Few changes …
=> [misp] fix NoneType on observable

internal-enrichment/ivre/src/config.yml.sample
All of the above parameters are mandatory, and I believe this makes more sense when first configuring the connector
* IVRE Default Config 
* N/A
I feel this makes the generic sample config more usable and less ambiguous
=> Update to the sample config for the IVRE connector

external-import/cve/docker-compose.yml, external-import/cve/src/config.yml.sample, external-import/cve/src/cve.py
* Implement a variable CVE historical start date to avoid ingesting CVE data from previous years that are not relevant
*
* N/A
- [ x ] I consider the submitted work as finished
- [ x ] I tested the code for its functionality using different use cases
No further comments, the change is minor.
=> Adding variable Start Date for NVD CVE Feeds

external-import/misp-feed/src/config.botvrij.yml.sample, external-import/misp-feed/src/config.circl.yml.sample, external-import/misp-feed/src/config.threatfox.yml.sample
***Update***: Added 3 sample `config.yml` files. The platform admin can decide how they'd like to deploy the local copies of `misp-feed` to consume whatever feeds that they want to consume.
<strike>Modify `external-import/misp-feed/src/misp-feed.py` so that it will read the `config.yml` from the current working directory, rather than trying to find the one that is located in the same folder as the `misp-feed.py` script.
Add three subdirectories to the misp-feed `src/` folder that contain config templates for the following MISP-format feeds:
* https://www.circl.lu/doc/misp/feed-osint
* https://www.botvrij.eu/data/feed-osint
* https://threatfox.abuse.ch/downloads/misp/
A proposal for the use would be to (more or less) run each like this:
```sh
cd …
```
=> Add 3 default MISP feeds: CIRCL, ThreatFox, Botvrij

external-import/misp-feed/src/misp-feed.py
I found a very very easy typo of environment name in parsing config variables and I propose a PR to fix it.
- actual: MISP_FEED_MPORT_FROM_DATE
- expect: MISP_FEED_IMPORT_FROM_DATE
Let me know if this PR is good for you.
* Fix a typo of environment name in the parsing config section.
=> [misp-feed] An easy typo of environment name is exists in the block of parsing config variables 

external-import/cyber-campaign-collection/src/cyber-campaign-collection.py
When a date is extracted from the report filename, this attempts to determine if the month and day fields are sane numeric values. If not (such as '00' or 'XX'), the connector will now simply default to '01' for the malformed field.
The current code, when it encounters such a parsing failure, will throw an exception and exit, handling it semi-gracefully. However, the connector will not register where it left off, and it will start processing all of the successful reports from the first report again, adding all of the duplicate import work into the worker queue, in a permanent loop. I was able to test this successfully on all of the work items starting from year `2014` on up.
=> Bugfix: cyber-campaign-collection crashes when date fails parsing, infinite loop adding earlier items to queue forever

external-import/misp-feed/src/misp-feed.py
[Flashpoint](https://flashpoint.io/) provides their CTIs as MISP-Feed and we want to include them.
But the structure of the json file for each event (introduced as `<event_id>.json` )  is DictArray such as `[ {"Event": ...} ]`  and we caught below shortened traceback with additional survey.
```
File "/path/to/misp-feed.py", line xxx, in <module>
id=Identity.generate_id(event["Event"]["Orgc"]["name"], "organization"),
TypeError: list indices must be integers or slices, not str
```
The location of above exception is https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/misp-feed/src/misp-feed.py#L1441
1. Check if the json of each event is list or not
2. Get one row if it is a list and the length is 1
3. Raise exception if it is a list and the length is not 1
- this …
=> [misp-feed] Cannot parse feed of the Flashpoint API

external-import/cisa-known-exploited-vulnerabilities/src/main.py
* Ensure vuln_id and org_id are assigned when a new vulnerability and infrastructure object are created by the connector.
* #843
=> [cisa-known-exploited-vulnerabilities] Fix unknown IDs (#843)

internal-enrichment/intezer-sandbox/src/intezer_api.py, internal-export-file/export-report-pdf/README.md, internal-export-file/export-report-pdf/docker-compose.yml, internal-export-file/export-report-pdf/src/export-report-pdf.py, internal-export-file/export-report-pdf/src/resources/threat-actor.css.template, internal-export-file/export-report-pdf/src/resources/threat-actor.html
* Handle the export of Threat Actor entities to PDF
* Fix issue where Intrusion Set entity reports missing Originates From, see changes to `internal-export-file/export-report-pdf/src/resources/intrusion-set.html`
* Fixed the intezer sandbox connector (minor change, can implement in another PR if needed)
These changes were made in order to allow exporting Threat Actors to PDF, as currently the connector only handles Intrusion Set and Report entities.
=> [ExportReportPDF] Export Threat-Actor Entities

internal-enrichment/shodan-internetdb/README.md, internal-enrichment/shodan-internetdb/docker-compose.yml, internal-enrichment/shodan-internetdb/src/config.yml.sample, internal-enrichment/shodan-internetdb/src/shodan_internetdb/config.py, internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
* Remove SHODAN_CREATE_INDICATOR, nothing about the shodan enrichment specifies maliciousness, an indicator should not be created by this.
* Add the enrichment as a note, instead of description hacking. Updating a description, even with appending the enrichment was a messy proposition to begin with. 
* None
Searching works relatively well, you'd just need to pivot from the note back to the observable if that's what was in the results.
Abstract:
```
Shodan InternetDB Enrichment of 8.8.8.8
```
Content:
```
Shodan InternetDB:
------------------
Hostnames: 
- dns.google
------------------
Software: n/a
------------------
Vulnerabilities: n/a
------------------
Ports: 
- 53
- 443
------------------
```
=> [shodan] remove indicator, enrich as a note

external-import/crits/.dockerignore, external-import/crits/Dockerfile, external-import/crits/README.md, external-import/crits/docker-compose.yml, external-import/crits/entrypoint.sh, external-import/crits/src/config.yml.sample, external-import/crits/src/crits.py, external-import/crits/src/requirements.txt
This is intended to be a connector that will fetch data from an external CRITs (https://crits.github.io) instance, and import it into OpenCTI. Similar to the existing `external-import/misp` connector. **This is a work in progress**.
* Add a new `external-import` connector named `crits` which will import data from a CRITs instance (https://crits.github.io)
This is a work in progress, but I wanted to publish a PR on the feature branch early in the development process so that discussion could happen here, as well as awareness. I've used the CRITs platform for over 10 years, and while it was a great platform at the time, its front-end is largely based upon an outdated approach to web application development, it is not compatible with Python 3, where it uses STIX it uses STIX 1.x, and it is no …
=> Add a CRITs external-import connector

external-import/misp/src/misp.py
Just a quick fix even though as a high impact.
Connectors code really need some love, functions with 400 lines of code...
=> Fix wrong return misp connector

internal-enrichment/shodan/src/shodanImport.py
* Switch Subject and Issuer when creating new X.509 certificate Observables, which were accidentally backwards
N/A
=> Fix X509 Subject and Issuer in Shodan enrichment

external-import/misp/README.md, external-import/misp/docker-compose.yml, external-import/misp/src/config.yml.sample, external-import/misp/src/misp.py
This new config option will allow a user to set a attribute filter in order for the MISP connector find the right value to use as Report description.
=> Added report description attribute finder in MISP connector

external-import/misp/README.md, external-import/misp/docker-compose.yml, external-import/misp/src/config.yml.sample, external-import/misp/src/misp.py
Added capability to choose to add MISP tags as labels. Some MISP events from certain sources provide tags that are not relevant, therefore, with this option, a user can choose if want those tags to be added as labels (like is already doing by default) or not.
=> Add capability to choose to add MISP tags as labels

external-import/misp/src/misp.py
Capability handle UN M49 regions from MISP galaxy. It will automatically create the regions if they don't exist. These are the same region names used by OpenCTI-Platform/datasets, therefore, if an user already have the dataset ingested, the misp connector will only create the relationships.
=> Added capability to handle Regions M49 galaxy from MISP

.circleci/config.yml, internal-enrichment/domaintools/.dockerignore, internal-enrichment/domaintools/.gitignore, internal-enrichment/domaintools/Dockerfile, internal-enrichment/domaintools/README.md, internal-enrichment/domaintools/docker-compose.yml, internal-enrichment/domaintools/entrypoint.sh, internal-enrichment/domaintools/src/config.yml.sample, internal-enrichment/domaintools/src/connector/__init__.py, internal-enrichment/domaintools/src/connector/builder.py, internal-enrichment/domaintools/src/connector/constants.py, internal-enrichment/domaintools/src/connector/core.py, internal-enrichment/domaintools/src/main.py, internal-enrichment/domaintools/src/requirements.txt
Add DomainTools as a new enrichment connector. The connector can be triggered on `domain-name` and `ipv4-addr`. 
Depending on the information retrieved, the following observable types might be created: 
- `domain-name` 
- `ipv4-addr`
- `email-addr`
- `autonomous-system`
* Add a new enrichment connector: domaintools
* #910
=> [domaintools] add enrichment connector

stream/splunk/README.md, stream/splunk/src/splunk.py
* Using token (JWT) for Splunk authentication: this is a more standard way to authenticate to Splunk API and it avoids using raw credentials without adding complexity in the code. 
* Sanitize KV store keys: the connector cannot process indicators like `[file:hashes.'SHA-256' = 'xyz']` because KV store keys cannot contain `.`. Also, unusual characters like `'` make usage of these keys less convenient when writing Splunk queries. I proposed in this PR to replace `.` by `:` and to remove single quotes.
* Ignore some entity types: the `splunk_ignore_types` var was already defined but not used. I just added a simple condition ignoring types provided in this var. 
I didn't create any issue related to these changes.
=> [splunk] Use JWT for Splunk auth, sanitize kvstore keys, ignore some entity types

internal-enrichment/virustotal/src/main.py, internal-enrichment/virustotal/src/virustotal/virustotal.py
* Add delay if connector fails to start because it can't make a connection to the OpenCTI platform (following the template's example)
* When VirusTotal connector had auto-enrichment enabled, if a large artifact file was uploaded, it took a few seconds to finish uploading to OpenCTI and propagate through the system. The VT connector would fail with a list index exception when looking for the "importFiles" list. Adding a small delay and updating the observable variable allows for that propagation time to complete before moving on with the process.
- Tested with multiple file sizes
- Tested with bringing services up slowly
=> VirusTotal fixes

external-import/urlscan/src/urlscan/connector.py
* urls started coming in prefixed by `blob:`, breaks url parsing
* #960
=> [urlscan] Fix blob urls

external-import/vxvault/src/vxvault.py
Fixing #973 and #974 - connector imports garbage data and leaves trailing `\n` characters in the name and value field of indicators and observables.
I propose a simple fix for both issues, keeping changes to a minimum. The author of the source data has adjusted the format of the data slightly (https://twitter.com/GraemeMeyer/status/1613900217434230788?s=20), and this PR accounts for that.
* Strip (trim) all values before import to remove leading and trailing whitespace characters
* Check against accidentally importing HTML tags and blank/whitespace events as indicators/observables
* #973 
* #974 
- [N/A] I added/update the relevant documentation (either on github or on notion)
- [N/A ] Where necessary I refactored code to improve the overall quality
This is my first PR for the project, so …
=> [VXVault] - Fix #973 and #974 - connector imports garbage data

external-import/misp/src/misp.py
* Fix resolve_markings method to take into account uppercase tags in MISP.
=> Fix method to take into account uppercase tags

external-import/ironnet/src/ironnet/config.py
* The create_ip_indicators config option was half-broken, it was duplicating the IRONNET_CREATE_INDICATORS env var.
* n/a
=> [ironnet] Fix IP indicator config option

internal-enrichment/virustotal/docker-compose.yml, internal-enrichment/virustotal/src/config.yml.sample, internal-enrichment/virustotal/src/requirements.txt, internal-enrichment/virustotal/src/virustotal/client.py, internal-enrichment/virustotal/src/virustotal/virustotal.py
* Make the VirusTotal connector async
* Remove the wait for artifact analysis completion flag since it's async
* Add support for uploading unseen URLs to VT
=> [VirusTotal] Connector async and added url upload

internal-enrichment/virustotal/src/virustotal/builder.py
* Bugfix to ignore empty categories returned by VT
=> [VirusTotal] Ignore empty categories

stream/elastic/elastic/sightings_manager.py, stream/elastic/pyproject.toml
Made the signal import compatible with ECS8.0 alerts.
*  distingusih between the two alert formats "<= 7.17" and ">= 8.0.0"
=> Connector-Elastic - ECS 8.0.0 compatibility

stream/elastic/elastic/import_manager.py, stream/elastic/elastic/stix2ecs.py
A few changes. 
* Fixed the bug with the wildcard mentioned in the issue below. 
* Fixed the error when entity delivered by OpenCTI server is "none"
* Made the exception clearer that is thrown when unknown STIX attributes are encountered. This makes debugging easier. 
* https://github.com/OpenCTI-Platform/connectors/issues/983
Code is tested in our production envorinment.
=> Connector-Elastic - index pattern is used wrongly

stream/elastic/Dockerfile
In our Kybernetes-setup, the connector-elastic container did not terminate itself if the module pycti tries to reset itself on connection interupt (e.g., when restting the connector via GUI). 
The pycti module throws "SIGTERM" to terminate the process. That, however, does not work as the process is the primary process within the container and the SIGTERM signal is not sent to the process. This also because the connector-elastic process is multi-threaded. 
We solve this by including "tini" spawing the connector python process. This may also be applicable to other connectors. 
* introducing a tini abstraction layer when starting the container
*
=> Connector-Elastic - allowing self-termination

stream/elastic/elastic/import_manager.py
The datetime module used in the connector-elastic connector requires the floor() method on timestamps which is not provided by datetime. 
* changed datetime to arrrow. No additional python modules required as datemath already loads arrow internally.
=> Connector-Elastic - datemath requires arrow instead of datetime  

external-import/abuse-ssl/src/abuse-ssl.py
The connector "abuse-ssl" formats a STIX attribute wrongly. 
See: http://docs.oasis-open.org/cti/stix/v2.0/cs01/part4-cyber-observable-objects/stix-v2.0-cs01-part4-cyber-observable-objects.html#_Toc496716225
* connector-abuse-ssl: fixed STIX-attribute string ipv4 -> ipv4-addr
=> Connector Abuse-SSL - fixed STIX attribute string: ipv4 -> ipv4-addr

external-import/misp-feed/src/misp-feed.py
* setting `Attribute` key to an empty array if it doesn't exist
* #1008
=> setting Attribute key to empty array if not present

internal-export-file/export-file-csv/src/export-file-csv.py, internal-export-file/export-file-stix/src/export-file-stix.py, internal-export-file/export-file-txt/src/export-file-txt.py
By default, only filters and search keywords are taken into account during the export : selecting individual entities via the checkboxes is not taken into account by the list export functions.
Steps to create the smallest reproducible scenario:
1. Select multiple observables / indicators via the check boxes
2. Open the export panels and export to CSV or JSON
3. Returned format includes all observables or indicators, not the entities selected
When we select some entities via checkboxes, the file export should only contain those entities (=entities that are checked + respect the current filtering).
If no entities are selected: the workflow stay the same as it is
- txt exports (except for relationships and single entities)
- csv exports
- stix exports …
=> Export only selected entities (#1741)

stream/elastic/README.md, stream/elastic/config.reference.yml, stream/elastic/elastic/conf.py, stream/elastic/elastic/console.py, stream/elastic/elastic/import_manager.py, stream/elastic/elastic/sightings_manager.py
The current connector-elastic module requieres the "manage" cluster privilege on its target Elasticseach instance. In case ILM or index-templates are not deployed, these privileges are not required as well. The connector, however, does a few actions that lead to aborting when not permitted the elevated rights. 
This pull-request adds an additional flag `output.elasticsearch.reduced_privilege` to the configuration that disables these additional actions and allows for tailoring the access to a specific index only. 
* adding the flag `output.elasticsearch.reduced_privilege` to the configuration in defaults, config.yaml and env-variables
* disable the elastic_helper.ping() method that requieres "manage" cluster privileges.
* Extending the README accordingly. 
* Fixing a but where the variable …
=> Connector-Elastic - allowing less privileged Elasticsearch access

stream/elastic/elastic/sightings_manager.py
The sightings-manager importing sightings from Elasticsearch can throw an unhandled error and stop working while other threads in the connector keep running. 
This patch allows the sightings-manager thread to throw a SIGTERM, identically to the helper module in pycti: https://github.com/OpenCTI-Platform/client-python/blob/7a65e478709bcd86b5a528225ec19ab5ede5af45/pycti/connector/opencti_connector_helper.py#L36
This allows to spot problem with the setup on a container overview without looking into the specific container logs. 
The diff looks huge, but actually it is just adding four lines for try-and-except and intending the full block within.
* putting the full sightings_mangager run-loop in a try-catch block that allows to end the programm when an unhandled exception is thrown by the …
=> Connector-Elastic - allow sightings-manager to restart the container 

internal-export-file/export-file-csv/src/export-file-csv.py, internal-export-file/export-file-txt/src/export-file-txt.py
when exporting a location (country, adminstrative area..) in txt: error, list empty
https://github.com/OpenCTI-Platform/opencti/issues/2821 (bug 3)
=> [connectors] Txt location export bug fix (#2821)

internal-import-file/import-file-stix/Dockerfile, internal-import-file/import-file-stix/src/requirements.txt
* Add `numpy==1.24.2` to the `requirements.txt` of the `import-file-stix` connector
* Install the `gfortran`, `musl-dev`, `g++`, `openblas`, and `openblas-dev` alpine packages, which provide necessary build dependencies for `numpy`. In the case of `openblas`, it is necessary because otherwise it defaults to a very slow BLAS implementation.
* Does not completely solve #941 but addresses one of the issues encountered
=> [import-file-stix] Add numpy to requirements.txt and install build dependencies

internal-enrichment/shodan-internetdb/Dockerfile, internal-import-file/import-file-stix/Dockerfile
* Add `musl-dev`, `libffi-dev`, and `gcc` to the `build` container for the `shodan-internetdb` connector, as these missing was causing it to fail to build successfully in my environment
* Remove the `openblas` from the `apk del` command in `import-file-stix` because `numpy` may need this lib at run-time, or fail unexpectedly on some features
* Fix a missing newline at the end of the file in `shodan-internetdb`'s `Dockerfile`
=> Update build dependencies for shodan-internetdb, import-file-stix

internal-enrichment/hygiene/src/hygiene.py, internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
The `hygiene` and `shodan-internetdb` enrichment connectors were pulling down the entirety of the observables that they operate on, despite only using a small number of those fields. One major consequence of this approach is that these `read()` requests would cause OpenCTI to perform an S3 ListObjectsV2 operation each time the `read()` was called, which could amount to 100's or 1000's of attempts. As the LIST requests in AWS are 10x more expensive than the GET or HEAD requests, this easily caused S3 costs to be more expensive than EC2 costs, when using enrichment connectors like these.
An added benefit is that this change eliminated a lot of latency that previously existed in performing these operations, which speeds up the connectors, too.
* Limit data requests for `hygiene` to exactly …
=> Optimize SDO .read() operations in [hygiene] and [shodan-internetdb] enrichment connectors

external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py, external-import/urlhaus/src/urlhaus.py
In the stix_domain_object read operation, don't fetch fields that won't be used by the connector.
* Only fetch `id`, `standard_id`, and `entity_type` when performing a `stix_domain_object` `read()` operation. This will prevent attempts to perform LIST operations against S3 buckets when those results won't be used
* Only fetch `id` and `entity_type` when performing an existence test using `read()` in `malwarebazaar-recent-additions`
* Same problem as #1028 just found in another connector
=> [urlhaus] & [malwarebazaar] Minimize data from SDO read() operation

stream/sentinel/src/sentinel.py
Update to the Sentinel Connector to address one issue found with timedelta and accounting only for valid Sentinel IOCs supported by the API.
Updated the connector to account for:
* Coverting expire_time to int to account for timedelta being a string and failing when using docker-compose
* Limiting oauth request to only being created on valid IOC events to prevent excessive oauth requests
* Creation events that are only supported valid IOCs for the Sentinel API
* https://github.com/OpenCTI-Platform/connectors/issues/1023
=> Update Sentinel connector

internal-import-file/import-document/src/requirements.txt, internal-import-file/import-file-stix/src/requirements.txt
* Update Python dependency versions of `beautifulsoup4`, `pdfminer.stix`, `ioc-finder`, `dateparser` and add missing dependency `chardet` for `import-document` connector, to latest versions
* Update `stix2-elevator` for `import-file-stix` connector to latest version
These newer versions add some improved performance as well as some reported bug fixes, compared to the versions the project uses today. I have been doing various tests with the PDF import feature in order to iron out some bugs that I've encountered, and this is the byproduct of some of that testing. I am still seeing some errors with import, but these changes appear to have cleared a few of the common `import-stix-file` connector-reported bugs. As well, the fixes in the newer ioc-parser library should make it faster, as well …
=> [import-document] [import-file-stix] Update version of dependencies

external-import/urlhaus/src/urlhaus.py
The connector-urlhaus has been sped up by implementing the following additions: 
* URLHAUS_INTERVAL can now also be a float, allowing the connector to run more often than once a day. 
* a simple caching procedure of threats. Instead of asking opencti for every threat individually, identical requests are now cached. It is now 98% faster. 
* instead of parsing and uploading the full csv file to opencti, the newest entry timestamp is saved and only the new entries are processed.
* seamless upgrade from old connector state to the new one.
* every 5000k processed entries, a notification is printed to the info log. 
* errors output now a stacktrace, simplifying debugging. 
*
=> Connector-Urlhaus -- Caching and state output

external-import/taxii2/src/taxii2.py
This fix is to address the connectors compatability with taxii 2.1. When I added pagination in release 5.7.0, I was only able to test with a taxii 2.0 server and I had assumed that taxii 2.1 still would send the data as a bundle to the client. Upon getting access to a taxii 2.1 server, I realise this is not the case.
If using the 5.7.0 version of the client and a taxii 2.1 server, you will receive the following error:
File "/opt/opencti-taxii2/taxii2.py", line 150, in run
self.poll_all_roots(coll_title)
File "/opt/opencti-taxii2/taxii2.py", line 189, in poll_all_roots
self.poll_entire_root(root)
File "/opt/opencti-taxii2/taxii2.py", line 221, in poll_entire_root
self.poll(coll)
File "/opt/opencti-taxii2/taxii2.py", line 257, in poll
bundleid = response["id"]
KeyError: 'id'
Terminated
This …
=> [taxii2] Fixed bug for compatibility with taxii 2.1

internal-enrichment/google-dns/.dockerignore, internal-enrichment/google-dns/Dockerfile, internal-enrichment/google-dns/README.md, internal-enrichment/google-dns/docker-compose.yml, internal-enrichment/google-dns/src/client.py, internal-enrichment/google-dns/src/config.yml.sample, internal-enrichment/google-dns/src/main.py, internal-enrichment/google-dns/src/requirements.txt, internal-enrichment/google-dns/tests/test_client.py
- Add a new connector that enriches Domain Name Observables using the [Google Public DNS API](https://developers.google.com/speed/public-dns/docs/doh/json)
- Supports these query types:
- NS: creates Domain Names
- A: creates IPv4 Addresses
- CNAME: creates Domain Names
- MX: creates Domain Names
- TXT: creates Texts
- Between the enriched Domain Name and any additional Observables representing query results, the connector creates "resolves-to" Relationships and notes the type in its description. This is based on the DomainTools connector.
N/A
=> Introduce the Google DNS connector

external-import/taxii2/README.md, external-import/taxii2/docker-compose.yml, external-import/taxii2/src/taxii2.py
Add the ability to add a custom label to an indicator/observable/incident.
The reason why I need this is due to sharing observables which have indicators from multiple sources.
If I want to share an observable from a particular feed, I have been filtering by author in the past, but if another author generated the observable, then the indicator will not be shared.
So by creating a label for each of my taxii feeds and creating a filter based on the label, I am able to share the observables without any being missed out
=> [Taxii2] Custom labels

internal-enrichment/shodan-internetdb/src/shodan_internetdb/connector.py
Should fix #1109, as the key has changed from `value` to `observable_value`
* Change observable key from `value` to `observable_value`
* #1109 
I tested the gq query in a repl to check the structure of the observable, full connector has not been tested from start to finish.
=> Update shodan-idb connector

external-import/mandiant/README.md, external-import/mandiant/docker-compose.yml, external-import/mandiant/src/config.yml.sample, external-import/mandiant/src/mandiant.py
This PR is to fix the bug I created when implementing mscore.
What started off as a bug fix turned into multiple after I was unable to test my original changes effectively.
1) Fixed issue with callers not being updated when mscore was first introduced.
2) Changed import_start_day to be days_before_start to make configuration easier.
3) Mandiant requires next to be the only parameter if it is being used.
4) Next parameter now equals variable from response. This was hard coded as None. This fixes a lot of the end_epoch being in the future issues.
5) Mandiant doesn't provide next in the response if there is no next page. Added no_more_result = True
6) Current_state now equals the time it was initially run for vulnerability, indicator and report.
7) I changed the limits to the defaults, I did …
=> [Mandiant] Bug fix for mscore implementation

internal-enrichment/google-dns/src/main.py
* Use `customAttributes` in the SDO read against Domain Name observables
This implements the same optimization I made in #1028 and #1031 that prevents the `self.helper.api.stix_cyber_observable.read(...)` call from querying any existing related artifact objects from the MinIO/S3 backends. In addition to speeding up the overall query, this also prevents an expensive `LIST` operation when using AWS S3 for object storage.
* #1031 
* #1027
=> [google-dns] Optimize SDO read to not query Minio/S3

external-import/taxii2/src/taxii2.py
This pagination method relies on having a manifest available so an accurate date added can be retrieved and used to poll for further indicators. But it turns out not all Taxii servers return a manifest. Unfortunately the 3 Taxii servers I have access to, have a manifest, so it is hard for me to provide a workaround. So what I have done is moved the version variable to before the while loop (in case there is no data) and have made a way to exit the loop if the manifest is zero in size. So now it won't crash anymore and will continue to send the bundle to OpenCTI, but will only run once, like previous connector versions. 
https://github.com/OpenCTI-Platform/connectors/issues/1123
I know the team is working on a Taxii client built into the platform, so users might have to wait for this to …
=> [Taxii2] Bugfix for no manifest available

stream/splunk/README.md, stream/splunk/docker-compose.yml, stream/splunk/src/config.yml.sample, stream/splunk/src/requirements.txt, stream/splunk/src/splunk.py
Hi, 
I create this PR to open a discussion on the current Splunk connector and its use on a production environment.
We faced several operational issues and are proposing solutions for each of them:
**1. Removing the "1 connector for multiple Splunk" feature**
The current version is able to push an entity to multiple Splunk, it allows to mutualize enrichment CPU usage.
However, it leads to inter-dependencies between Splunk instances. An issue with the first configured Splunk instance can impact the second one. Also, as OpenCTI / Splunk A and the OpenCTI / Splunk B share the same state internally, it is easy, when an incident occurs on Splunk A or B to get an inconsistent state.
It is actually way more simple and reliable to have on connector per Splunk instance. It also simplifies the code …
=> Refactoring of Splunk connector: various structural improvements

external-import/abuse-ssl/docker-compose.yml
Comment documenting units used for abuse-ssl interval - most connectors document with a comment what unit the interval field uses (seconds, days etc.), but this one was missing.
This just adds a comment that explains that the abuse_ssl connector's interval is in minutes.
=> Comment documenting units used for abuse-ssl interval

external-import/cve/src/cve.py
Change working directory to a subdirectory: /opt/opencti-connector-cve/tmp
Allows this directory to be mounted separately with write privileges.
Container as is cannot be run without special privileges to allow writing and processing the downloaded file in /opt/opencti-connector-cve.
- [ x] I consider the submitted work as finished
- [ x] I tested the code for its functionality using different use cases
- [ x] I added/update the relevant documentation (either on github or on notion)
- [ x] Where necessary I refactored code to improve the overall quality
This should have zero effect on anyone using this currently with root privileges. This simply allows users to create and mount a directory separately if they so choose.
=> moved working directory to /tmp

external-import/virustotal-livehunt-notifications/src/virustotal-livehunt-notifications.py
The virustotal-livehunt-notifications connector does not link the author (identity object) to the newly created objects, making it difficult to see which objects are created by the connector. 
* Add the author when creating objects with the virustotal-livethunt-notifications connector
* N/A
Before: 
After:
=> [vt-livehunt] add author to created objects

template/Dockerfile
* Bump docker alpine python from 3.10 to 3.11
* According to https://docs.python.org/3/whatsnew/3.11.html  "Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite." and "When printing tracebacks, the interpreter will now point to the exact expression that caused the error, instead of just the line".
=> Bump to alpine python 3.11

stream/elastic/README.md, stream/elastic/config.reference.yml, stream/elastic/elastic/conf.py, stream/elastic/elastic/elastic.py, stream/elastic/elastic/import_manager.py, stream/elastic/elastic/sightings_manager.py
* added ability and configuration abilities to push indicator labels on the ElasticSearch database, if enabled. The newly introduced configuration flag 'include_labels' allows for enabling this feature, defaults to false. 
* added a new mode 'ecs_no_signals' that allows the connector to run in 'ecs' mode without signals importing enabled. This is useful, for example, if two Elastic connectors are running for the same ElasticSearch database but the sightings should be imported only by one of them. 
* reverted the changes for the Elastic connector in PR1132 (https://github.com/OpenCTI-Platform/connectors/pull/1132). The mentioned administrator privileges where exactly the reason, I introduced the flag. Moreover, the changes by PR1132 break the connector if low privileges are required (the …
=> Connector Elastic - new features and bugfixes

external-import/cve/src/cve.py
I've amended a couple of lines to rectify the filepath being written to (to be /tmp/), as in it's current state, the connector does not work properly.
https://github.com/OpenCTI-Platform/connectors/pull/1174
One of the previous pull requests ( #1174 ) looked to have the data files stored and processed in /opt/opencti-connector-cve/tmp/ directory. However, the majority of the lines amended in that request actually made reference to the absolute path of /tmp/, rather than the /opt/opencti-connector-cve/tmp/ path that was intended. 
However, due to /tmp/ being globally writeable by default, it works just as well as a solution to the original problem. This is a request to amend the two lines that do not actually make reference to /tmp/ to bring them in line with the rest of the changes.
#1174 …
=> Rectified non absolute /tmp/ path

external-import/tweetfeed/src/tweetfeed.py
Fix, stix pattern type unsopported in some openCTI instance
* Fixing the running schedule issue
* Fixing the "pattern_type" key during indicator creation, it was changed from "stix2" to "stix", this should fix some compatibility issues.
* //
* //
=> [TWEETFEED CONNECTOR]

external-import/mandiant/src/mandiant/actors.py
Our Mandiant subscription seems to redact some fields. These fields are not empty (i.e., key does not exists) but contain a string "redacted". This leads to failure in the connector-mandiant code as some fields are expected to contain lists, which Python strings can be addresses as, but further processing fails. 
This patch catches these cases. In our setup, the connector now runs without error. 
* sanitizing the reading of certain properties
*
=> connector-mandiant - catch 'redacted' entries in actor data-struct

template/src/main.py
* Update a link in the connector template's code comments to point to the new location of dev docs
N/A
Docs moved from Notion to `docs.opencti.io`
=> Update link to connector dev docs in template

external-import/riskiq/src/riskiq/client.py, stream/virustotal-livehunt-rules/src/client.py
The RiskIQ connector is not working, having the following error: 
```
"Retry.__init__() got an unexpected keyword argument 'method_whitelist'"
```
This occurs since the commit of the renovate bot, that upgraded `urllib3` to v2 and the `method_whitelist` argument has been removed since v2.
I changed the argument name in the `stream/virustotal-livehunt-rules` connector as well to avoid a similar issue. 
*  Replace `method_whitelist` by `allowed_methods`
* Linked to the same issue for the VirusTotal enrichment connector: #1276
=> [connectors] replace `method_whitelist` by `allowed_methods`

external-import/misp-feed/src/misp-feed.py
* Skip the galaxy without namespace instead of failing completely
* Log the error with the helper when the runer encounters an exception
N/A
=> [misp-feed] Ignore galaxy with missing namespace instead of failing completely

external-import/misp-feed/src/misp-feed.py
* threat_level_id is not required, so it shouldn't break the connector if one event is missing it, we can default to "Undefined"
N/A
=> Misp feed/unknown threat level

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py
* Add the hash of the file that triggered the alert in the name
* Add external reference to VT on file
* Check if an alert with the same name exists before creating it
* Fix some `valid_from` dates that are not valid (month not between 1..12)
=> [vt-livehunt] add file hash in alert name

external-import/taxii2/src/config.yml.sample, external-import/taxii2/src/taxii2.py
I've allowed Taxii2.1 feeds to use the next parameter.
Duplicate code has been added to a function.
I simplified some code so it was a bit cleaner.
I've tested on my Taxii 2.0 and 2.1 servers.
https://github.com/OpenCTI-Platform/connectors/issues/1298
Thanks to @mpatrini7 for the inspiration :-)
=> [Taxii2] Enabling Next Parameter for Taxii2.1 Feeds

external-import/taxii2/src/taxii2.py
I have added code to enumerate the x_opencti_main_observable_type field. Users will now be able to filter on the main observable type from the Indicators view. It also allows them to share indicators by their observable type.
This is done by running regex on the pattern to extract the observable type. Have tested this on a Taxii 2.0 and Taxii 2.1 feed and it works fine.
Please note: If the pattern has multiple indicators in it, the regex will extract the first entry. I couldn't think of a better way to do this as we are unable to prompt the user for what they would like it to be.
=> [Taxii2] Enumerated main observable type

external-import/feedly/src/feedly/opencti_connector/connector.py, external-import/feedly/src/requirements.txt
* The STIX exports we generate from Feedly now have a description in markdown instead of html, so we can skip the markdownify step
=> [feedly] (update) Report descriptions are now in md

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py, external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py
* Remove the snippet from the description of the alert and add the date of the notification
* Remove the id of the vt object and the filtered tag from the labels of the alert
* Set a default for the minimal number of positives
* N/A
=> [vt-livehunt] modification of alert description and labels

external-import/urlhaus/src/urlhaus.py
Problem: most exceptions were generically caught and their stacktrace printed via the logger helper. The connector, however, was not terminated but let running.
This lead to issues when the opencti api helper failed due to "ConnectionResetError: [Errno 104] Connection reset by peer" (the connection to opencti) or similar occurings and did not recover itself. The connector halted its functions but kept running, requireing an inspect and a manual restart of the container. 
Therefore, I have simplified the exception handling of the connector significantly, see proposed changes. 
* first, removing all exception handlers
* then, adding a generic exception handlers around the run function, catching all exceptions, printing the stacktrace and then terminating the execution, leading to a restart …
=> [connector-urlhaus] exception handling clean-up

stream/splunk/README.md, stream/splunk/docker-compose.yml, stream/splunk/src/config.yml.sample, stream/splunk/src/splunk.py
https://github.com/OpenCTI-Platform/connectors/issues/1386
amend payload sent to splunk kvstore because it is not STIX friendly to extract fields from extension-definition-UUID
* extract several fields from extension-definition-UUID, such as:
* created_at
* updated_at
* score
* labels
* is_inferred
* get rid of extensions since it is no longer needed once the above fields have been added to the payload
* amend readme with some guidelines how to leverage the opencti kvstore on splunk
* issue-1386
Related issue-1386 mention few more changes that I decided not to implement because I found those changes not so relevant since we can define different lookup definition per type. Among those mentionned changes that are not part of of this PR are (1) normalization of type=file by leveraging the …
=> Connector splunk/issue-1386/kvstore friendly format instead of stix

external-import/restore-files/src/restore-files.py
* add missing test for `find_element` result like [there](https://github.com/OpenCTI-Platform/connectors/blob/2a5c0891e695aa5b5b4a08204918fe8d1d883be8/external-import/restore-files/src/restore-files.py#L121)
* Closes #842
There was no test for `find_element` result and changes are fixes it.
=> fix restore-files connector bug `AttributeError: 'NoneType' object has no attribute 'keys' `

internal-enrichment/yara/src/main.py
Since an Indicator can have `importFiles` associated with it, when the list call is performed to get all Indicators that match the `pattern_type="yara`" filter, it also attempts to retrieve any `importFiles` or `exportFiles` (by performing an S3 LIST operation), but the results of this will never be used. In fact, the yara connector only cares about `id`, `standard_id`, `pattern`, `name`, and `pattern_type`. 
This change limits the Indicator `list()` request to fetch only the fields: `id`, `standard_id`, `pattern`, `name` and `pattern_type`. This ensures that OpenCTI never attempts a S3 LIST operation. This drastically speeds up execution, as well as significantly reduces monetary charges when using AWS S3 as the file storage backend.
It is not a complex change, but the version of the …
=> [yara] Use customAttributes to limit overhead of yara sig list() call

external-import/misp/src/config.yml.sample, external-import/misp/src/misp.py
In certain situations, we want to be able to keep labels as they are sent (especially  when they contain special characters).
This PR allows you to configure a list of labels that will be kept as is.
=> [misp] keep as-is configuration option for labels

external-import/comlaude/Dockerfile, external-import/comlaude/README.md, external-import/comlaude/docker-compose.yml, external-import/comlaude/entrypoint.sh, external-import/comlaude/src/comlaude/__init__.py, external-import/comlaude/src/comlaude/requirements.txt, external-import/comlaude/src/config.yml.sample, external-import/comlaude/src/main.py, external-import/comlaude/src/requirements.txt
The Comlaude Connector is designed to integrate with the [Comlaude API](https://api.comlaude.com/docs) to leverage the `Domain Search Endpoint`. This endpoint provides a comprehensive list of all domains within a specified group, along with detailed information for each domain.
* Add new integration for ComLaude to import known domain infrastructure to support SafeLists.
=> Add external-import Comlaude to Connectors.

external-import/thehive/README.md, external-import/thehive/docker-compose.yml, external-import/thehive/src/config.yml.sample, external-import/thehive/src/thehive.py, external-import/thehive/src/utils.py
* Add support for indicator types ipv6, email_address, and email_subject.
* Add support for cve, vendor, supplier, organization, asset, and identity.
* Add support for ipv4 and ipv6 cidrs.
* Add README.
* Fix `KeyError` when the owner is not defined when importing a Task. 
```
{
"timestamp": "2023-10-14T06:16:00.622646Z",
"level": "ERROR",
"name": "pycti.connector",
"message": "Traceback (most recent call last):\n File \"/opt/opencti-connector-thehive/thehive.py\", line 799, in run\n stix_bundle = self.generate_case_bundle(case)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File \"/opt/opencti-connector-thehive/thehive.py\", line 591, in generate_case_bundle\n if task[\"owner\"] == user_mapping_split[0]:\n ~~~~^^^^^^^^^\nKeyError: 'owner'\n"
}
```
The **TheHive Connector** allows for integration of …
=> [thehive] - Add support for new indicator types and fix error when task owner is not defined

external-import/threatfox/src/requirements.txt
Validator module is missing in the 5.11.1 version, causing error on ThreatFox connector.
Add the following line in requirement.txt (latest version)
```
validator==0.7.1
```
=> Python module "Validator" is missing

external-import/threatfox/src/requirements.txt
In my previous commit https://github.com/OpenCTI-Platform/connectors/pull/1489 I made a mistake using "validator" python module (wich exist too)  instead of "valadators" module. Here is a quick fix to solve this issue.
=> Update requirements.txt - Mistake with "validators" module

internal-enrichment/hygiene/src/hygiene.py
Line `160` still refers to `stix_entity["value"]`. Change to `opencti_entity["observable_value"]` like in https://github.com/OpenCTI-Platform/connectors/commit/05356194b9570965fa23b3718732abfb96844bb1. This causes an exception to be thrown when the connector tries to write the logging message.
=> [hygiene] fix hash value report in error message as well

external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py, external-import/malwarebazaar-recent-additions/src/requirements.txt
* Add `stix2` as dependency to `malwarebazaar-recent-additions`
* Mark all artifacts downloaded from MB as `TLP:CLEAR` (within the `stix2` module, this is still referred to as `TLP_WHITE`)
* Details at: #1516 
MalwareBazaar ToS states that all submitters are to consider their uploads `TLP:CLEAR`: https://bazaar.abuse.ch/faq/#tos
=> [malwarebazaar-recent-additions] Mark uploaded artifacts as TLP:CLEAR

external-import/alienvault/docker-compose.yml
[AlienVault] changing the OPENCTI_URL variable to match the default OpenCTI install and also have consistency with other connector default variable.
* The current version corresponds neither to the default value of the OpenCTI installation nor to the default OPENCTI_URL value of the other connectors.
* https://github.com/OpenCTI-Platform/connectors/issues/1404
=> [AlienVault] Changing some value to add a better "out of the box" experience

external-import/virustotal-livehunt-notifications/src/config.yml.sample, external-import/virustotal-livehunt-notifications/src/livehunt/builder.py, external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py
The changes are related to the Virustotal Livehunt connector. More precisely:
* the endpoint used is migrated to a non-deprecated endpoint,
* when alert are generated, the name of the livehunt session as well as the yara's name can be stored as label on the alert,
* the generated sample's description can contain the result per anti-virus used.
By default, not many things are changed. For the changes to be visible, the connector's configuration has to be updated.
=> [vt-hunt] Refine the imported entities and change the endpoint used

external-import/threatfox/src/main.py
* handle both the /full (zipped) and /recent (unzipped) url flavors
* add force_ping after run_and_terminate, just like #1611 
* #1594 
Instead of try/except we could do `data.startswith(b"PK")` or just let the zipfile fail and try failover to csv instead as is committed.
=> [threatfox] handle both /full/ and /recent/ urls

external-import/taxii2/src/taxii2.py
Changed the variable for x_opencti_main_observable_type when a file is used from File to StixFile.
Question asked in Slack.
=> [taxii2] Wrong Observable Type used for File

internal-enrichment/cape-sandbox/docker-compose.yml, internal-enrichment/cape-sandbox/src/cape-sandbox.py, internal-enrichment/cape-sandbox/src/config.yml.sample
* Added a feature to allow users to customize the Cape-Sandbox (Internal Enrichment) connector API URL through environment variables in the Docker container.
* Introduced the environment variable `CAPE_SANDBOX_API_URL` for users to set their desired API URL.
* [Link to any related issues or discussions, if applicable]
This change is designed to enhance the usability and flexibility of the Cape-Sandbox connector by allowing users to easily adapt the API URL to their specific requirements without modifying the code directly. I tested the feature thoroughly and updated the documentation accordingly. Looking forward to your feedback!
=> Feature: Allow Customization of Cape-Sandbox API URL via Environment Variables

external-import/cve/src/services/client/vulnerability.py
The changes proposed here help to address the pagination issues described in #1661. The connector will now detect if the first request yields a total results larger than the page size and will initiate pagination.
The filtering of CVEs for only the CVSS 3.1 CVEs is moved to just prior the function returning and will return this filtered list.
There isn't really a need to calculate or track "pages", so this code will only make use of the start_index and how many items are remaining.
* #1661
The code here will also require the code changes made in https://github.com/OpenCTI-Platform/connectors/pull/1666 which address the API Rate limiting issues
Here is a screenshot of the connector running with the debug output for additional reference
=> [cve] Refactor Pagination (#1661)

external-import/taxii2/src/taxii2.py
* Removed check on "next" value against available collections as "next" does not have to be a collection ID, according to the TAXII 2.1 spec
* Fixed infinite loop
* Removed related unreferenced code
* #1683
* #1574
As this is an urgent change to fix potential platform-wide performance issues and TAXII 2.1 feed ingestion, I only removed the problematic code without inserting any additional code.
=> Rolled back 34eb547 as per #1683

internal-import-file/import-document/src/reportimporter/core.py
* Implementation of the detection system, and replacement of invalid characters when it is Windows
* No issue
=> [connector] bug/Import-document - invalid characters for windows

internal-enrichment/import-external-reference/Dockerfile
Everything is explained in the issue linked to this PR : https://github.com/OpenCTI-Platform/connectors/issues/1698
* Install v0.12.6 of the wkhtmltopdf utility
* https://github.com/OpenCTI-Platform/connectors/issues/1698
=> Improve pdf generation done by the connector import-external-reference

internal-enrichment/import-external-reference/Dockerfile
Modification of debian distro and utility version used in connector import-external-reference
Everything is explain in the issue https://github.com/OpenCTI-Platform/connectors/issues/1710
* https://github.com/OpenCTI-Platform/connectors/issues/1710
=> Modification of debian distro and utility version used in connector import-external-reference

external-import/rst-report-hub/src/config.yml.sample, external-import/rst-threat-feed/src/config.yml.sample, external-import/rst-threat-feed/src/main.py, external-import/rst-threat-feed/src/rstcloud/__init__.py
* an ability to import only attributed vs all indicators
* only_new behaviour changed to get all recently updated indicators
* vuln objects are added to the stix bundle to ensure that indicator->vuln references are imported correctly
* config sample files using the old connector names
* url value format for indicators corrected
=> [RST Cloud] Jan 2024 Updates

external-import/abuseipdb-ipblacklist/src/main.py
old: 
```
if __name__ == "__main__":
try:
connector = abuseipdbipblacklistimport()
connector.run()
except:
time.sleep(10)
exit(0)
```
new: 
```
if __name__ == "__main__":
try:
connector = abuseipdbipblacklistimport()
connector.run()
except Exception as e:
print(e)
time.sleep(10)
exit(0)
```
https://github.com/OpenCTI-Platform/connectors/issues/1721
*
*
- [x ] I consider the submitted work as finished
- [ x] I tested the code for its functionality using different use cases
- [x ] Where necessary I refactored code to improve the overall quality
=> added proper exception handling abuseipdb blacklist main.py

external-import/misp/src/misp.py
In some MISP sources somehow there are objects like intrusion-sets that are being created with a name that is a uuid. This fix will prevent that from happen.
=> Ignore intrusion-sets names that are uuid

internal-enrichment/import-external-reference/Dockerfile
Check for build architecture and install arm64 or amd64 version of package as needed. Currently, this `Dockerfile` always assumes `amd64` despite the `wkhtmltox` package having an arm64 distribution. The changes determine this at build time based upon the build platform architecture (via `uname -m`). Unfortunately, the output of `uname -m` produces different architecture names than what the packages use, so `sed` is used inline to translate these appropriately.
Tested build on both amd64 and arm64 (AWS Graviton)
=> [import-external-reference] Fix arm64 build for connector

internal-enrichment/tagger/README.md, internal-enrichment/tagger/src/connector.py
* Add an extra check for the attribute `objectLabel` along with handling of values.
* N/A
It's a relatively small change and quite rigid, it could potentially be opened up and allow for more attributes that are lists to be searched.
But from what I can see there isn't many use cases for that in OpenCTI's data model.
=> [Tagger] Support for objectLabel search in Tagger 

external-import/orange-cyberdefense/docker-compose.yml, external-import/orange-cyberdefense/src/config.yml.sample, external-import/orange-cyberdefense/src/orange-cyberdefense.py
This pull request addresses a bug in the import_datalake function. The issue stemmed from incorrect indentation, which led to the limitation where only threats of the "indicator" type were transmitted in the bundle. This caused a significant reduction in the number of threats processed by OpenCTI.
Additionally, improvements have been made to the formatting of notes to enhance readability. A filter has also been implemented to prioritize the display of the most recently updated items at the top of the list.
=> FEAT: update config, update note format, fix a bug 

stream/harfanglab/src/sightings.py
The problem has been identified, this error comes from the fact that when launching the connector there are no security events at HarfangLab.
* Setting up a condition and an info log to warn that there is no security event data at harfanglab
* #1771
*
=> [harfanglab] Fix error when there is no data (security events)

internal-enrichment/yara/src/main.py
* Use new `withFiles` option with `stix_cyber_observable.read()` to fetch file IDs for an Artifact when enriching with the YARA connector, based on https://github.com/OpenCTI-Platform/connectors/commit/1b8f610249ad04c0d87981052bc5269f58b9ec28#
* When fetching an Artifact's file contents, retry 5 times by default in case OpenCTI is not ready if auto-enriching a new Artifact
* Resolves https://github.com/OpenCTI-Platform/connectors/issues/1703
None
=> Fix YARA connector

external-import/feedly/src/feedly/opencti_connector/connector.py
* Split on `:` for stix pattern instead of `=`, and strip for good mesure
* when the pattern had `{stix_type}:value="some value"` format, it wasn't mapped correctly to the OpenCTI type
=> [feedly] improve observable mapping

external-import/threatfox/docker-compose.yml
CONNECTOR_NAME had typo (Space between Threat and Fox)
*       "CONNECTOR_NAME=Abuse.ch | Threat Fox" to "CONNECTOR_NAME=Abuse.ch | ThreatFox"
*    
* None
*
- [ X] I consider the submitted work as finished
- [X ] I added/update the relevant documentation (either on github or on notion)
Nice and easy change for me.
=> Fix typo in CONNECTOR_NAME in threatfox/docker-compose.yml

external-import/taxii2/README.md, external-import/taxii2/src/taxii2.py
* Add an API key as an authentication method to the remote TAXII server. Passed via a header on HTTP requests, using a key (header name), and a value (header value) mechanism.  
none
- [x ] I consider the submitted work as finished
- [x ] I tested the code for its functionality using different use cases
- [x ] I added/update the relevant documentation (either on github or on notion)
=> [taxii2] Add API key as an auth option for remote TAXII2 server url

internal-enrichment/import-external-reference/README.md, internal-enrichment/import-external-reference/docker-compose.yml, internal-enrichment/import-external-reference/src/config.yml.sample, internal-enrichment/import-external-reference/src/import-external-reference.py
* While waiting to find a new lib, we will correctly display the error on the front
* (Edit - Add variable wkhtmltopdf_path in config.yml)
* #1812 
*
* to test this connector you will first need to install [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html)
* After installation, setting up the path for testing (l.89):
`path_wkhtmltopdf = "C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"`
`config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)`
`data = pdfkit.from_url(url_to_import, output_path=None, options=options, configuration=config)`
What you must have:
URLs to test for external references:
- https://www.trendmicro.com/en_us/research/24/b/cve202421412-water-hydra-targets-traders-with-windows-defender-s.html
- https://securityaffairs.com/159074/reports/ransomfeed-q3-report- …
=> [Connector] Fix report error in front for import-external-reference

internal-enrichment/greynoise/src/greynoise.py
* Delete method "_get_entity_in_opencti()" not used after organization
* #1868
*
=> [Greynoise] Delete method not used

external-import/recorded-future/src/main.py
* Turn TLP configuration in lowercase to be correctly mapped
=> [Recorded Future] Fix TLP to be in lowercase for correct mapping

external-import/sekoia/docker-compose.yml
* add campaign,infrastructure,relationship in CONNECTOR_SCOPE in accordance to [our documentation](https://docs.sekoia.io/cti/features/integrations/opencti/)
* Users were not able to have the relationship between objects
=> add campaign,infrastructure,relationship in CONNECTOR_SCOPE

external-import/threatfox/src/main.py
* Improved csv reader configuration parameters
* Setting a block for malware creation and its relationship with the indicator when it is "unknown" (only indicator creation)
* Creation of a new object for better reading of columns
* Sort and remove null values (“None”, “”) for aliases and labels
* #1891
=> [ThreatFox] Fix mapping of malware aliases

external-import/cpe/src/connector.py
* Use title instead of product name extract
* #1931 
*
- [ x] I consider the submitted work as finished
- [ x] I tested the code for its functionality using different use cases
- [ x] Where necessary I refactored code to improve the overall quality
It's a small change that improves the UX directly
=> fix: use title for obserable name

external-import/threatfox/README.md, external-import/threatfox/docker-compose.yml, external-import/threatfox/src/config.yml.sample, external-import/threatfox/src/main.py
- In the nature of so many connectors, this was previously one giant function. Now it has several and looks somewhat organized.
- Changed the stix2.Malware to use the `fk_malware` field instead of `malware_printable` from the feed. Whichever connector made my Malware/alias records tends to use the fk_malware instead. This was causing ref not found errors when importing the releationships. For example: change from using `WikiLoader` to `win.wikiloader` as the malware name.
- Discussion: This could be considered a breaking change, add a toggle-able option?
- The Elasticsearch [integration](https://github.com/elastic/integrations/tree/main/packages/ti_opencti) expects the indicator name to be a valid ip, domain-name, or hash. Previously, this connector added them with the port included in …
=> [Threatfox] rework, improvements

external-import/recorded-future/entrypoint.sh, external-import/recorded-future/src/rflib/constants.py, external-import/recorded-future/src/rflib/risk_list.py
* Fix criticality score mapper and handle empty string to be replaced with score at 0 and add corresponding security level to be aligned with Recorded Future severity level
* Fix entrypoint to align with all connectors
* https://github.com/OpenCTI-Platform/opencti/issues/6358
=> [Recorded Future] Fix risk rules criticality score, handle empty string

internal-enrichment/recordedfuture-enrichment/docker-compose.yml, internal-enrichment/recordedfuture-enrichment/src/config.yml.sample, internal-enrichment/recordedfuture-enrichment/src/requirements.txt, internal-enrichment/recordedfuture-enrichment/src/rf_enrichment.py
* Update RF enrichment connector to be playbook compatible
* Update related configuration files
* Remove confidence level in connector as it is deprecated since >= 6.0
* https://github.com/OpenCTI-Platform/connectors/issues/1839
=> [RF Enrichment] Make RF enrichment connector playbook compliant

internal-enrichment/import-external-reference/README.md
* Correct config variable name from `CONNCETOR_AUTO` to `CONNECTOR_AUTO`
=> [Import External Reference] Correct config variable name

external-import/threatfox/src/main.py
* Added an objects if statement before send_stix2_bundle. When setting THREATFOX_IMPORT_OFFLINE to false, it is possible to have a bundle with 0 objects, which causes an error.
* Moved the debug print to before send_stix2_bundle so it prints when send_stix2_bundle is causing an error.
=> [ThreatFox] Added if statement to send_stix2_bundle

external-import/riskiq/src/config.yml.sample, external-import/riskiq/src/riskiq/riskiq.py
* We want to be able to set a starting date for importing RiskIQ items.
* A new environment variable can now be used to configure this behavior (RISKIQ_IMPORT_FROM_TIMESTAMP); if it's not set, the behavior remains the same (all articles are fetched).
=> [RiskIQ] Add support for import start date

internal-export-file/export-file-csv/src/export-file-csv.py, internal-export-file/export-file-stix/src/export-file-stix.py, internal-export-file/export-file-txt/src/export-file-txt.py, internal-export-file/export-report-pdf/src/export-report-pdf.py
* Pass markings through export connectors : report pdf, csv, txt, stix
* https://github.com/OpenCTI-Platform/opencti/issues/5797
This pull request is related to the ones in the `Client-Python` and `Open-CTI` :
* https://github.com/OpenCTI-Platform/client-python/pull/613
* https://github.com/OpenCTI-Platform/opencti/pull/6030
=> [backend] Define file marking definitions (#opencti/5797-export)

internal-enrichment/greynoise/src/main.py
* The previous update for API checking was causing container restarts every few minutes
* Adds a local state file for the API key, which the container can then use
*
*
=> [greynoise_enricher] change API key validation to use local state file

external-import/eset/src/eset.py
* When a STIX object is encountered which has no `created_by_ref` then add one referencing the ESET author
The ESET connector is creating a lot of objects with no listed author, when ingesting from a collection. The connector properly sets authors in reports, but not in entities ingested from collections. This change will add ESET as the author, if the STIX in the TAXII feed doesn't already list another author, so that none of these entities are author-less.
=> [eset] Bug: Fix entities and SCOs created with no author

external-import/eset/src/eset.py
The STIX2 malware entities from ESET's data stream appear to have their IDs randomly generated each time they appear in a new object. This results in many thousands of STIX IDs being generated for the same malware signature. To correct this, the STIX ID provided by ESET is overridden by the deterministic id generator available in pycti, before the entity is ingested. This is contributing to redis memory consumption, as well as unnecessary backlogging of the ESET connector's ingest queue.
Additionally, I discovered a similar bug exists where ESET attempts to communicate country-targeting information by using an Identity named `"customer"` with country codes in the `contact_information` field. The way this is formatted causes similar problems as the Malware entities above, but in this case …
=> [eset] Bug: Fix cases where ESET randomly-generates STIX ids, creating infinite aliases

external-import/taxii2/src/taxii2.py
* Added code to generate a work_id and modified send_stix2_bundle to send the work_id with the bundle.
* My IDE was complaining that utcfromtimestamp was depreciated, changed this to fromtimestamp. 
* https://github.com/OpenCTI-Platform/connectors/issues/977
I have tested this code against taxii 2.0 and 2.1 servers.
=> [taxii2] Added work_id to send_stix2_bundle

internal-enrichment/virustotal/src/virustotal/builder.py
* Correct recovery and updating of the score
* In the case where the virustotal score is lower than the opencti score and the environment variable is set to false, we correctly create a note instead of changing the score in opencti.
* #2091 
*
=> [VirusTotal] Fix updating score

external-import/recorded-future/src/rflib/rf_client.py
because of the very long processing times, there is a problem with long and inactive tcp sessions (<30mn) which pass through security equipment (FW / Proxy)
=> [RF] generate new tcp session on each fusion file - signed 

internal-import-file/import-document/src/reportimporter/core.py
* Initialize file to None before import, otherwise we might add the previous file imported (global import) to a report when creating a workbench directly from a report
* https://github.com/OpenCTI-Platform/connectors/issues/2144
To reproduce the issue, you need to import globally a file that will create a workbench, no need to validate this workbench, just create a new report, import in this report another file, then validate the workbench and it will take the last imported file and add it to the report.
=> [import-document] Initialize file before import (opencti/6999)

external-import/diode-import/entrypoint.sh
* Fix directory entrypoint.sh
It should be : `cd /opt/opencti-connector-diode-import` instead `cd /opt/opencti-connector-diode-bundle-import`.
* #2152 
*
=> [Diode-Import] Fix directory entrypoint.sh

external-import/rst-report-hub/src/main.py
* A PDF copy of the original webpages (where the TI reports come from) is copied to all objects in the bundle. Fixed by attaching PDFs only to a Report stix object
* If connector is run manually, the config file needs another stanza as there is a type in the code. Fixed by changing the property name from "rst_report_hub" to "rst-report-hub" to align with this connector name and the folder name for it.
=> [RST CLOUD] May 2024: Bug Fixes 

external-import/mandiant/src/connector/indicators.py
* Remove report creation loop while importing indicators
* https://github.com/OpenCTI-Platform/connectors/issues/2170
=> [Mandiant] Remove report creation while importing indicators

internal-enrichment/urlscan-enrichment/src/main.py, internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/converter_to_stix2.py
* Fix import environment variable in converter_to_stix from docker
* Remove unnecessary instantiation of UrlscanConstants in main.py
* #2194
=> [Urlscan] Fix import environment variable from docker

internal-enrichment/virustotal/src/virustotal/builder.py
* added a check, to verify if the key "asn" is being returned, which doesn't cause the enrichment to fail completely.
*
Got the error:
``` json
"Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):
File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 349, in _data_handler
message = self.callback(event_data)
^^^^^^^^^^^^^^^^^^^^^^^^^
File \"/opt/opencti-connector-virustotal/virustotal/virustotal.py\", line 371, in _process_message
return self._process_ip(stix_objects, stix_entity, opencti_entity)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File \"/opt/opencti-connector-virustotal/virustotal/virustotal.py\", line 247, in _process_ip
builder.create_asn_belongs_to()\n  File …
```
=> Update Virustotal builder

external-import/misp/README.md, external-import/misp/docker-compose.yml, external-import/misp/src/config.yml.sample, external-import/misp/src/misp.py
…SP_DATETIME_ATTRIBUTE
* Add env `MISP_DATE_FILTER_FIELD`
* use new env `MISP_DATE_FILTER_FIELD` as a filter field instead of `MISP_DATETIME_ATTRIBUTE`
* https://github.com/OpenCTI-Platform/connectors/issues/2158
=> add new env MISP_DATE_FILTER_FIELD

external-import/taxii2/README.md, external-import/taxii2/src/config.yml.sample, external-import/taxii2/src/taxii2.py
I have a taxii 2.0 feed that is pushing interesting data in a stix custom property. Currently it is being dropped by OpenCTI. I've added some code (disabled by default) that will allow a user to define the custom property as a variable and save the data as a label. I wasn't sure if there was a better way to do this.
I did pop the question into slack, just in case I get any interesting responses there.. https://filigran-community.slack.com/archives/C06CC3T5Z37/p1716258546130119
=> [Taxii2] Option to pull data from custom property and put in a label

external-import/recorded-future/src/rflib/rf_to_stix2.py
* Fix import TA as individual when type of Person from RF
=> [Recorded Future] Fix import TA as individual when type of Person from RF

internal-enrichment/cape-sandbox/docker-compose.yml, internal-enrichment/cape-sandbox/src/cape-sandbox.py, internal-enrichment/cape-sandbox/src/config.yml.sample
Update docker-compose.yml with correct variable name
=> [cape-sandbox] - fix docker-compose.yml template

external-import/mandiant/src/connector/__main__.py
* Catch exception outside running connector process by adding a print()
* https://github.com/OpenCTI-Platform/connectors/issues/2372
=> [Mandiant] Add log when exception is caught outside of running connector process

internal-import-file/import-document/src/reportimporter/config/entity_config.ini, internal-import-file/import-document/src/reportimporter/models.py
* Add a new configuration to only have exact match for some fields. 
* Add aliases of locations to exact match: when a country has a 'AND' alias for exemple, we do not want to match all lower cases 'and'
* opencti #7566
=> [import-document] added new exact_match_fields in configuration

.circleci/config.yml, stream/webhook/Dockerfile, stream/webhook/README.md, stream/webhook/docker-compose.yml, stream/webhook/entrypoint.sh, stream/webhook/src/requirements.txt, stream/webhook/src/webhook.py
* Add a new connector Webhook which will relay events
Open to discuss :)
=> [Webhook] Init connector

external-import/opencti/src/connector.py
- Fix the interval check in the OpenCTI connector.
`self.interval` is already converted to seconds [here](https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/opencti/src/connector.py#L63)
So the current calculation takes a seconds value, subtracts 1 second, then multiplies, turning it into something inbetween millis/nanos.
Relevant log:
```
{
"timestamp": "2024-07-08T18:20:42.200433Z",
"level": "INFO",
"name": "OpenCTI",
"message": "Connector will not run, next run in: -122.06 days"
}
```
Relevant state:
```
{'last_run': 1709246449}
last_run.isoformat()='2024-02-29T22:40:49+00:00'
```
Broken since [here](https://github.com/OpenCTI-Platform/connectors/commit/038869f327b01c455fca22191ccf150e5e92e5f9#diff-ba1788a6c5f0f2c6a513a1165e4289377d127e7b17bf69fcfd7d88f0d22e26a6R …
=> [opencti] Fix interval bug

external-import/misp/src/misp.py
The return was in a loop, when the indicator was composed, there was an exit too early. This resulted in the failure to create two indices for the filename|md5 type, for example.
=> Fix for mistake in indent.

internal-enrichment/tagger/src/connector.py
* Fixed the issue in TaggerConnector where entity type comparisons were case-sensitive, causing mismatches.
* Ensured safe access to entity attributes to prevent runtime errors when attributes are missing.
* This fix addresses an unreported issue where reports were not being tagged correctly due to case-sensitive entity type checks and missing attributes.
These changes ensure that the 'Tagger' connector correctly tags entities by using case-insensitive comparisons and handling missing attributes gracefully. This improves the robustness and accuracy of the tagging process.
=> Fix Tagger Connector entity type comparison and safe attribute access"

external-import/mandiant/README.md, external-import/mandiant/src/connector/base.py, external-import/mandiant/src/connector/reports.py
* Add new environment variable to add CPE for a Software or not => `MANDIANT_VULNERABILITY_IMPORT_SOFTWARE_CPE`
* Add new environment variable to limit the number of relationships created for a vulnerability => `MANDIANT_VULNERABILITY_MAX_CPE_RELATIONSHIP`
* https://github.com/OpenCTI-Platform/connectors/issues/2467
=> [Mandiant] Create 2 new environment variables for creating CPE or not for software and limit number of relationships 

external-import/malpedia/README.md, external-import/malpedia/src/config.yml.sample, external-import/malpedia/src/main.py, external-import/malpedia/src/malpedia_connector/malpedia.py, external-import/malpedia/src/malpedia_services/config_variables.py, external-import/malpedia/src/malpedia_services/converter_to_stix.py
* Set a new environment variable to define the `default_marking`.
* Set up scheduler without breaking changes (using `schedule_unit`)
* Added traceback
* Updated Readme and config.yml.sample
* Removed `update_existing_data` usage
* #2460
=> [Malpedia] Adding variable default_marking, and schedule_unit

external-import/mandiant/src/connector/base.py, external-import/mandiant/src/connector/reports.py
*  Generate new ID when importing Software from a Report when `MANDIANT_VULNERABILITY_IMPORT_SOFTWARE_CPE` is configured to False 
*  Fix state when entity use epoch time: add a security for end_epoch => start_epoch + 2 days
* https://github.com/OpenCTI-Platform/connectors/issues/2492
=> [Mandiant]  Handle multiple standard ID for a software when importing a report + fix state when entity use epoch time

external-import/sekoia/README.md
Small updates
* Update of the content from Partner (Sekoia)
*
*
*
=> Update README.md from Partner

.circleci/config.yml, external-import/cofense/.gitignore, external-import/cofense/Dockerfile, external-import/cofense/README.md, external-import/cofense/docker-compose.yml, external-import/cofense/entrypoint.sh, external-import/cofense/src/config.yml.sample, external-import/cofense/src/main.py, external-import/cofense/src/requirements.txt
* Add new connector for integration with Cofense
* https://github.com/OpenCTI-Platform/connectors/issues/2522
=> [Cofense] NEW Cofense connector from Cofense

external-import/anyrun-feed/src/anyrun_feed.py
According to the [API manual](https://intelligence.any.run/Threat%20Intelligence%20Feeds%20Documentation.pdf), with 'TI token', the Header should start with API-Key.
* `Header: Basic <TI Token>` -> `Header: API-Key <TI Token>`
* Wrong way of using 'TI token'
=> Fix anyrun_feed.py

internal-export-file/export-report-pdf/src/resources/case.css.template, internal-export-file/export-report-pdf/src/resources/intrusion-set.css.template, internal-export-file/export-report-pdf/src/resources/report.css.template, internal-export-file/export-report-pdf/src/resources/threat-actor.css.template
Sets 100% as the maximum width of images when converting to html before to be exported in PDF.
* https://github.com/OpenCTI-Platform/connectors/issues/2587
=> Sets 100% as the maximum width of images when converting to html before to be exported in PDF

external-import/flashpoint/src/mispfeed.py
* Change Flashpoint's MISP endpoint from HTTP to HTTPS.
The HTTP in the MISP URL causes an issue with our proxy, that will only accept HTTPS requests. The Flashpoint API also requires HTTPS and calling it with HTTP leads to a 307 redirect.
The MISP endpoint used here also isn't configurable. @SamuelHassine , let me know if you have any thoughts on this one though or if there is something that I've missed.
=> Change flashpoint misp endpoint from http to https

external-import/urlscan/src/urlscan/connector.py
=> [urlscan] fix missing created_by_ref for indicators GH-2654

external-import/feedly/src/feedly/opencti_connector/connector.py, external-import/feedly/src/requirements.txt
* Using report contents instead of creating a note in the feedly connector
* N/A
=> [feedly] Use content for reports intsead of creating notes

external-import/zerofox/src/collectors/collector.py, external-import/zerofox/src/collectors/mappers/botnetToInfrastructure.py, external-import/zerofox/src/collectors/mappers/c2DomainsToInfrastructure.py, external-import/zerofox/src/collectors/mappers/exploitToTool.py, external-import/zerofox/src/collectors/mappers/malwareToMalware.py, external-import/zerofox/src/collectors/mappers/phishingToInfrastructure.py, external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py, external-import/zerofox/src/collectors/mappers/vulnerabilityToVulnerability.py, external-import/zerofox/src/main.py, external-import/zerofox/src/open_cti/__init__.py, external-import/zerofox/src/open_cti/domain_objects.py, external-import/zerofox/src/open_cti/observables.py
* include the x_opencti_main_observable_type custom property on all observables
* add author as custom property  created_by_ref field on stix observables, normal one on other objects, based on a stix2 Identity object named ZeroFox
=> [ZeroFox] add created_by_ref and opencti_observable_main_type to stix objects

external-import/urlscan/README.md, external-import/urlscan/docker-compose.yml, external-import/urlscan/src/config.yml.sample, external-import/urlscan/src/urlscan/client.py, external-import/urlscan/src/urlscan/connector.py, external-import/urlscan/src/urlscan/loop.py
* Connector now properly uses `CONNECTOR_INTERVAL`.
* Connector will now properly handle getting data from provider since `last_run`
* Introduces a new config variable `CONNECTOR_LOOKBACK`. This variable defines how far to look back in days if the connector has never run or the last run is older than this value. Default is 3. You should not go above 7.
* GH-2667
=> [urlscan] Resolves GH-2667

external-import/sekoia/src/sekoia.py
* Avoid to add multiple time the Sekoia.io source in objects
*
*
=> fix(Sekoia): Prevent adding multiple times Sekoia.io as reference

external-import/greynoise-feed/src/main.py
* Modifies the query the feed uses to match the restrictions documented: https://docs.greynoise.io/docs/using-greynoise-as-an-indicator-feed#how-to-build-a-script-to-pull-a-greynoise-feed
*
*
*
=> [greynoise-feed] fix feed queries to match documentation

external-import/crowdstrike/src/crowdstrike_feeds_services/utils/__init__.py
The CrowdStike Connector was failing when encountering a specific report from CrowdStrike that had an undefined tag. This PR uses the more resilient `get` method to obtain a key that may be missing.
Here is a log showing the error:
> `"level": "ERROR", "name": "Crowdstrike", "message": "CrowdStrike connector internal error: 'value'", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-crowdstrike/crowdstrike_feeds_connector/core.py\", line 284, in process_message\n    importer_state = importer.start(work_id, new_state)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-crowdstrike/crowdstrike_feeds_connector/importer.py\", line 40, in start\n    return self.run(state)\n           ^^^^^^^^^^^^^^^\n  File …
=> [CrowdStrike] Fix KeyError in CrowdStrike processing

external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py
* use dot notation to access properties of FetchedReport instances, as bracket notation can't be used in this case
* #2603
=> [Crowdstrike] Fix "'FetchedReport' not subscriptable" errors

external-import/crowdstrike/src/crowdstrike_feeds_connector/actor/importer.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/importer.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/snort_suricata_master_importer.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/rule/yara_master_importer.py
* Add work_id per entity (Report/Actor/Indicator)
* Change filter for getting last updated threat actors
* Change filter for last updated indicators
* Optimize indicator import 
* https://github.com/OpenCTI-Platform/connectors/issues/2683
=> [Crowdstrike] Improve connector and indicators ingestion 

external-import/cisa-known-exploited-vulnerabilities/src/main.py
Instead of storing the "execution date", use the provided "dateReleased" as the state and republish content only if the "dateReleased" is updated since last execution.
https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities_schema.json
* https://github.com/OpenCTI-Platform/connectors/issues/2720
=> [CISA KEV]: Do not republish all the content at each execution

stream/webhook/docker-compose.yml
CONNECTOR_SCOPE is incorrect based on documentation. This is the fix
Docker-compose.yml of the connector-webhook has the incorrect CONNECTOR_SCOPE
Documentation found in README states that the it is mandatory and 'Must be webhook'
=> [ Webhook Stream ] - Correct CONNECTOR_SCOPE

stream/sentinel-intel/Dockerfile
Replace `opencti-connector-sentinel` with `opencti-connector-sentinel-intel`.
=> [Sentinel-intel] Fix directory name in Dockerfile

external-import/crowdstrike/src/crowdstrike_feeds_services/utils/config_variables.py
* Fix API Base URL variable name incorrectly defined
* https://github.com/OpenCTI-Platform/connectors/issues/2773
=> [Crowdstrike] Fix API Base URL variable name incorrectly defined

stream/harfanglab/Dockerfile, stream/qradar/Dockerfile, stream/sentinel-intel/Dockerfile, stream/sentinel/Dockerfile, stream/splunk/Dockerfile, stream/webhook/Dockerfile
* Downgrade Python version to 3.11 as stix-shifter is not compatible
=> [Connectors] Downgrade Python version to 3.11 as stix-shifter is not compatible

internal-enrichment/import-external-reference/Dockerfile
* Downgrade Python version to 3.11 connector use a lib which is not compatible with Python 3.12 in Dockerfile
=> [import-external-reference] Downgrade Python version to 3.11 connector use a lib which is not compatible with Python 3.12 in Dockerfile

internal-enrichment/import-external-reference/Dockerfile
* Change distribution to bookworm as playrwright cannot be used with alpine
=> [import-external-reference] Change distribution to bookworm as playrwright cannot be used with alpine

.circleci/config.yml
* Add docker_layer_caching for image layers in CI
https://circleci.com/docs/docker-layer-caching/
`Use Docker layer caching (DLC) to reduce Docker image build times on CircleCI. DLC is available on all CircleCI plans.`
https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/#set-up-remote-docker-and-docker-layer-caching
`With Docker layer caching enabled, CircleCI can reuse layers from previous builds if they haven’t changed. This significantly reduces build times, as unchanged layers do not need to be rebuilt.`
* https://github.com/OpenCTI-Platform/connectors/issues/2901
=> [connectors] Add docker_layer_caching for image layers in CI

internal-import-file/import-file-misp/src/import-file-misp.py, internal-import-file/import-file-stix/src/import-file-stix.py
* we were adding objects_refs to all enties in the context of an import within an entity. We now check if the entity context is a container before adding object refs. This caused the splitter to incorrectly skip the relationships linked to the entity context
* closes #2918
* original opencti issue https://github.com/OpenCTI-Platform/opencti/issues/8818
=> [internal-import] only add object_refs if entity context is a container

external-import/mandiant/src/connector/indicators.py
*  Add Mandiant score to IOC instead of confidence level on OCTI
* https://github.com/OpenCTI-Platform/connectors/issues/2816
=> [Mandiant] Add Mandiant score to IOC instead of confidence

external-import/crowdstrike/src/crowdstrike_feeds_connector/core.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/importer.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/report/builder.py, external-import/crowdstrike/src/crowdstrike_feeds_connector/report/importer.py
* Remove report creation when importing Indicators due to volume of data
* Add query when importing report to add IOCs at the same time
These changes avoid to have the report with some entities at a certain moment and avoid to wait days to have complete report with IOCs.
* https://github.com/OpenCTI-Platform/connectors/issues/2765
=> [Crowdstrike] Handle IOCs to be added in the report while importing the report

stream/tanium/src/import_manager.py
* Check if "labels" key exists in data before accessing it
* https://github.com/OpenCTI-Platform/connectors/issues/2798
As the connector is deprecated, I "quick fixed" this issue without any significant/structural changes.
=> [Tanium] Fix KeyError on non-existing indicator's labels

.circleci/config.yml
* Revert python test image to 3..11 version as some dependencies do not support 3.12
* https://github.com/OpenCTI-Platform/connectors/issues/2978
*
=> fix: revert to 3.11 for CI tests

internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/converter_to_stix2.py
When no ASN was found, generate_stix_asn_with_relationship returned None, causing extend(stix_obs_asn) to fail, returning empty array instead fixes the issue
* Fix error in urlscan-enrichment when no ASN is found
Error I got:
```
connector-urlscan-enrichment-1  | {"timestamp": "2024-11-14T11:01:57.762977Z", "level": "ERROR", "name": "Urlscan", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-urlscan-enrichment/main.py\", line 318, in _process_message\n    stix_bundle = self._generate_stix_bundle(\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-urlscan-enrichment/main.py\", line 196, in _generate_stix_bundle\n …
```
=> [urlscan-enrichment] Return empty array instead of None when no ASN found

external-import/mitre/src/connector.py
* Added a default value of 7 for the MITRE_INTERVAL, as expected per documentation.
* N/A
No big change, just a minor thing I stumbled on during my first deployment.  If the misp.interval setting is not explicitly defined, the worker will crash with a type error, while the documentation states there is a default value of 7.
=> [Mitre] Add default for interval, as the documentation states.

internal-enrichment/shodan/README.md, internal-enrichment/shodan/docker-compose.yml, internal-enrichment/shodan/src/config.yml.sample, internal-enrichment/shodan/src/shodanImport.py
* Created config to use ISP name for ASN name. I wasn't sure if this was a bug or intended by the original author, but other enrichment connectors use a name, so this change allows you to align with that.
=> [Shodan] Created config to use ISP name for ASN name.

external-import/misp-feed/src/misp-feed.py, external-import/misp/src/misp.py
- Implementation of a check when creating a relationship: if `object_observable` id is different from `observable` id, then the relationship can be created; otherwise, it cannot be created.
Initially, when creating the relationship, we could have had an identical ref for `source_ref `and `target_ref`, which would have caused the error: `UNSUPPORTED ERROR (Relation cant be created with the same source and target)`
- Changes made to `MISP` & `MISP-FEED` connectors
* #2868
=> [Misp] Fix error of relation having same ref for source and target

external-import/mandiant/src/connector/base.py, external-import/mandiant/src/connector/errors.py, external-import/mandiant/src/connector/utils.py
* Implement an Exception, handling connector state external reset.
* https://github.com/OpenCTI-Platform/connectors/issues/3001
[Investigation page](https://www.notion.so/filigran/Mandiant-Crash-if-no-state-1448fce17f2a80599603e9dacebad438)
Simplified behavior changes
```mermaid
stateDiagram-v2
classDef RED fill:red
classDef ORANGE fill:orange, color:black
classDef NEW stroke:yellow
classDef YELLOW fill: yellow, color:black
[*] --> ContextSetup
ContextSetup --> ConnectorInit 
ConnectorInit --> WaitingForNewScheduledJob : Initial State Registered
WaitingForNewScheduledJob --> Processing : New Job Detected
Processing --> AttemptReadState 
AttemptReadState --> StatePresent : STATE Found
AttemptReadState --> StateNull : STATE Null
StatePresent --> SuccessCase : Data Received
SuccessCase --> …
```
=> [Mandiant] fix: infinitely crashes if the state is empty

internal-export-file/export-report-pdf/src/export-report-pdf.py
* fix list search in case of list params equal None
* fix file markings on selection 
* https://github.com/OpenCTI-Platform/opencti/issues/9082
It crashed when we tried to export a selection of entities with file_markings.
Then another case was fixed: it would also crash when list_params was empty. 
ask Nino for more infos if needed
=> [ExportReportPdf] list params fixed (#9082)

external-import/loaderinsightagency/Dockerfile, external-import/loaderinsightagency/README.md, external-import/loaderinsightagency/docker-compose.yml, external-import/loaderinsightagency/entrypoint.sh, external-import/loaderinsightagency/src/config.yml.sample, external-import/loaderinsightagency/src/main.py, external-import/loaderinsightagency/src/requirements.txt
The connector ingests IOCs from the Loader Insight Agency File Feed and creates relationships that provides context to the IOCs such as which malware downloaded which payload, from where and what the payload is detected as (if known).
* Adding a new connector to ingest IOCs from the Loader Insight Agency File Feed.
* None
=> Create a connector for the Loader Insight Agency File Feed

internal-export-file/export-report-pdf/src/export-report-pdf.py, internal-export-file/export-report-pdf/src/requirements.txt, internal-export-file/export-report-pdf/src/resources/case.html, internal-export-file/export-report-pdf/src/resources/report.css.template, internal-export-file/export-report-pdf/src/resources/report.html
- add `cmarkgfm` library
- convert entity `description` field to HTML before injecting it into template
- replace `<p>` tag by `<div>` in case’s template to ensure consistent display
* #2735 
- run `bandit` on `markdown` lib's code
- run `pip-audit` on connector's requirements
Incident response's description used for tests:
```
**Incident from Harfanglab Incidents**  
1. first item  
first description
2. second item  
second desc  
www.example.com, https://example.com, and contact@example.com.
A note[^1]
[^1]: Big note.
~one~ or ~~two~~ tildes.
| a | b  |  c |  d  |
| - | :- | -: | :-: |
``` 
output:
cmarkgfm lib doc: [https://pypi.org/project/pycmarkgfm/](https://pypi.org/project/pycmarkgfm/)
=> [ExportReportPdf] Convert entity's description from markdown to HTML

external-import/crtsh/src/crtsh/core/crtsh.py, external-import/crtsh/src/crtsh/core/crtsh_utils.py, external-import/crtsh/src/lib/external_import.py, external-import/crtsh/src/main.py
* handle `last_run` timestamp to avoid re-importing same data over and over
* fill `author` field
* get fresh data on every run instead of on connector's launch
* #2540 
- Notion investigation page is complete
Issues with STIX IDs have been resolved in a previous commit few weeks/months ago (https://github.com/OpenCTI-Platform/connectors/commit/643ab5e7d26ad2cf28207b2ef235290a53ff92e7#diff-9c357b07c8678cca6427bb1f51bda9ebec82bf33decba03a71e8b36e9e84b737)
=> [crtsh] fix import issues

internal-enrichment/tagger/README.md, internal-enrichment/tagger/src/connector.py
* Two new attributes available to act based on contained entities of container (e.g. Report)
* https://github.com/OpenCTI-Platform/connectors/issues/3064
Need to be tested using the two new attributes available:
- objects-type
- objects-name
=> [Tagger] Add a capacity to the Tagger connector

internal-import-file/import-document/docker-compose.yml
Change the env variable CONNECTOR_ONLY_CONTEXTUAL=false to prevent confusion.
- https://github.com/OpenCTI-Platform/connectors/issues/3087
=> Update importDocument docker-compose.yml

external-import/misp/docker-compose.yml, external-import/misp/src/config.yml.sample
Update default MISP docker-compose.yml example configuration to avoid confusion about the purpose of the "MISP_IMPORT_TAGS" env.
* https://github.com/OpenCTI-Platform/connectors/issues/3090
*
=> Update default MISP docker-compose.yml to avoid confusion

external-import/recorded-future/src/rflib/rf_client.py, external-import/recorded-future/src/rflib/rf_to_stix2.py
* handle case when no attachement found
* Add a fake ID in the report as STIX2 doesn’t allowed that a report have no object references and it raise an error when no object_refs exists and we still want to create the report ❌
* Solution preferred:  Create a subclass of Report to have optional object_refs and not required
* https://github.com/OpenCTI-Platform/connectors/issues/2938
=> [Recorded Future] handle exception raised when no attachment and no object_refs to report

templates/create_connector_dir.sh
* Create an init script to de-templatize a template connector
It might be interesting to automatically add the build steps from the script, but I had no idea how to do it automatically ..
=> [TEMPLATE] create init script

stream/crowdstrike-endpoint-security/src/crowdstrike_services/constants.py
* Change values used in `range()` function.
* 19, 39, 59, 79, and 100 were not taken into account when mapping thus returning `null` value.
* This resulted in an invalid input error when creating indicators with those scores.
=> [CrowdStrike-Endpoint-Security] Fixing severity map bug

renovate.json
* Allow renovate to create PR only outside French working hours.
*
*
=> Limit renovate PRs to nights and weekend

external-import/zerofox/src/collectors/mappers/malwareToMalware.py, external-import/zerofox/src/collectors/mappers/ransomwareToMalware.py, external-import/zerofox/src/open_cti/domain_objects.py, external-import/zerofox/src/requirements.txt
* Use pycountry to better annotate country codes
* add opencti_main_observable_type to indicators
* correct malware name to just be a file hash
* https://github.com/OpenCTI-Platform/connectors/issues/2828
=> [Zerofox] Add format changes to malware endpoint and country entities

external-import/mandiant/src/connector/reports.py
Comment codes that generate invalid "originates-from" relationships between some countries  and malwares/intrusion-sets mentionned in Mandiant reports
* https://github.com/OpenCTI-Platform/connectors/issues/3129
=> [Mandiant]: Invalid "originates-from" relationships

external-import/eset/src/eset.py
In the ESET connector, if an atomic indicator comes in as a URL, Domain-Name, or IPv4 Address, the upstream STIX doesn't have the `x_opencti_main_observable_type` on it. It also doesn't automatically get set during ingest. So, in the case of supported indicator types, add it to the bundle before ingest.
- https://github.com/OpenCTI-Platform/connectors/issues/3237
=> [eset] FIX: Add x_opencti_main_observable_type when missing from atomic indicators

external-import/ransomwarelive/README.md, external-import/ransomwarelive/src/lib/ransom_conn.py
- Properly handle empty sector values
- Do not create threat actor objects by default
- They were wasteful duplicates of Intrusion Sets and not threat actors in terms of STIX definitions 
- Fix typos
- Fix README tables
* https://github.com/OpenCTI-Platform/connectors/issues/2665
=> Improve ransomware.live connector

external-import/abuse-ssl/src/abuse-ssl.py
Remove unused variable `update_existing_data`
#3194 
I have broken the previous PR #3203. sry for this :). 
Thank you for your project!
=> [AbuseSSL] Remove unused variable

templates/internal-enrichment/src/internal_enrichment_connector/connector.py
Fix syntax error making the test always true
`if self.entity_in_scope` was always true
* Add a parameter to entity_in_scope so it actually runs the function instead of testing if it exists
* https://github.com/OpenCTI-Platform/connectors/issues/3273
=> [Templates] Fix syntax error on entity_in_scope in template

external-import/hunt-io/.docker-compose.yml, external-import/hunt-io/.dockerignore, external-import/hunt-io/Dockerfile, external-import/hunt-io/README.md, external-import/hunt-io/entrypoint.sh, external-import/hunt-io/src/config.yml.sample, external-import/hunt-io/src/external_import_connector/__init__.py, external-import/hunt-io/src/external_import_connector/client_api.py, external-import/hunt-io/src/external_import_connector/config_variables.py, external-import/hunt-io/src/external_import_connector/connector.py, external-import/hunt-io/src/external_import_connector/converter_to_stix.py, external-import/hunt-io/src/external_import_connector/models.py, external-import/hunt-io/src/external_import_connector/utils.py, external-import/hunt-io/src/main.py, external-import/hunt-io/src/requirements.txt, external-import/hunt-io/tests/common_fixtures.py, external-import/hunt-io/tests/test-requirements.txt, external-import/hunt-io/tests/test_template_connector.py
This PR introduces a new connector to integrate Hunt.io’s C2 (Command and Control) feed with OpenCTI. The connector retrieves, processes, and maps threat intelligence data into STIX-compliant objects and relationships to enhance threat visibility in OpenCTI.
- API Integration: The connector fetches C2 feeds from the [Hunt.io API](https://apidocs.hunt.io/reference/download-c2-feed) in zip format.
- Response Handling: The compressed payload is unzipped, and its contents are processed into actionable threat intelligence.
- STIX Object Creation: Each entity in the feed is mapped to corresponding STIX objects/observables.
- Concurrency: To efficiently handle the large datasets, the connector spawns up to 4 worker threads, processing entities concurrently to mitigate buffer overflow risks.
| …
=> [Hunt IO] Connector for importing C2 feed into OpenCTI

external-import/rst-report-hub/src/main.py
*  Add missing generate id
* https://github.com/OpenCTI-Platform/connectors/issues/3290
=> [RST Report Hub] Add missing generate id

external-import/comlaude/src/main.py, external-import/eset/src/eti_api.py, external-import/intelfinder/src/intelfinder/__init__.py, external-import/obstracts/src/taxii2.py, external-import/sentinel-incidents/src/sentinel_incidents_connector/connector.py, external-import/siemrules/src/taxii2.py, external-import/stixify/src/taxii2.py, external-import/tenable-vuln-management/src/tenable_vuln_management/converter_to_stix.py, external-import/tenable-vuln-management/src/tenable_vuln_management/models/opencti.py, external-import/vulmatch/src/taxii2.py, external-import/zerofox/src/http_/__init__.py, external-import/zerofox/src/http_/http_request.py, stream/chronicle/src/common/datetime_converter.py
* Update format following Black dependency upgrade
* https://github.com/OpenCTI-Platform/connectors/issues/3345
=> [All connectors] Fix Update format following Black dependency upgrade

.circleci/config.yml, .circleci/scripts/generate_ci.py, .circleci/templates/dynamic.yml.j2, .circleci/vars.yml, external-import/sentinelone-threats/Dockerfile
The main idea is to dynamically generate a ci configuration file at runtime based on the directory structure to facilitate building all containers.
* Divide all container construction work into single units
* Remove the need to manually add the build of new images
* ~~Add capability to build ARM images~~
* Add capability to overload tags
* https://github.com/OpenCTI-Platform/connectors/issues/3038
* https://github.com/OpenCTI-Platform/connectors/issues/2359
* https://github.com/OpenCTI-Platform/connectors/issues/502
Should not be merge yet, need to:
🚨 Some containers could be renamed (internal-export-file / internal-import-file)
----
=> [CIRCLECI] Dynamic-CI 💡

external-import/socradar/Dockerfile, external-import/socradar/README.md, external-import/socradar/entrypoint.sh, external-import/socradar/requirements.txt, external-import/socradar/src/config.yml.sample, external-import/socradar/src/lib/radar.py, external-import/socradar/src/main.py
- Add SOCRadar external import connector with support for:
* IP addresses (IPv4/IPv6)
* Domains
* URLs
* File hashes
- Implement STIX2 mapping with metadata:
* Source attribution
* First/last seen dates
* Confidence levels
* TLP marking
- Add rate limiting and pagination handling
- Include error handling and logging
- https://github.com/OpenCTI-Platform/connectors/issues/3379
This connector integrates SOCRadar's threat intelligence feeds into OpenCTI. Testing has been completed with:
- OpenCTI 6.4.2
- Python 3.11
- Various indicator types and formats
- STIX2 bundle creation and import verification
The implementation follows OpenCTI connector best practices and provides a robust solution for importing SOCRadar threat intelligence into the platform.
=> [socradar] Add SOCRadar external import connector

external-import/sentinel-incidents/src/sentinel_incidents_connector/client_api.py, external-import/sentinel-incidents/src/sentinel_incidents_connector/connector.py, external-import/sentinel-incidents/src/sentinel_incidents_connector/converter_to_stix.py
* get a fresh token on every run instead of on every launch
* handle stix2 errors to avoid blocking imports
* check if directory's path is valid before creating a Directory observable
* #3325 
* #3344 
These are naive solutions to fix the issue as quickly as possible. But better solutions exist, such as:
- add a refresh strategy when the current token is about to expire
- perform data validation (pydantic models) for both Sentinel’s responses and OpenCTI’s objects
=> [Sentinel Incidents] 401 Unauthorized error + missing Directory's path

internal-enrichment/hatching-triage-sandbox/docker-compose.yml, internal-enrichment/hatching-triage-sandbox/src/config.yml.sample, internal-enrichment/hatching-triage-sandbox/src/hatching-triage-sandbox.py
* Add playbook compatibility and handle bundle when STIX objects is not in scope defined
* URL analysis submission support
* Remove confidence_level inf configuration files as it is not used anymore since OpenCTI version >= 6.0.0
* 
* https://github.com/OpenCTI-Platform/connectors/issues/2931
=> [Hatching Triage Sandbox] URL analysis support + Playbook compatibility

.circleci/vars.yml, internal-import-file/import-file-yara/.dockerignore, internal-import-file/import-file-yara/.gitignore, internal-import-file/import-file-yara/Dockerfile, internal-import-file/import-file-yara/Dockerfile_fips, internal-import-file/import-file-yara/README.md, internal-import-file/import-file-yara/docker-compose.yml, internal-import-file/import-file-yara/entrypoint.sh, internal-import-file/import-file-yara/src/config.yml.sample, internal-import-file/import-file-yara/src/import-file-yara.py, internal-import-file/import-file-yara/src/requirements.txt
New internal import connector that handle .yar file.
* https://github.com/OpenCTI-Platform/connectors/issues/3235
=> [ImportFileYARA]: Create an import file connector dedicated to import YARA files/rules

external-import/sentinel-incidents/docker-compose.yml
Update sentinel-incidents docker-compose.yml to include the mandatory "CONNECTOR_DURATION_PERIOD"
=> Update sentinel-incidents docker-compose.yml

external-import/cape/src/cape/telemetry.py
* Fix conflict between pycti and stix2.v21 Malware classes
* Fix Get_Malware receiving list instead of string
* Fix conflict between pycti and stix2.v21 Indicator classes
* Fixed to assign labels in the appropriate format
* #3355
=> Fix connector-cape bugs

stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py
* explicitly handle error when Authentication fails and logs server response details
*  https://github.com/OpenCTI-Platform/connectors/issues/3351
Notion investigation page https://www.notion.so/filigran/Sentinel-Intel-Connector-Not-Sending-Data-18b8fce17f2a80369730d92656219234
=> [SENTINEL-INTEL] fix: add explicit error when authentication fails

external-import/virustotal-livehunt-notifications/src/livehunt/builder.py, external-import/virustotal-livehunt-notifications/src/livehunt/livehunt.py
* Remove `sys.exit()` on uncaught exceptions (issue's fix)
* Use `self.helper.connector_logger` logging functions (improvement)
* Fix `config.yml` path to launch connector manually (other fix)
* #3334
=> [Virustotal Livehunt Notifications] Fix ModuleNotFound error

external-import/sekoia/README.md, external-import/sekoia/docker-compose.yml, external-import/sekoia/src/config.yml.sample, external-import/sekoia/src/sekoia.py
Sekoia provides a list of sources who have reported the information. The information is contained in a custom Sekoia field, named "x_inthreat_sources_refs".
The various sources would have to be imported into the platform. 
* Since STIX does not allow multiple “Author”, we record them in labels, e.g. “source:Name1”, “source:Name2”, ...
* https://github.com/OpenCTI-Platform/connectors/issues/3176
=> [Sekoia] Retrieve the list of entity sources

external-import/zvelo/src/zvelo_connector/converter_to_stix.py
* Fix Type Error
* https://github.com/OpenCTI-Platform/connectors/issues/3409
Error due to the typo between "c" and "C" leading to the use of `callable ` method rather than `Callable` type
```bash
def known_converter_error(
func: Callable[["ConverterToStix", ...], stix2.v21._STIXBase21),
) -> Callable[["ConverterToStix", ...], stix2.v21._STIXBase21]:
```
Test by raising a ConverterError
```{"timestamp": "2025-02-12T06:40:12.681908Z", "level": "ERROR", "name": "Zvelo CTI", "message": "[CONNECTOR] An error occurred while converting {'ip_info': [{'ip': '162.241.124.142'}], 'url': 'https://yaseui.net/Ik98ufh9FIV8FUV', 'discovered_date': '2025-02-12T05:54:58Z', 'brand': '1&1 ionos', 'confidence_level': 100, 'last_active_date': '2025-02-12T06:36:05.057148Z', 'status': 'active', …
```
=> [Zvelo] Fix type error

internal-import-file/import-document/src/reportimporter/core.py, internal-import-file/import-file-misp/src/import-file-misp.py, internal-import-file/import-file-stix/src/import-file-stix.py, internal-import-file/import-file-yara/src/import-file-yara.py
[client] Add markings support for workbench
OpenCTI
- https://github.com/OpenCTI-Platform/opencti/issues/9882
Client-Python
- https://github.com/OpenCTI-Platform/client-python/pull/825
=> [client] Add markings support for workbench

external-import/recorded-future/src/rflib/rf_playbook_alerts.py
* Fix unhashable dict issue by getting author ID to get playbook alerts Novel Identity Exposure
* https://github.com/OpenCTI-Platform/connectors/issues/3216
Expected output
=> [Recorded Future] Fix unhashable dict issue by getting author ID

external-import/crowdstrike/src/crowdstrike_feeds_connector/indicator/builder.py, external-import/group-ib/src/data_to_stix2.py, external-import/malpedia/src/malpedia_services/converter_to_stix.py, external-import/proofpoint-tap/tests/test_domain/test_use_cases/test_ingest_incident.py, external-import/recorded-future/src/rflib/rf_alerts.py, external-import/recorded-future/src/rflib/rf_playbook_alerts.py, external-import/recorded-future/src/rflib/rf_to_stix2.py, external-import/recorded-future/src/rflib/risk_list.py, external-import/threatfox/src/main.py, internal-enrichment/greynoise/src/main.py, internal-enrichment/ipqs/src/ipqs/builder.py, internal-enrichment/malbeacon/src/malbeacon_converter.py, internal-enrichment/recordedfuture-enrichment/src/rflib/rf_to_stix2.py, internal-enrichment/reversinglabs-malware-presence/src/main.py, internal-enrichment/reversinglabs-spectra-analyze/src/main.py, internal-enrichment/reversinglabs-spectra-intel-submission/src/main.py, internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/converter_to_stix2.py, internal-enrichment/virustotal/src/virustotal/builder.py, internal-import-file/import-file-yara/src/import-file-yara.py, stream/tanium/src/sightings.py
The `valid_from` and `valid_until` fields generated in Python within some connectors logic are not predictive, contrary to the expectations of OpenCTI platform's mechanisms. These fields, like IDs, must always be predictive. Otherwise, it is preferable to leave them empty, allowing the platform to populate them with its algorithms and rules.
Currently, using now for these fields when no data is provided disrupts the decay logic and other business processes implemented within OpenCTI. Moreover, this approach is redundant, as the platform already defaults to now when the fields are left empty.
* Remove now date from `valid_from` attributes and replace by original and immutable date OR remove the field
* Fix format for Crowdsrtike IOC builder file
* Fix format for Proofpoint TAP
* Fix …
=> [Connectors] Fix valid_from date in some connectors + format files + correct relationships direction

stream/sentinel-intel/src/sentinel_intel_connector/api_handler.py, stream/sentinel-intel/src/sentinel_intel_connector/connector.py
- raise errors instead of returning None in _send_request()
- refacto error handling in API handler
- handle API handler errors in process_message()
* #3444 
Related to https://github.com/OpenCTI-Platform/connectors/pull/3425
=> [Sentinel-Intel] Improve error handling in Sentinel API client

internal-enrichment/attribution-tools/Dockerfile
* Install `openblas`, `gfortran`, and `xsimd` in attribution-tools container
The build of the container for `attribution-tools` appears broken now, at least on ARM64 architecture. Not sure if it's also broken on x86-64 (I presume it is fine there?).
Installing dependencies OpenBLAS and gFortran seem to fix the breakage.
During fixing, I also noticed that some of the Python code will use `xsimd` if it is available. As this could potentially speed up analysis by leveraging streaming instructions, I figured I would add this as well to the container.
- https://github.com/OpenCTI-Platform/connectors/issues/3476
=> [attribution-tools] Install gfortran, openblas, xsimd

internal-enrichment/urlscan-enrichment/README.md, internal-enrichment/urlscan-enrichment/docker-compose.yml, internal-enrichment/urlscan-enrichment/src/config.yml.sample, internal-enrichment/urlscan-enrichment/src/main.py, internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/config_variables.py
* Make indicator creation optional
* Add a URLSCAN_ENRICHMENT_CREATE_INDICATOR variable to decide whether or not to create indicator when enrichment is done
- https://github.com/OpenCTI-Platform/connectors/issues/3477
=> [urlscan-enrichment] Make indicator creation optional

external-import/misp/src/misp.py
* Handle PAP markings
* Use TLP:CLEAR instead of TLP:WHITE
* https://github.com/OpenCTI-Platform/connectors/issues/3352
*
=> [MISP] handle PAP markings, use TLP:CLEAR instead of TLP:WHITE

external-import/vulncheck/src/vclib/sources/nistnvd2.py
* Replace `extend()` with `append()` to correctly add the object without string iteration.
* This pull request fixes an issue in the vulncheck connector (nistnvd2 source) where the SCOPE_SOFTWARE data was not being handled correctly. The error occurred because extend was used to add a single relationship object, which caused Python to iterate over the object (string iteration). 
* https://github.com/OpenCTI-Platform/connectors/issues/3524
=> [vulncheck ] Use append for SCOPE_SOFTWARE in vulncheck (nistnvd2 source)

external-import/malwarebazaar-recent-additions/src/malwarebazaar-recent-additions.py
Added some features in MalwareBazaar Connector.
* Added indicator creation with sha256 for each artifact
* Added relationship between indicator and artifact
* Added a visual change to show the last execution in connector screen
* https://github.com/OpenCTI-Platform/connectors/issues/3205
=> [MalwareBazaar] Add SHA256 Indicators and visual change

external-import/taxii2/src/connector/connector.py, external-import/taxii2/src/connector/process_objects.py
* Defined variable type for integers which are pulled from config. In some customer environments these could be stored as strings, which will cause an error.
* https://github.com/OpenCTI-Platform/opencti/issues/9949
* https://github.com/OpenCTI-Platform/connectors/issues/3525
=> [Taxii2] Handling Int in Config

external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/connector.py, external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/converter_to_stix.py, external-import/microsoft-defender-incidents/src/microsoft_defender_incidents_connector/utils.py
* check IP value version
* add a check for System entity creation
* https://github.com/OpenCTI-Platform/connectors/issues/3556
* https://github.com/OpenCTI-Platform/connectors/issues/3539
=> [microsoft-defender-incidents]: Errors when converting “IPEvidence” containing IPv6 addresses

external-import/ipsum/README.md, external-import/ipsum/docker-compose.yml, external-import/ipsum/src/config.yml.sample, external-import/ipsum/src/external_import_connector/config_variables.py, external-import/ipsum/src/external_import_connector/connector.py, external-import/ipsum/src/external_import_connector/converter_to_stix.py
* No default marking: Add default TLP:CLEAR marking as the source is OSINT
* Add config.yml.sample
* Update documentation
* https://github.com/OpenCTI-Platform/connectors/issues/3514
=> [IPSum] Connector needs improvements

.github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml, renovate.json
* Manually renovate pre-commit-config linters version
* Add pre-commit-config to renovate bot
* Add pre-push hook to check if commits are signed
* Alter PR Template to remind contributor to sign their commits
* https://github.com/OpenCTI-Platform/connectors/issues/3565
* https://github.com/OpenCTI-Platform/connectors/issues/3566
```bash
python -m pip install pre-commit
pre-commit install --hook-type pre-commit --hook-type pre-push
git checkout -b "test_branch"
touch test.py
echo "import os" > test.py
git add test.py
git commit -m "signed commit with flake8 error" -S
echo 'import os
_ = os.environ' > test.py
git add test.py
git commit -m "unsigned commit" --no-gpg-sign
git push -u origin test_branch
git checkout master
git branch -D test_branch 
rm test.py
```
=> [ALL] - feat: add tools to ensure commits are signed and renovate pr-commit-config

external-import/ransomwarelive/src/lib/ransom_conn.py
* Fix import victim key attribute
* https://github.com/OpenCTI-Platform/connectors/issues/3374
This following issue can be raised when the configuration variable `CONNECTOR_CREATE_THREAT_ACTOR` is not set to True
```{"timestamp": "2025-01-31T13:21:39.672778Z", "level": "ERROR", "name": "Ransomware Live", "message": "cannot access local variable 'relation_sec_TA' where it is not associated with a value", "exc_info": "Traceback (most recent call last):\n  File \"/opt/connector/lib/ransom_conn.py\", line 552, in stix_object_generator\n    bundle.append(relation_sec_TA)\n                  ^^^^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'relation_sec_TA' where it is not associated with a value", "taskName": null}```
=> [RansomwareLive] Fix import victim key attribute

external-import/silobreaker/src/silobreaker.py
*  Improve error handling while fetching list to not send only empty dict when error occurs
* https://github.com/OpenCTI-Platform/connectors/issues/3642
https://www.notion.so/filigran/Silobreaker-Strange-behavior-on-lists-filters-1ba8fce17f2a8085add4d24ae6693abd
=> [Silobreaker] Improve error handling while fetching list

templates/external-import/src/external_import_connector/connector.py, templates/external-import/src/main.py, templates/internal-enrichment/src/internal_enrichment_connector/connector.py, templates/internal-enrichment/src/main.py, templates/internal-export-file/src/internal_export_file_connector/connector.py, templates/internal-export-file/src/main.py, templates/internal-import-file/src/internal_import_file_connector/connector.py, templates/internal-import-file/src/main.py, templates/stream/src/main.py, templates/stream/src/stream_connector/connector.py
Isolate the helper and config from the connector instance
- https://github.com/OpenCTI-Platform/connectors/issues/3635
=> [Templates] Isolate config & helper from the connector template

external-import/bambenek/src/bambenek_connector/config_variables.py, external-import/bambenek/src/bambenek_connector/connector.py, external-import/bambenek/src/bambenek_connector/converter_to_stix.py
* Resolution of various bugs 
* https://github.com/OpenCTI-Platform/connectors/issues/3621
* https://github.com/OpenCTI-Platform/connectors/issues/3620
=> [Bambenek] fix: stix id should be determinist, correct observable type is Domain-Name, generated stix objects should be sent to the platform

stream/zscaler/src/stream_connector/connector.py
I updated the script so that domains are added to **"Custom URLs"** instead of **"URLs retaining parent category"** in Zscaler. 
Specifically:
In get_**zscaler_blocked_domains**, the script now reads the blocked domain list from the **urls** field instead of **dbCategorizedUrls**.
In **send_to_zscaler**, both creation and deletion events use **"urls"** in the payload instead of **"dbCategorizedUrls"**.
These changes ensure that domains appear under **"Custom URLs"** within the chosen Zscaler category.
* https://github.com/OpenCTI-Platform/connectors/issues/3690
=> [Zscaler] Modified category blacklist

external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py
* handle of FileHashes contained in File Evidence
* https://github.com/OpenCTI-Platform/connectors/issues/3673
=> [microsoft-sentinel-incidents]: File hashes contained in File Evidence are not correctly converted into Observables

external-import/misp/README.md, external-import/misp/docker-compose.yml, external-import/misp/src/config.yml.sample, external-import/misp/src/misp.py
Currently the Attributes tags take precedence over the Events tags (if attribute has tags)
This commit allows for the option to allow the labels that are present on an Event (OpenCTI Reports) to apply on top of the labels set by the Attributes (Observables and/or Indicators). While not changing behaviour by introducting a setting that defaults to the previous behaviour.
* Add setting for this new feature with default of old behaviour
* Add the Event labels to the Attribute labels when setting is set to true, otherwise keep old behaviour
* https://github.com/OpenCTI-Platform/connectors/issues/3495
This would be my first PR to this project any guidance where needed is appreciated.
=> [MISP] Adds propagate labels from Event to Attribute option #3495

external-import/mandiant/src/connector/reports.py, internal-export-file/export-file-csv/src/export-file-csv.py
* Add a global try/cath per csv line, to allow exporting csv event if one line has issue
* Add some test on value that are lists inside, to avoid crashing on null/None values
Error log on catch looks like:
```
{"timestamp": "2025-03-31T12:55:02.411462Z", "level": "WARNING", "name": "ExportFileCsv", "message": "Error with csv input data, one line cannot be exported.sequence item 0: expected str instance, NoneType found"}
```
On opencti connector view when there is an error:
* closes #3617
=> [export-csv] Improve management when data are incomplete (#3617)

external-import/thehive/src/thehive.py
Hello 
I've updated the script to correctly handle the **_updatedAt** field. Previously, the function get_updated_date was checking for **updatedAt** (without the underscore), which caused it to always fall back on **_createdAt**, even when **_updatedAt** was available.
**In this update:**
- The condition now properly checks for the presence of _updatedAt before falling back to _createdAt.
- This change ensures that the most accurate update timestamp is used when generating STIX bundles for alerts and cases.
- The construct_query method has also been verified to query using _updatedAt, aligning the entire flow with the correct timestamp field.
- I have also add the underscore in the log of "_createAt" (line 324)
Thank you.
The connector now respects the intended logic for object updates
* …
=> Thehive fix "updateAt"

external-import/tenable-security-center/tenable_security_center/adapters/tsc_api/v5_13_from_asset.py, external-import/tenable-security-center/tests/test_adapters/test_tsc_api/test_v5_13_from_asset.py
* Explicitly converts both scannedIPs and repository id to strings to handle type inconsistencies.
* Adds a unit test to verify the corrected output from the API adapter.
* https://github.com/OpenCTI-Platform/connectors/issues/3564
Investigation Notion Page : https://www.notion.so/filigran/Tenable-Security-Center-Varying-repository_id-types-in-API-response-should-be-handled-1b68fce17f2a802eaeede3457963836c
=> [Tenable security center] feat: inconsistent repository id types in api response could be handled

.github/workflows/auto-set-labels.yml
* Add automatically "filigran team" labels on PR from Filigran employees.
Same as opencti one https://github.com/OpenCTI-Platform/opencti/blob/master/.github/workflows/auto-set-labels.yml
*
*
=> [CI] add auto label filigran team

external-import/cve/src/services/client/api.py
* Use the correct apiKey field for header
Output
- Response status is 200 even if the wrong key is given BUT it's limited 
- Following NVD:
> Including apiKey:{key value}, (without brackets or spaces) allows users to make a greater number of requests in a given time than they could otherwise
Link to NVD documentation : [HERE](https://nvd.nist.gov/developers/start-here#:~:text=Including%20apiKey%3A%7Bkey%20value%7D%2C%20(without%20brackets%20or%20spaces)%20allows%20users%20to%20make%20a%20greater%20number%20of%20requests%20in%20a%20given%20time%20than%20they%20could%20otherwise)
This change add apiKey field to avoid rate limiting issues
* https://github.com/OpenCTI-Platform/connectors/issues/3813
=> [CVE] Use the correct apiKey field for header

external-import/dragos/dragos/adapters/config/env.py, external-import/dragos/dragos/adapters/config/yaml.py, external-import/dragos/dragos/interfaces/config.py, external-import/dragos/tests/tests_dragos/tests_adapters/tests_config/test_env.py, external-import/dragos/tests/tests_dragos/tests_adapters/tests_config/test_yaml.py, external-import/dragos/tests/tests_dragos/tests_interfaces/test_config.py
* add api_secret for dragos
Aside :
* fix None config values handled by pycti
* fix scopes as a joined str for pycti interpretation
* N/A
=> [Dragos] fix: missing api_secret in Dragos config

stream/qradar/src/qradar.py
* Better handle reference sets creation responses
* https://github.com/OpenCTI-Platform/connectors/issues/3853
=> [qradar]: No error logs when the connector is not able to contact configured QRadar instance

internal-import-file/import-document-ai/src/reportimporter/core.py, internal-import-file/import-document-ai/src/reportimporter/util.py
* When a TTP is extracted by Import Document AI connector, check if it exists in the platform to avoid duplication
* https://github.com/OpenCTI-Platform/connectors/issues/3871
There has been a quick demo to product to ensure the solution is sufficient
=> [Import Document AI] Import Document AI matches existing TTP

external-import/disinfox/docker-compose.yml, external-import/disinfox/src/config.yml.sample, external-import/disinfox/src/external_import_connector/config_variables.py
ensure same name is used everywhere while mitigating breaking changes
* replace `DISINFOX_BASE_URL` by `DISINFOX_URL` as `get_config_variable()` argument
* ensure same name is used everywhere (_docker-compose.yml_, _config.yml_)
* #3904 
This PR ensure same config behavior when launching the connector both manually and as a docker image, while mitigating the breaking changes. This is why the code has been changed to correspond to the _.env_ file and not the opposite.
=> [Disinfox] Rename env var for get_config_variable()

external-import/dogesec-ctibutler/entrypoint.sh, external-import/dogesec-obstracts/entrypoint.sh, external-import/dogesec-stixify/entrypoint.sh, external-import/dogesec-vulmatch/entrypoint.sh
* modify entrypoint file path to point to correct file
- https://github.com/OpenCTI-Platform/connectors/issues/3930
=> [dogesec cti butler/obstracts/stixify/vulmatch] fix entrypoints for dogesec-*

external-import/feedly/src/feedly/opencti_connector/connector.py
* Modify the relationship_type when transforming threat actors to intrusion set if the type is located-at
* Not required but implemented:
* Fix objects_refs when present during transformation threat-actor to intrusion-set
* https://github.com/OpenCTI-Platform/connectors/issues/3915
=> [Feedly] Modify relationship_type when transforming threat actors to intrusion set

external-import/ransomwarelive/requirements.txt
* Add missing whois library in requirements.txt file
* https://github.com/OpenCTI-Platform/connectors/issues/3941
=> [ransomwarelive] Add missing whois library

external-import/misp/src/misp.py, external-import/misp/src/requirements.txt
* add error handling in `run()` method
* replace deprecated `datetime` methods
* #3156 
This PR doesn't solve the issue itself (I couldn't reproduce the mentioned bug), but the connector doesn't crash anymore and instead, re-launch the `run()` method after the interval (similar to `schedule_process` behavior).
=> [MISP] Add error handling to avoid the connector to crash

internal-enrichment/virustotal/README.md, internal-enrichment/virustotal/docker-compose.yml, internal-enrichment/virustotal/src/config.yml.sample, internal-enrichment/virustotal/src/virustotal/builder.py, internal-enrichment/virustotal/src/virustotal/client.py, internal-enrichment/virustotal/src/virustotal/virustotal.py
*  Updated the code to include additional attributes from Virustotal API response to Notes.
* Updated the VirusTotal client to fetch URL-related objects.
* https://github.com/OpenCTI-Platform/connectors/issues/4024
=> [Virustotal] Adds Attributes for Virustotal Notes

external-import/email-intel-imap/src/base_connector/requirements.txt, external-import/email-intel-imap/src/requirements.txt, external-import/email-intel-microsoft/src/base_connector/requirements.txt, external-import/email-intel-microsoft/src/requirements.txt
* Fix dependencies conflict: 
```
#0 6.365 ERROR: Cannot install -r /opt/opencti-connector-email-intel-imap/base_connector/requirements.txt (line 1), -r /opt/opencti-connector-email-intel-imap/base_connector/requirements.txt (line 3) and pydantic==2.10.6 because these package versions have conflicting dependencies.
#0 6.366 
#0 6.366 The conflict is caused by:
#0 6.366     The user requested pydantic==2.10.6
#0 6.366     The user requested pydantic==2.10.6
#0 6.366     pydantic-settings 2.8.1 depends on pydantic>=2.7.0
#0 6.366     pycti 6.6.12 depends on pydantic~=2.11.3
#0 6.366 
#0 6.366 To fix this you could try to:
#0 6.366 1. loosen the range of package versions you've specified
#0 6.366 2. remove package versions to allow pip to attempt to solve the dependency conflict
```
* …
=> [EmailIntelImap & EmailIntelMicrosoft] Fix: Align required Pydantic version for connectors with PyCTI dependencies.

stream/splunk/README.md, stream/splunk/docker-compose.yml, stream/splunk/src/config.yml.sample, stream/splunk/src/splunk.py
* Add Basic authentication to Splunk connector based on [docs](https://docs.splunk.com/Documentation/Splunk/latest/RESTUM/RESTusing#Authentication_and_authorization). 
* Basic authentication can help with incredibly old environments like Splunk<7.3 where you can't use Bearer authentication.
- https://github.com/OpenCTI-Platform/connectors/issues/4055
=> [splunk] Add basic auth for splunk<7.3

external-import/sekoia/README.md, external-import/sekoia/docker-compose.yml, external-import/sekoia/src/config.yml.sample, external-import/sekoia/src/sekoia.py
The number of objects fetched from the Sekoia API is currently hardcoded to 200, which may be too low, especially during the initial ingestion of historical intelligence. This PR allows the user to configure this setting while keeping `200` as the default value.
- https://github.com/OpenCTI-Platform/connectors/issues/4073
=> [Sekoia] Allow configuration of API query limit

external-import/microsoft-sentinel-incidents/src/microsoft_sentinel_incidents_connector/converter_to_stix.py
* Correct syntax using json.loads method
* https://github.com/OpenCTI-Platform/connectors/issues/4107
Tested only with basic local use cases : 
* using remediation_steps = "abc"=> JSONDECODEERROR is excepted gracefully
* using remediation_steps = None => empty list is provided as expected
=> [Microsoft Sentinel Incidents] fix: Parsing Remediation steps should not raise error.

external-import/malwarebazaar/.dockerignore, external-import/malwarebazaar/Dockerfile, external-import/malwarebazaar/README.md, external-import/malwarebazaar/docker-compose.yml, external-import/malwarebazaar/entrypoint.sh, external-import/malwarebazaar/src/config.yml.sample, external-import/malwarebazaar/src/main.py, external-import/malwarebazaar/src/malwarebazaar_connector/__init__.py, external-import/malwarebazaar/src/malwarebazaar_connector/client_api.py, external-import/malwarebazaar/src/malwarebazaar_connector/config_loader.py, external-import/malwarebazaar/src/malwarebazaar_connector/connector.py, external-import/malwarebazaar/src/malwarebazaar_connector/converter_to_stix.py, external-import/malwarebazaar/src/malwarebazaar_connector/utils.py, external-import/malwarebazaar/src/requirements.txt
* Based on Conversation in PR (https://github.com/OpenCTI-Platform/connectors/pull/3503) - @romain-filigran request a new MalwareBazaar Connector that would create File Observables.
* This new connector supports the proposed changes of:
* Creates a File Observable, Indicator, and a Relationship between the entities
* No malware file is uploaded
* Uses new 6.6.x connector template to send data to RabbitMQ
* Sets an `x_opencti_score` based on the configuration, defaulted to 100 
N/A
None
=> [malwarebazaar] MalwareBazaar Connector that will create a File Observable; Supports disabling of the upload of the actual malware file.

internal-enrichment/urlscan-enrichment/src/main.py, internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/client.py, internal-enrichment/urlscan-enrichment/src/urlscan_enrichment_services/utils.py
* Do not raise but warn when user submits url and urlscan returns information but no DOM snapshot.
* Add a condition when preparing the file, the title of the snapshot must exist.
* #4111
=> [URLScan-Enrichment] Fix error when no snapshot

external-import/sekoia/README.md, external-import/sekoia/docker-compose.yml, external-import/sekoia/src/config.yml.sample, external-import/sekoia/src/sekoia.py
* Add an option in the connector to configure the import of indicators, with or without relationships avoiding big ingestion delays
* Remove bypass_split as it is not used anymore
* Update logger
* Remove deprecated usage of `utcnow()`
* https://github.com/OpenCTI-Platform/connectors/issues/4184
=> [Sekoia] Small fixes + add new config on importing IOC related object

external-import/google-ti-feeds/README.md, external-import/google-ti-feeds/connector/src/custom/configs/batch_processor_config.py, external-import/google-ti-feeds/connector/src/custom/mappers/gti_reports/gti_file_to_stix_file.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/orchestrator.py, external-import/google-ti-feeds/pyproject.toml, external-import/google-ti-feeds/tests/custom/mappers/gti_reports/test_gti_file_to_stix_file.py
GTI’s `creation-date` can sometimes point to the future/past trick pulled by malware authors to forge file timestamps, aiming to bypass SIEMs and other detection solutions.
While this timestamp is valuable for EDR, YARA, and other detection mechanisms, it's currently mapped to the wrong field in STIX 2.1.
I'm going to correct this based on the following mapping rules:
|        GTI Field        |   STIX 2.1 Mapping  |
| :---------------------: | :-----------------: |
|     `creation-date`     |   File SCO `ctime`  |
| `first_submission_date` | Indicator `created` |
And adding verified in readme + small increment bug in work name
* https://github.com/OpenCTI-Platform/connectors/issues/4201
After fix only the ctime on file is in the future, and not the creation date of the indicator.
Work …
=> [Google TI Feeds] indicators in future

connectors-sdk/tests/conftest.py, external-import/tenable-security-center/tests/conftest.py
* Remove strict check of pip audit
* https://github.com/OpenCTI-Platform/connectors/issues/4325
`check=False` (safe default)
This will let the process run and print any pip-audit errors, but it won’t raise an exception or stop your script.
=> [connectors] Remove strict check of pip audit

shared/tools/composer/generate_connectors_manifest.py
If a `logo.png` file is present in the metadata folder of a connector, when generating the catalogue manifest it will be encoded in base64 and put as "logo" field for this connector.
=> [composer] encode connectors logo in base64 in final manifest (#4627)

external-import/misp-feed/src/misp-feed.py
* Add a log message if misp-feed connector is ran in "s3" mode (as opposed to "url")
There is a bug in misp-feed connector that makes it unable to work if MISP_FEED_SOURCE_TYPE is set to "s3" : on line 2224, a message is logged, but this message is not present in the "s3" processing block.
This PR adds the message in this block – with some informative data – so that the connector does not fail.
=> Fixed issue in misp-feed that prevented import from S3 bucket

external-import/threatfox/src/.env.sample, shared/tools/composer/generate_connectors_config_json_schemas.sh
When opening a pull request, the CI job build_manifest is started on connectors that have changes from the branch to origin/master regarding if the branch is rebased or no.
This induce the generation of connectors manifest that haven't been changed in the scope the PR.
- This PR is based from the last commit of the 12th of september https://github.com/OpenCTI-Platform/connectors/commit/f2d5e09126949a08edc81fc38931e424f99e263f
- The git diff with origin/master at the time includes a lot of connectors :
* First commit simulate today's behavior. The CI run the build_manifest on the diff from the branch to `origin/master`
**5min59s**
https://app.circleci.com/pipelines/github/OpenCTI-Platform/connectors/11869/workflows/7a23e58b-d0d1-4f7c-8bea-8258bea3072e/jobs/208597
* 2nd commit is the CI …
=> [CircleCI] build_manifest on diff with origin/master instead forked master in PR

external-import/pgl-yoyo/Dockerfile
The building of the rolling images fails in the CI, due to missing git binary
* follow templates and add git libmagic etc...
* #4823
=> [PGL-YoYo] Fix Dockerfile

external-import/cpe/src/connector.py
* Change the header in the API request to NIST API from `api_key` to `apiKey` as per NIST documentation [[1](https://nvd.nist.gov/developers/start-here#:~:text=API%20keys%20are,is%20case%20sensitive.)]
* This is now consistent with what is used in the [CVE connector](https://github.com/OpenCTI-Platform/connectors/blob/17d8be603c4bfb9e8d36d42c043188cf83133181/external-import/cve/src/services/client/api.py#L21).
* The API calls still worked, but behaved as if no API key was provided - which the API makes possible, however, there is stricter rate limitation.
* https://github.com/OpenCTI-Platform/connectors/issues/4830
=> [CVE] Fixing API key header to follow NIST documentation

stream/microsoft-sentinel-intel/src/microsoft_sentinel_intel/connector.py
* fix: Remove mistaken set_state
* https://github.com/OpenCTI-Platform/connectors/issues/4840
=> [MicrosoftSentinelIntel] Remove mistaken set_state

external-import/crowdstrike/docker-compose.yml
These types are automatically included in the ingestion but seems to fail and the whole connector stops importing indicators. Since they aren't supported anyway, we might just ignore them here to avoid misbehaviours in user's instances.
* Add `username` and `password` to default indicator exclude types in `docker-compose.yml` file to skip them. They were being pulled by the connector and getting invalid type errors, causing the connector to stop importing other indicators.
* Closes #4847
=> [crowdstrike] set the default to ignore password and username types

external-import/google-ti-feeds/connector/src/custom/client_api/client_api_base.py, external-import/google-ti-feeds/connector/src/custom/configs/campaign/batch_processor_config_campaign.py, external-import/google-ti-feeds/connector/src/custom/configs/report/batch_processor_config_report.py, external-import/google-ti-feeds/connector/src/custom/configs/vulnerability/batch_processor_config_vulnerability.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/base_orchestrator.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/campaign/orchestrator_campaign.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/malware/orchestrator_malware.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/report/orchestrator_report.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/threat_actor/orchestrator_threat_actor.py, external-import/google-ti-feeds/connector/src/custom/orchestrators/vulnerability/orchestrator_vulnerability.py
This PR is part of the umbrella PR #4810 to solve the issues identified in #4801
Before:
After:
Umbrella PR: https://github.com/OpenCTI-Platform/connectors/pull/4810
Base Issue: https://github.com/OpenCTI-Platform/connectors/issues/4801
Sometimes, you can see the number overshot the total slightly, this is due to the api sending new data in the last page while processing them.
=> [Google TI] Fix increment number in work description #4810

external-import/google-ti-feeds/connector/src/custom/configs/gti_config_common.py, external-import/google-ti-feeds/tests/custom/configs/test_gti_config.py, external-import/google-ti-feeds/tests/custom/test_orchestrator.py
I forgot to set 'enable_decoding=False' for pydantic settings, leading to a bad usage of the type ListFromStrings from the SDK.
=> [Google TI] Fix pydantic for catalog integration

stream/misp-intel/src/config.yml.sample, stream/misp-intel/src/models/configs/base_settings.py, stream/misp-intel/src/models/configs/config_loader.py, stream/misp-intel/src/models/configs/misp_configs.py
* Fix configuration defaults to be None on empty env var
* https://github.com/OpenCTI-Platform/connectors/issues/4859
=> [MispIntel] Fix configuration defaults to be None on empty env var

external-import/recorded-future/docker-compose.yml, external-import/recorded-future/src/config.yml.sample, external-import/recorded-future/src/main.py, external-import/recorded-future/src/models/configs/config_loader.py, external-import/recorded-future/src/models/configs/recorded_future_configs.py
I was able to reproduce the bug straight forward by launching the connector with docker and .env (work with actual config.yml.sample):
This one is due to the fact that in the ConfigLoader the conf for the connector is loaded under `rf`:
This mean it will look for a variable starting with `rf_` which is the case in the sample config in yml:
but not in the readme and docker one:
So the fix consist to set back to recorded_future:
And after that the connector launch but with a new error:
The TLP provided in the doc are not lowercase and so don't match our Literal.
I've created a small validator to convert it to lower:
And then the connector start without trouble:
#4871 
The manifest for the connector is generated with the key prefix "RF_" so we need to check back the good regeneration after …
=> [Recorded Future] crash since 6.8.1 (#4871)

external-import/socradar/.dockerignore, external-import/socradar/.env.sample, external-import/socradar/Dockerfile, external-import/socradar/README.md, external-import/socradar/docker-compose.yml, external-import/socradar/entrypoint.sh, external-import/socradar/requirements.txt, external-import/socradar/src/config.yml.sample, external-import/socradar/src/lib/__init__.py, external-import/socradar/src/lib/api_client.py, external-import/socradar/src/lib/config_loader.py, external-import/socradar/src/lib/converter_to_stix.py, external-import/socradar/src/lib/radar.py, external-import/socradar/src/main.py
- Update config:
* remove 'radar_' suffix of config vars (from _config.yml_) 
* add runtime validation (with `pydantic_settings` lib)
* deprecate `RADAR_RUN_INTERVAL` (replaced by `CONNECTOR_DURATION_PERIOD`)
* deprecate `RADAR_COLLECTIONS_UUID` (replace by `RADAR_FEED_LISTS` - flat version)
* update _config.yml.sample_ / add _.env.sample_
* update README
- Update Docker files:
* add files from templates
* add env vars examples in _docker-compose.yml_
* update _Dockerfile_
- Replace deprecated code:
* use `self.helper.schedule_process` method
* use `self.helper.connector_logger` log methods
* use `self.helper.create_stix2_bundle` method
- Error handling improvement:
* add traceback in _main.py_
* add 2 abstraction layers: `RadarAPIClient` and `ConverterToStix`
* wrap expected errors with …
=> [SOCRadar] Update legacy code

connectors-sdk/connectors_sdk/models/octi/_common.py, connectors-sdk/connectors_sdk/models/octi/activities/analyses.py, connectors-sdk/connectors_sdk/models/octi/activities/observations.py, connectors-sdk/connectors_sdk/models/octi/knowledge/arsenal.py, connectors-sdk/connectors_sdk/models/octi/knowledge/entities.py, connectors-sdk/connectors_sdk/models/octi/knowledge/locations.py, connectors-sdk/connectors_sdk/models/octi/knowledge/techniques.py, connectors-sdk/connectors_sdk/models/octi/knowledge/threats.py, connectors-sdk/connectors_sdk/models/octi/relationships.py, connectors-sdk/connectors_sdk/models/octi/settings/taxonomies.py
* Consistency in `Field` definitions (e.g., use of explicit default values, remove ellipsis (...), etc.).
* Order of field arguments (preferably alphabetical).
* Migration from `Optional[<type>]` to `<type> | None` for optional fields, in line with [Pydantic v2](https://docs.pydantic.dev/latest/concepts/fields/#default-values). 
* #4889
=> [connector-sdk] Standardize Pydantic model syntax

external-import/recorded-future/src/rflib/rf_to_stix2.py
* Incorrect object used when adding converted TTP
* https://github.com/OpenCTI-Platform/connectors/issues/4892
=> [recorded-future] Exception when processing certain Analyst Notes

external-import/abuseipdb-ipblacklist/src/external_import_connector/connector.py, external-import/abuseipdb-ipblacklist/src/external_import_connector/converter_to_stix.py, external-import/abuseipdb-ipblacklist/tests/conftest.py, external-import/abuseipdb-ipblacklist/tests/test-requirements.txt, external-import/abuseipdb-ipblacklist/tests/test_connector.py
* Add `x_opencti_create_indicator` instead of manually creating indicator
*
* Closes #4783 
*
=> [abuseipdb-ipblacklist] fix discrepancy between observable and indicator scores (#4783)
